/**
 * lib/zones/data.ts
 * Source unique des zones desservies par ONE CONNEXION.
 * Paris 75 : données inline (20 arrondissements).
 * Banlieue  : importée depuis les fichiers par département.
 */
import type { Zone } from "./types";
import { ZONES_92 } from "./data-92";
import { ZONES_93 } from "./data-93";
import { ZONES_94 } from "./data-94";
import { ZONES_91 } from "./data-91";
import { ZONES_95 } from "./data-95";
import { ZONES_77 } from "./data-77";
import { ZONES_78 } from "./data-78";

// ─────────────────────────────────────────────────────────────────────────────
// PARIS INTRAMUROS — 20 arrondissements
// ─────────────────────────────────────────────────────────────────────────────
const ZONES_75: Zone[] = [
  {
    slug: "paris-1er",
    dept: "75001",
    name: "Paris 1er",
    fullName: "Paris 1er arrondissement",
    category: "paris",
    landmarks: ["Louvre","Châtelet","Palais Royal","Les Halles","Pont Neuf","Place Vendôme"],
    intro: "Cœur historique et de pouvoir, le 1er arrondissement concentre une densité exceptionnelle de grands tribunaux, d'études notariales multiséculaires et de sièges sociaux de luxe. L'hypercentre parisien bouillonne d'une activité juridique et commerciale qui ne tolère aucun retard.",
    logisticsContext: "Avec la piétonnisation croissante (Halles, Louvre) et les restrictions ZFE, circuler dans le 1er est un défi. Nos coursiers en deux-roues électriques et scooters naviguent sans aucune contrainte entre la rue de Rivoli et l'Île de la Cité, garantissant des remises ultra-rapides.",
    sectors: [
      { name: "Juridique & Notarial", example: "Dépôts urgents de conclusions au Tribunal de Commerce et échanges d'actes authentiques entre les études du Palais Royal.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Plis confidentiels" },
      { name: "E-commerce & Luxe", example: "Livraisons premium en gants blancs pour les boutiques de haute joaillerie de la Place Vendôme et rue Saint-Honoré.", serviceHref: "/services/livraison-e-commerce", serviceLabel: "Livraison luxe" },
      { name: "Corporate & Agences", example: "Navettes confidentielles entre les directions générales et leurs partenaires financiers.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Course dédiée" },
      { name: "Médical & Laboratoires", example: "Acheminement rapide de prélèvements pour les cliniques et cabinets esthétiques du centre.", serviceHref: "/services/transport-medical", serviceLabel: "Transport médical" },
      { name: "Événementiel", example: "Logistique de dernière minute pour les événements professionnels sous la Canopée des Halles.", serviceHref: "/services/transport-evenementiel", serviceLabel: "Transport événementiel" },
      { name: "Grands comptes", example: "Facturation centralisée par dossier pour les cabinets d'avocats et gestionnaires de patrimoine.", serviceHref: "/services/compte-entreprise", serviceLabel: "Compte entreprise" },
    ],
    keyClients: ["Études Notariales","Haute Joaillerie (Vendôme)","Tribunaux (Île de la Cité)","Sièges sociaux"],
    distanceParis: "Hyper-centre",
    pricingZone: "standard",
    seo: { title: "Coursier Paris 1er — Châtelet, Louvre, Vendôme | ONE CONNEXION", description: "Coursier express Paris 1er (75001). Spécialiste des plis juridiques (Tribunal de Commerce) et livraisons luxe (Vendôme). Enlèvement < 45 min.", keywords: ["coursier Paris 1er","coursier Châtelet","coursier Vendôme","livraison express 75001"] },
  },
  {
    slug: "paris-2e",
    dept: "75002",
    name: "Paris 2e",
    fullName: "Paris 2e arrondissement",
    category: "paris",
    landmarks: ["Bourse de Paris","Le Sentier","Opéra-Comique","Passages Couverts","Rue de la Paix"],
    intro: "Le 2e arrondissement mêle la frénésie de la finance autour de la Bourse à l'effervescence créative et textile du Sentier. C'est le carrefour où les start-ups technologiques côtoient les historiques du prêt-à-porter.",
    logisticsContext: "Les rues étroites du Sentier, souvent saturées de camionnettes de livraison, requièrent l'agilité de nos coursiers moto qui assurent des navettes fluides vers le 8e ou le 9e arrondissement en moins de 15 minutes.",
    sectors: [
      { name: "Corporate & Agences", example: "Transfert sécurisé de documents financiers et d'audits pour les acteurs de la Bourse et les fintechs.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Course dédiée" },
      { name: "E-commerce & Luxe", example: "Réassort express et envois de prototypes textiles pour les showrooms du Sentier.", serviceHref: "/services/livraison-e-commerce", serviceLabel: "Livraison mode" },
      { name: "Juridique & Notarial", example: "Signatures de contrats d'affaires et statuts de start-ups.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Plis confidentiels" },
      { name: "Médical & Laboratoires", example: "Livraisons d'ordonnances et d'analyses pour les centres médicaux du quartier Bourse.", serviceHref: "/services/transport-medical", serviceLabel: "Transport médical" },
      { name: "Événementiel", example: "Acheminement de décors et invitations pour les soirées de lancements tech.", serviceHref: "/services/transport-evenementiel", serviceLabel: "Transport événementiel" },
      { name: "Grands comptes", example: "Tournées inter-boutiques pour les enseignes de prêt-à-porter.", serviceHref: "/services/compte-entreprise", serviceLabel: "Compte entreprise" },
    ],
    keyClients: ["Showrooms (Le Sentier)","Start-ups & Fintechs","Cabinets de Conseil (Bourse)","Presse"],
    distanceParis: "Hyper-centre",
    pricingZone: "standard",
    seo: { title: "Coursier Paris 2e — Bourse, Sentier, Start-ups | ONE CONNEXION", description: "Coursier express Paris 2e (75002). Expert en livraison de prototypes (Sentier), plis financiers et navettes start-ups. Enlèvement < 45 min.", keywords: ["coursier Paris 2e","coursier Bourse","coursier Sentier","livraison mode Paris 2"] },
  },
  {
    slug: "paris-3e",
    dept: "75003",
    name: "Paris 3e",
    fullName: "Paris 3e arrondissement",
    category: "paris",
    landmarks: ["Le Marais","Musée Picasso","Square du Temple","Rue de Bretagne"],
    intro: "Le 3e arrondissement (Haut Marais) est l'épicentre parisien du design, des galeries d'art et des marques branchées. Ses ruelles historiques abritent une clientèle exigeante nécessitant un service de livraison irréprochable et discret.",
    logisticsContext: "La circulation dans le Marais est particulièrement contrainte le week-end et en soirée. Nos coursiers utilisent des vélos cargos et scooters électriques pour préserver la quiétude du quartier tout en garantissant des délais records.",
    sectors: [
      { name: "Événementiel", example: "Transport sous haute protection de toiles et sculptures pour les vernissages des galeries du Marais.", serviceHref: "/services/transport-evenementiel", serviceLabel: "Transport d'art" },
      { name: "E-commerce & Luxe", example: "Livraison premium (white-glove) de pièces de créateurs pour une clientèle VIP locale.", serviceHref: "/services/livraison-e-commerce", serviceLabel: "Livraison luxe" },
      { name: "Corporate & Agences", example: "Navettes de maquettes de design et press kits pour les agences de communication.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Course dédiée" },
      { name: "Juridique & Notarial", example: "Échanges d'actes pour les cabinets d'avocats spécialisés en propriété intellectuelle.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Plis confidentiels" },
      { name: "Médical & Laboratoires", example: "Liaisons urgentes entre pharmacies de quartier et laboratoires d'analyses.", serviceHref: "/services/transport-medical", serviceLabel: "Transport médical" },
      { name: "Grands comptes", example: "Accompagnement logistique lors des Fashion Weeks (Paris Fashion Week).", serviceHref: "/services/compte-entreprise", serviceLabel: "Fashion Week" },
    ],
    keyClients: ["Galeries d'art contemporain","Boutiques de créateurs","Agences de relations presse","Designers"],
    distanceParis: "Hyper-centre",
    pricingZone: "standard",
    seo: { title: "Coursier Paris 3e — Le Marais, Galeries d'Art | ONE CONNEXION", description: "Coursier express Paris 3e (75003). Spécialiste du transport d'art, livraisons VIP pour les boutiques du Marais et agences RP. Discrétion et sécurité.", keywords: ["coursier Paris 3e","coursier Le Marais","transport art Paris 3","coursier luxe 75003"] },
  },
  {
    slug: "paris-4e",
    dept: "75004",
    name: "Paris 4e",
    fullName: "Paris 4e arrondissement",
    category: "paris",
    landmarks: ["Notre-Dame","Hôtel de Ville","Centre Pompidou","Île Saint-Louis","Place des Vosges"],
    intro: "De l'Hôtel de Ville au Centre Pompidou, le 4e arrondissement est le cœur touristique et administratif de la capitale. Il abrite les instances municipales majeures ainsi qu'un tissu très dense de commerces et d'institutions culturelles.",
    logisticsContext: "Desservir l'Hôtel de Ville ou l'Île Saint-Louis nécessite une parfaite maîtrise des accès restreints et piétons. Nos coursiers accrédités assurent des dépôts officiels sans friction.",
    sectors: [
      { name: "Juridique & Notarial", example: "Dépôt de dossiers administratifs et appels d'offres à l'Hôtel de Ville.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Course dédiée" },
      { name: "Corporate & Agences", example: "Navettes de documents institutionnels avec les services de la mairie de Paris.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Plis confidentiels" },
      { name: "Événementiel", example: "Acheminement de scénographies pour les expositions du Centre Pompidou.", serviceHref: "/services/transport-evenementiel", serviceLabel: "Transport d'art" },
      { name: "E-commerce & Luxe", example: "Distribution pour les boutiques de souvenirs et de mode du quartier Beaubourg.", serviceHref: "/services/livraison-e-commerce", serviceLabel: "Livraison express" },
      { name: "Médical & Laboratoires", example: "Transport d'urgence pour l'Hôtel-Dieu (Île de la Cité).", serviceHref: "/services/transport-medical", serviceLabel: "Transport médical" },
      { name: "Grands comptes", example: "Prestations régulières pour les institutions publiques et muséales.", serviceHref: "/services/compte-entreprise", serviceLabel: "Compte entreprise" },
    ],
    keyClients: ["Mairie de Paris","Institutions Culturelles","Commerces Beaubourg","Cabinets institutionnels"],
    distanceParis: "Hyper-centre",
    pricingZone: "standard",
    seo: { title: "Coursier Paris 4e — Hôtel de Ville, Beaubourg | ONE CONNEXION", description: "Coursier express Paris 4e (75004). Appels d'offres Hôtel de Ville, plis institutionnels, transport pour galeries d'art (Beaubourg, Marais).", keywords: ["coursier Paris 4e","coursier Hôtel de Ville","coursier Beaubourg","livraison express 75004"] },
  },
  {
    slug: "paris-5e",
    dept: "75005",
    name: "Paris 5e",
    fullName: "Paris 5e arrondissement",
    category: "paris",
    landmarks: ["Panthéon","Sorbonne","Jardin des Plantes","Quartier Latin","Institut Curie"],
    intro: "Berceau universitaire et intellectuel, le 5e arrondissement abrite les plus prestigieuses universités (Sorbonne, Jussieu) et des centres de recherche de pointe (Institut Curie). C'est un véritable hub pour les secteurs scientifiques, médicaux et de l'édition.",
    logisticsContext: "L'ascension de la montagne Sainte-Geneviève et le dédale du Quartier Latin sont le terrain de jeu privilégié de notre flotte deux-roues, capable de relier les laboratoires aux hôpitaux parisiens à une vitesse inégalée.",
    sectors: [
      { name: "Médical & Laboratoires", example: "Transports urgents et sécurisés (ADR) de prélèvements et greffons pour l'Institut Curie.", serviceHref: "/services/transport-medical", serviceLabel: "Transport médical" },
      { name: "Corporate & Agences", example: "Transferts de manuscrits et épreuves pour les grandes maisons d'édition du Quartier Latin.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Course dédiée" },
      { name: "Juridique & Notarial", example: "Acheminement de documents académiques et diplômes certifiés.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Plis confidentiels" },
      { name: "Événementiel", example: "Livraisons de matériel pour les colloques et soutenances de thèse universitaires.", serviceHref: "/services/transport-evenementiel", serviceLabel: "Transport événementiel" },
      { name: "E-commerce & Luxe", example: "Approvisionnement des librairies indépendantes en ouvrages rares.", serviceHref: "/services/livraison-e-commerce", serviceLabel: "Livraison sur-mesure" },
      { name: "Grands comptes", example: "Partenariats de longue durée avec les pôles de recherche publique.", serviceHref: "/services/compte-entreprise", serviceLabel: "Compte entreprise" },
    ],
    keyClients: ["Instituts de Recherche (Curie)","Universités (Sorbonne)","Maisons d'édition","Librairies"],
    distanceParis: "Rive Gauche",
    pricingZone: "standard",
    seo: { title: "Coursier Paris 5e — Quartier Latin, Institut Curie | ONE CONNEXION", description: "Coursier express Paris 5e (75005). Spécialiste du transport médical urgent (Curie) et liaisons pour les universités et l'édition. Enlèvement < 45 min.", keywords: ["coursier Paris 5e","coursier Quartier Latin","coursier médical Paris 5","coursier Sorbonne"] },
  },
  {
    slug: "paris-6e",
    dept: "75006",
    name: "Paris 6e",
    fullName: "Paris 6e arrondissement",
    category: "paris",
    landmarks: ["Saint-Germain-des-Prés","Sénat (Jardin du Luxembourg)","Odéon","Institut de France"],
    intro: "Symbole de l'élégance parisienne, le 6e arrondissement abrite le Sénat, l'Institut de France, des cabinets d'avocats de renom et de luxueuses boutiques. C'est un quartier où la discrétion et la présentation du coursier priment.",
    logisticsContext: "Livrer aux abords du Sénat ou dans les ruelles étroites de Saint-Germain-des-Prés requiert un tact particulier. Nos coursiers premium garantissent une remise en main propre en costume avec une absolue confidentialité.",
    sectors: [
      { name: "Juridique & Notarial", example: "Transmission de plis ultra-confidentiels pour les sénateurs et cabinets d'avocats de prestige.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Plis confidentiels" },
      { name: "E-commerce & Luxe", example: "Livraison de cadeaux d'affaires, parfums et haute maroquinerie pour la clientèle VIP.", serviceHref: "/services/livraison-e-commerce", serviceLabel: "Livraison luxe" },
      { name: "Corporate & Agences", example: "Navettes de dossiers stratégiques pour les banques d'affaires et fonds d'investissement.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Course dédiée" },
      { name: "Événementiel", example: "Installation de vernissages pour les galeries d'art de la rue de Seine.", serviceHref: "/services/transport-evenementiel", serviceLabel: "Transport d'art" },
      { name: "Médical & Laboratoires", example: "Livraisons discrètes pour les cliniques esthétiques privées.", serviceHref: "/services/transport-medical", serviceLabel: "Transport médical" },
      { name: "Grands comptes", example: "Service conciergerie d'entreprise exclusif pour les gestionnaires de fortune.", serviceHref: "/services/compte-entreprise", serviceLabel: "Compte entreprise" },
    ],
    keyClients: ["Institutions (Sénat)","Cabinets d'avocats prestigieux","Galeries d'art","Marques de luxe"],
    distanceParis: "Rive Gauche",
    pricingZone: "standard",
    seo: { title: "Coursier Paris 6e — Saint-Germain, Sénat, Luxe | ONE CONNEXION", description: "Coursier express Paris 6e (75006). Livraison premium, plis ultra-confidentiels (Sénat, Avocats) et transport d'œuvres d'art. Discrétion absolue.", keywords: ["coursier Paris 6e","coursier Saint-Germain-des-Prés","coursier Sénat","coursier luxe 75006"] },
  },
  {
    slug: "paris-7e",
    dept: "75007",
    name: "Paris 7e",
    fullName: "Paris 7e arrondissement",
    category: "paris",
    landmarks: ["Tour Eiffel","Invalides","Assemblée Nationale","Quai d'Orsay","Rue du Bac"],
    intro: "Cœur politique et diplomatique de la France, le 7e arrondissement regroupe les ministères, l'Assemblée Nationale et une multitude d'ambassades. La sécurité et la fiabilité des transports y sont des exigences non négociables.",
    logisticsContext: "La forte sécurisation autour des ministères et ambassades impose des contrôles d'identité stricts. Nos coursiers habilités disposent de l'expérience requise pour franchir ces barrières institutionnelles sans perte de temps.",
    sectors: [
      { name: "Juridique & Notarial", example: "Dépôts officiels de dossiers et visas auprès des ministères (Quai d'Orsay) et ambassades.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Course dédiée" },
      { name: "Corporate & Agences", example: "Échanges de documents classifiés pour les directions de grandes instances publiques.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Plis confidentiels" },
      { name: "E-commerce & Luxe", example: "Acheminement de produits de luxe et épicerie fine pour les résidents des Invalides.", serviceHref: "/services/livraison-e-commerce", serviceLabel: "Livraison premium" },
      { name: "Médical & Laboratoires", example: "Transports urgents de matériel de santé pour les hôpitaux militaires (Invalides).", serviceHref: "/services/transport-medical", serviceLabel: "Transport médical" },
      { name: "Événementiel", example: "Navettes pour les réceptions diplomatiques et événements ministériels.", serviceHref: "/services/transport-evenementiel", serviceLabel: "Transport événementiel" },
      { name: "Grands comptes", example: "Partenariats logistiques sous accord de confidentialité (NDA) avec les institutions.", serviceHref: "/services/compte-entreprise", serviceLabel: "Compte institutionnel" },
    ],
    keyClients: ["Ministères","Ambassades","Assemblée Nationale","Family Offices"],
    distanceParis: "Rive Gauche",
    pricingZone: "standard",
    seo: { title: "Coursier Paris 7e — Invalides, Ministères, Ambassades | ONE CONNEXION", description: "Coursier express Paris 7e (75007). Habilités aux accès ministères et ambassades. Plis diplomatiques et confidentiels remis en main propre.", keywords: ["coursier Paris 7e","coursier ambassade Paris","coursier Invalides","livraison express 75007"] },
  },
  {
    slug: "paris-8e",
    dept: "75008",
    name: "Paris 8e",
    fullName: "Paris 8e arrondissement",
    category: "paris",
    landmarks: ["Champs-Élysées","Triangle d'Or","Élysée","Place de la Concorde","Gare Saint-Lazare"],
    intro: "Le 8e arrondissement est la vitrine économique et de prestige de Paris. Des Champs-Élysées au Triangle d'Or, il concentre les sièges du CAC40, la haute finance, les palaces et les sièges des plus grandes marques mondiales.",
    logisticsContext: "L'intensité du trafic autour de l'Étoile et d'Haussmann exige une logistique hyper-réactive. Nous y opérons nos plus grands volumes de plis urgents avec une garantie de prise en charge en quelques minutes.",
    sectors: [
      { name: "Corporate & Agences", example: "Liaisons entre directions générales, fonds d'investissement et banques d'affaires d'Haussmann.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Plis confidentiels" },
      { name: "Juridique & Notarial", example: "Transmissions de contrats de fusion/acquisition pour les cabinets d'avocats internationaux.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Course dédiée" },
      { name: "E-commerce & Luxe", example: "Acheminement direct depuis les ateliers vers les boutiques de l'Avenue Montaigne.", serviceHref: "/services/livraison-e-commerce", serviceLabel: "Livraison luxe" },
      { name: "Médical & Laboratoires", example: "Tournées pour les cliniques de médecine esthétique réputées du Triangle d'Or.", serviceHref: "/services/transport-medical", serviceLabel: "Transport médical" },
      { name: "Événementiel", example: "Logistique VIP pour les défilés de mode et inaugurations sur les Champs-Élysées.", serviceHref: "/services/transport-evenementiel", serviceLabel: "VIP & Fashion" },
      { name: "Grands comptes", example: "Service courrier internalisé et facturation multi-services pour les groupes du CAC40.", serviceHref: "/services/compte-entreprise", serviceLabel: "Compte entreprise" },
    ],
    keyClients: ["Sièges CAC40","Banques d'Affaires","Cabinets Internationaux","Maisons de Haute Couture"],
    distanceParis: "Hyper-centre",
    pricingZone: "standard",
    seo: { title: "Coursier Paris 8e — Champs-Élysées, Triangle d'Or | ONE CONNEXION", description: "Coursier express Paris 8e (75008). Spécialiste finance, luxe et grands comptes. Enlèvement < 45 min sur les Champs-Élysées et Haussmann.", keywords: ["coursier Paris 8e","coursier Champs-Élysées","coursier Triangle d'Or","livraison express 75008"] },
  },
  {
    slug: "paris-9e",
    dept: "75009",
    name: "Paris 9e",
    fullName: "Paris 9e arrondissement",
    category: "paris",
    landmarks: ["Opéra Garnier","Grands Boulevards","Galeries Lafayette","Quartier Saint-Georges"],
    intro: "Symbole de la vie culturelle et du grand commerce parisien, le 9e abrite les Grands Magasins, l'Opéra et une concentration exceptionnelle de start-ups et d'entreprises du digital (la \"Silicon Sentier\" étendue).",
    logisticsContext: "Le secteur des Grands Boulevards est un nœud de circulation majeur. Notre flotte s'adapte en temps réel, garantissant des livraisons de colis de matériel IT comme de plis ultra-rapides vers le reste de la capitale.",
    sectors: [
      { name: "Corporate & Agences", example: "Navettes de matériel informatique et contrats pour les scale-ups et entreprises technologiques.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Course dédiée" },
      { name: "E-commerce & Luxe", example: "Retours express et transferts de stocks pour les Galeries Lafayette et Printemps.", serviceHref: "/services/livraison-e-commerce", serviceLabel: "Logistique Retail" },
      { name: "Événementiel", example: "Transport de costumes et décors pour les théâtres et salles de spectacle de l'Opéra.", serviceHref: "/services/transport-evenementiel", serviceLabel: "Transport événementiel" },
      { name: "Juridique & Notarial", example: "Acheminement de dossiers pour les cabinets de recrutement et d'audit.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Plis confidentiels" },
      { name: "Médical & Laboratoires", example: "Livraisons quotidiennes pour les laboratoires d'analyses de la Chaussée d'Antin.", serviceHref: "/services/transport-medical", serviceLabel: "Transport médical" },
      { name: "Grands comptes", example: "Gestion externalisée des courriers pour les incubateurs et espaces de coworking.", serviceHref: "/services/compte-entreprise", serviceLabel: "Compte entreprise" },
    ],
    keyClients: ["Start-ups & Scale-ups","Grands Magasins","Théâtres & Opéra","Sièges d'assurances"],
    distanceParis: "Hyper-centre",
    pricingZone: "standard",
    seo: { title: "Coursier Paris 9e — Opéra, Grands Boulevards, Start-ups | ONE CONNEXION", description: "Coursier express Paris 9e (75009). Spécialiste tech, start-ups et retail (Grands Magasins). Livraison informatique et plis urgents < 45 min.", keywords: ["coursier Paris 9e","coursier Opéra","coursier Grands Boulevards","livraison express 75009"] },
  },
  {
    slug: "paris-10e",
    dept: "75010",
    name: "Paris 10e",
    fullName: "Paris 10e arrondissement",
    category: "paris",
    landmarks: ["Gare du Nord","Gare de l'Est","Canal Saint-Martin","Hôpital Saint-Louis","Place de la République"],
    intro: "Le 10e arrondissement est le cœur logistique ferroviaire de l'Europe avec ses deux gares majeures. Il connaît un fort dynamisme avec l'implantation d'agences de pub, de labels de musique et d'hôpitaux prestigieux comme Saint-Louis.",
    logisticsContext: "La jonction entre les gares génère un trafic dense. Nos coursiers réalisent des exploits pour rattraper des départs de train (colis express en gare) ou assurer des urgences vitales vers l'hôpital Saint-Louis.",
    sectors: [
      { name: "Médical & Laboratoires", example: "Transports de sang et d'analyses dermatologiques d'urgence pour l'Hôpital Saint-Louis.", serviceHref: "/services/transport-medical", serviceLabel: "Transport médical" },
      { name: "Corporate & Agences", example: "Livraison de maquettes et disques durs pour les studios de post-production du canal.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Course dédiée" },
      { name: "Événementiel", example: "Navettes urgentes de bagages ou colis oubliés vers les trains Eurostar / Thalys.", serviceHref: "/services/transport-evenementiel", serviceLabel: "Colis express" },
      { name: "Juridique & Notarial", example: "Dépôts urgents auprès des tribunaux pour les cabinets situés près de République.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Plis confidentiels" },
      { name: "E-commerce & Luxe", example: "Livraisons du dernier kilomètre pour les concept stores du Canal Saint-Martin.", serviceHref: "/services/livraison-e-commerce", serviceLabel: "Livraison e-commerce" },
      { name: "Grands comptes", example: "Logistique programmée pour les réseaux de presse des gares.", serviceHref: "/services/compte-entreprise", serviceLabel: "Compte entreprise" },
    ],
    keyClients: ["Hôpital Saint-Louis","Agences créatives","Studios de production","Logistique gares"],
    distanceParis: "Nord",
    pricingZone: "standard",
    seo: { title: "Coursier Paris 10e — Gares, Canal Saint-Martin, Hôpital | ONE CONNEXION", description: "Coursier express Paris 10e (75010). Urgences médicales (Hôpital Saint-Louis), liaisons Gare du Nord/Est et navettes pour les agences du Canal.", keywords: ["coursier Paris 10e","coursier Gare du Nord","coursier hôpital Saint-Louis","livraison express 75010"] },
  },
  {
    slug: "paris-11e",
    dept: "75011",
    name: "Paris 11e",
    fullName: "Paris 11e arrondissement",
    category: "paris",
    landmarks: ["Bastille","Oberkampf","Nation","Place de la République","Atelier des Lumières"],
    intro: "Le 11e est l'arrondissement le plus densément peuplé, célèbre pour son esprit festif et entrepreneurial. Il héberge d'innombrables start-ups, artisans, designers et espaces de coworking qui nécessitent une logistique hyper-flexible.",
    logisticsContext: "Parfaitement desservi par les boulevards extérieurs, le 11e permet à nos coursiers d'effectuer des sauts de puce très rapides d'Oberkampf à Bastille, tout en naviguant dans un maillage de rues étroites.",
    sectors: [
      { name: "Corporate & Agences", example: "Liaisons B2B entre les start-ups d'Oberkampf et les pépinières d'entreprises.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Course dédiée" },
      { name: "E-commerce & Luxe", example: "Distribution same-day de commandes pour les créateurs de mode et artisans locaux.", serviceHref: "/services/livraison-e-commerce", serviceLabel: "Livraison express" },
      { name: "Juridique & Notarial", example: "Signature de baux commerciaux et contrats de travail pour les nouvelles enseignes.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Plis confidentiels" },
      { name: "Médical & Laboratoires", example: "Transferts vers les grands hôpitaux de l'Est (Saint-Antoine, Tenon).", serviceHref: "/services/transport-medical", serviceLabel: "Transport médical" },
      { name: "Événementiel", example: "Livraison de catering et matériel pour les salles de concert (Bataclan) et ateliers.", serviceHref: "/services/transport-evenementiel", serviceLabel: "Transport événementiel" },
      { name: "Grands comptes", example: "Groupage de plis pour les grands espaces de coworking.", serviceHref: "/services/compte-entreprise", serviceLabel: "Compte entreprise" },
    ],
    keyClients: ["Espaces de Coworking","Start-ups","Artisans & Créateurs","Salles de concert"],
    distanceParis: "Est",
    pricingZone: "standard",
    seo: { title: "Coursier Paris 11e — Bastille, Oberkampf, Nation | ONE CONNEXION", description: "Coursier express Paris 11e (75011). Partenaire des start-ups, espaces de coworking et artisans de Bastille à Nation. Enlèvement < 45 min.", keywords: ["coursier Paris 11e","coursier Bastille","coursier Oberkampf","livraison express 75011"] },
  },
  {
    slug: "paris-12e",
    dept: "75012",
    name: "Paris 12e",
    fullName: "Paris 12e arrondissement",
    category: "paris",
    landmarks: ["Gare de Lyon","Ministère de l'Économie (Bercy)","Accor Arena","Bois de Vincennes","Hôpital Saint-Antoine"],
    intro: "Entre la Gare de Lyon, le pôle d'affaires de Bercy (Ministère des Finances) et l'immensité du Bois de Vincennes, le 12e arrondissement est une zone contrastée aux besoins logistiques intenses, mêlant fret ferroviaire et urgences ministérielles.",
    logisticsContext: "La proximité de l'A4 et du boulevard périphérique fait du 12e un tremplin stratégique vers l'Est francilien. Nos coursiers assurent des jonctions immédiates entre les trains TGV de la Gare de Lyon et Bercy.",
    sectors: [
      { name: "Juridique & Notarial", example: "Dépôt de dossiers d'appels d'offres au Ministère de l'Économie et des Finances.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Plis officiels" },
      { name: "Corporate & Agences", example: "Transferts de dossiers comptables pour les cabinets de la Tour de l'Horloge.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Course dédiée" },
      { name: "Médical & Laboratoires", example: "Urgences sanguines et biologiques pour l'Hôpital Trousseau et Saint-Antoine.", serviceHref: "/services/transport-medical", serviceLabel: "Transport médical" },
      { name: "Événementiel", example: "Logistique technique lourde pour les concerts de l'Accor Arena.", serviceHref: "/services/transport-evenementiel", serviceLabel: "Fret léger" },
      { name: "E-commerce & Luxe", example: "Récupération de colis fret à la Gare de Lyon pour livraison du dernier kilomètre.", serviceHref: "/services/livraison-e-commerce", serviceLabel: "Logistique dernier km" },
      { name: "Grands comptes", example: "Contrats de gestion de courrier pour les directions ministérielles.", serviceHref: "/services/compte-entreprise", serviceLabel: "Compte institutionnel" },
    ],
    keyClients: ["Ministère de l'Économie","Hôpitaux (Saint-Antoine, Trousseau)","Accor Arena","Cabinets d'audit"],
    distanceParis: "Est",
    pricingZone: "standard",
    seo: { title: "Coursier Paris 12e — Bercy, Gare de Lyon, Hôpitaux | ONE CONNEXION", description: "Coursier express Paris 12e (75012). Plis officiels (Bercy), urgences médicales (Saint-Antoine) et relais Gare de Lyon. Enlèvement < 45 min.", keywords: ["coursier Paris 12e","coursier Bercy","coursier Gare de Lyon","livraison express 75012"] },
  },
  {
    slug: "paris-13e",
    dept: "75013",
    name: "Paris 13e",
    fullName: "Paris 13e arrondissement",
    category: "paris",
    landmarks: ["Station F","Hôpital Pitié-Salpêtrière","Place d'Italie","Bibliothèque François-Mitterrand (BnF)"],
    intro: "Le 13e arrondissement s'est imposé comme le centre névralgique de la Tech française avec Station F. C'est également un immense pôle de santé abritant la Pitié-Salpêtrière, le plus grand hôpital d'Europe.",
    logisticsContext: "L'avenue de France et les quais de Seine offrent des axes de circulation rapides. Nos coursiers jonglent entre le matériel informatique pointu des start-ups et les transports vitaux sous température dirigée de l'hôpital.",
    sectors: [
      { name: "Médical & Laboratoires", example: "Transport d'organes, sang et essais cliniques (ADR) pour la Pitié-Salpêtrière.", serviceHref: "/services/transport-medical", serviceLabel: "Transport médical" },
      { name: "Corporate & Agences", example: "Livraison urgente d'ordinateurs et prototypes technologiques pour les licornes de Station F.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Course dédiée" },
      { name: "Juridique & Notarial", example: "Signatures de levées de fonds et pactes d'actionnaires pour les start-ups.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Plis confidentiels" },
      { name: "Événementiel", example: "Approvisionnement pour les grandes expositions de la BnF et du quartier Paris Rive Gauche.", serviceHref: "/services/transport-evenementiel", serviceLabel: "Transport événementiel" },
      { name: "E-commerce & Luxe", example: "Livraison B2B pour le tissu commercial florissant de la Place d'Italie.", serviceHref: "/services/livraison-e-commerce", serviceLabel: "Livraison e-commerce" },
      { name: "Grands comptes", example: "Externalisation logistique complète pour les campus incubateurs.", serviceHref: "/services/compte-entreprise", serviceLabel: "Compte entreprise" },
    ],
    keyClients: ["Hôpital Pitié-Salpêtrière","Start-ups (Station F)","Institutions (BnF)","Sièges bancaires"],
    distanceParis: "Sud",
    pricingZone: "standard",
    seo: { title: "Coursier Paris 13e — Station F, Pitié-Salpêtrière | ONE CONNEXION", description: "Coursier express Paris 13e (75013). Expert en logistique médicale (Pitié-Salpêtrière) et transports urgents IT pour les start-ups (Station F).", keywords: ["coursier Paris 13e","coursier Station F","coursier hôpital Pitié-Salpêtrière","livraison express 75013"] },
  },
  {
    slug: "paris-14e",
    dept: "75014",
    name: "Paris 14e",
    fullName: "Paris 14e arrondissement",
    category: "paris",
    landmarks: ["Gare Montparnasse","Tour Montparnasse","Hôpital Cochin","Observatoire","Catacombes"],
    intro: "Historiquement intellectuel, le 14e est aujourd'hui porté par le gigantesque pôle d'affaires de Montparnasse et de nombreux centres hospitaliers d'excellence (Cochin, Montsouris, Sainte-Anne).",
    logisticsContext: "Desservant le Grand Ouest de la France, la Gare Montparnasse est une véritable usine à colis. Nos coursiers maîtrisent parfaitement les accès de la Tour et des gares pour assurer des jonctions en temps réel.",
    sectors: [
      { name: "Médical & Laboratoires", example: "Liaisons quotidiennes de prélèvements entre l'Hôpital Cochin et l'Institut Pasteur voisin.", serviceHref: "/services/transport-medical", serviceLabel: "Transport médical" },
      { name: "Corporate & Agences", example: "Échanges de documents confidentiels entre les étages de la Tour Montparnasse.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Course dédiée" },
      { name: "Événementiel", example: "Rapatriement de plis oubliés directement sur les quais des TGV en partance.", serviceHref: "/services/transport-evenementiel", serviceLabel: "Colis express" },
      { name: "Juridique & Notarial", example: "Transmission de contrats pour les sièges d'assurances et mutuelles du quartier.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Plis confidentiels" },
      { name: "E-commerce & Luxe", example: "Desserte des commerces de la rue Daguerre et des Alésia.", serviceHref: "/services/livraison-e-commerce", serviceLabel: "Livraison e-commerce" },
      { name: "Grands comptes", example: "Tournées multi-sites pour les acteurs de la santé du sud parisien.", serviceHref: "/services/compte-entreprise", serviceLabel: "Compte entreprise" },
    ],
    keyClients: ["Tour Montparnasse","Gare Montparnasse","Hôpital Cochin","Sièges d'assurances"],
    distanceParis: "Sud",
    pricingZone: "standard",
    seo: { title: "Coursier Paris 14e — Montparnasse, Hôpital Cochin | ONE CONNEXION", description: "Coursier express Paris 14e (75014). Livraisons urgentes Tour Montparnasse, urgences médicales (Cochin) et liaisons TGV. Enlèvement < 45 min.", keywords: ["coursier Paris 14e","coursier Montparnasse","coursier Cochin","livraison express 75014"] },
  },
  {
    slug: "paris-15e",
    dept: "75015",
    name: "Paris 15e",
    fullName: "Paris 15e arrondissement",
    category: "paris",
    landmarks: ["Hôpital Européen Georges-Pompidou (HEGP)","Parc des Expositions (Porte de Versailles)","Beaugrenelle","Tour Montparnasse (limite)"],
    intro: "Le plus peuplé des arrondissements est un géant économique. Il accueille les sièges de médias audiovisuels prestigieux, le Parc des Expositions de la Porte de Versailles et un grand pôle de santé publique.",
    logisticsContext: "La diversité des activités (salons pros, télévision, santé) fait du 15e une zone nécessitant une grande adaptabilité, des camions avec hayon pour VIParis aux deux-roues pressés pour les JT.",
    sectors: [
      { name: "Événementiel", example: "Transport de stands, PLV et matériels pour les congrès mondiaux à la Porte de Versailles.", serviceHref: "/services/transport-evenementiel", serviceLabel: "Transport fret" },
      { name: "Corporate & Agences", example: "Acheminement de rushs vidéo et supports de communication pour les chaînes de télévision.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Course dédiée" },
      { name: "Médical & Laboratoires", example: "Prise en charge d'analyses et de sang pour l'HEGP et l'Hôpital Necker.", serviceHref: "/services/transport-medical", serviceLabel: "Transport médical" },
      { name: "Juridique & Notarial", example: "Navettes administratives pour les grandes tours de bureaux du Front de Seine.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Plis confidentiels" },
      { name: "E-commerce & Luxe", example: "Livraisons en main propre aux résidents du quartier Beaugrenelle.", serviceHref: "/services/livraison-e-commerce", serviceLabel: "Livraison premium" },
      { name: "Grands comptes", example: "Assistance logistique dédiée pour les organisateurs de salons professionnels.", serviceHref: "/services/compte-entreprise", serviceLabel: "Compte entreprise" },
    ],
    keyClients: ["Parc des Expositions","Hôpitaux (HEGP, Necker)","Chaînes de Télévision","Grands sièges sociaux"],
    distanceParis: "Ouest",
    pricingZone: "standard",
    seo: { title: "Coursier Paris 15e — Porte de Versailles, HEGP, Médias | ONE CONNEXION", description: "Coursier express Paris 15e (75015). Spécialiste logistique salons (Porte de Versailles), transport audiovisuel et médical (HEGP).", keywords: ["coursier Paris 15e","coursier Porte de Versailles","coursier audiovisuel Paris","livraison express 75015"] },
  },
  {
    slug: "paris-16e",
    dept: "75016",
    name: "Paris 16e",
    fullName: "Paris 16e arrondissement",
    category: "paris",
    landmarks: ["Trocadéro","Bois de Boulogne","Stade Roland-Garros","Parc des Princes","Avenue Foch"],
    intro: "Résidentiel et haut de gamme, le 16e arrondissement est l'adresse des ambassades, des grandes fortunes, mais aussi de hauts lieux sportifs internationaux (Roland-Garros, Parc des Princes).",
    logisticsContext: "L'exigence est le maître mot. Qu'il s'agisse d'un pli diplomatique très sensible ou d'un colis de luxe pour un résident, la ponctualité absolue et la discrétion de nos coursiers sont testées chaque jour.",
    sectors: [
      { name: "Juridique & Notarial", example: "Acheminement sécurisé de documents pour les ambassades et consulats étrangers.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Plis confidentiels" },
      { name: "E-commerce & Luxe", example: "Service conciergerie et livraison VIP de haute couture pour les résidents privés.", serviceHref: "/services/livraison-e-commerce", serviceLabel: "Livraison luxe" },
      { name: "Événementiel", example: "Logistique d'accréditations et VIP pour les grands tournois sportifs et soirées de gala.", serviceHref: "/services/transport-evenementiel", serviceLabel: "Transport événementiel" },
      { name: "Corporate & Agences", example: "Transport d'actes pour les gestionnaires de grands patrimoines et family offices.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Course dédiée" },
      { name: "Médical & Laboratoires", example: "Navettes urgentes entre les cliniques privées très exclusives du quartier.", serviceHref: "/services/transport-medical", serviceLabel: "Transport médical" },
      { name: "Grands comptes", example: "Partenariats de confiance (NDA) pour les grandes institutions internationales.", serviceHref: "/services/compte-entreprise", serviceLabel: "Compte institutionnel" },
    ],
    keyClients: ["Ambassades","Family Offices","Organisateurs sportifs (Roland Garros)","Cliniques privées"],
    distanceParis: "Ouest",
    pricingZone: "standard",
    seo: { title: "Coursier Paris 16e — Ambassades, Luxe, Événementiel | ONE CONNEXION", description: "Coursier express Paris 16e (75016). Livraison VIP discrète, plis diplomatiques, navettes ambassades et logistique d'événements sportifs.", keywords: ["coursier Paris 16e","coursier ambassade Paris","coursier VIP Paris","livraison express 75016"] },
  },
  {
    slug: "paris-17e",
    dept: "75017",
    name: "Paris 17e",
    fullName: "Paris 17e arrondissement",
    category: "paris",
    landmarks: ["Nouveau Palais de Justice (Tribunal de Paris)","Batignolles","Parc Monceau","Porte Maillot","Place des Ternes"],
    intro: "Avec l'ouverture du Tribunal de Paris aux Batignolles, le 17e est devenu le centre névralgique de la justice en France. Il abrite également de nombreux sièges sociaux vers Wagram et des cabinets d'avocats fraîchement implantés.",
    logisticsContext: "La navette Palais de Justice est notre spécialité locale. Nos coursiers accrédités déposent quotidiennement des centaines de conclusions et tocs en contournant les embouteillages de la Porte de Clichy.",
    sectors: [
      { name: "Juridique & Notarial", example: "Dépôts massifs et urgents d'actes au Tribunal Judiciaire de Paris pour les avocats de tout l'hexagone.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Spécial Avocats" },
      { name: "Corporate & Agences", example: "Liaisons régulières pour les directions générales installées autour de la Place de l'Étoile et Ternes.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Plis confidentiels" },
      { name: "Médical & Laboratoires", example: "Desserte des laboratoires et cliniques du quartier Monceau.", serviceHref: "/services/transport-medical", serviceLabel: "Transport médical" },
      { name: "Événementiel", example: "Approvisionnement du Palais des Congrès de la Porte Maillot.", serviceHref: "/services/transport-evenementiel", serviceLabel: "Transport événementiel" },
      { name: "E-commerce & Luxe", example: "Livraisons express pour les commerçants du quartier des Ternes.", serviceHref: "/services/livraison-e-commerce", serviceLabel: "Livraison e-commerce" },
      { name: "Grands comptes", example: "Facturation centralisée par dossier pour les gros cabinets d'avocats d'affaires.", serviceHref: "/services/compte-entreprise", serviceLabel: "Compte entreprise" },
    ],
    keyClients: ["Tribunal de Paris (Palais de Justice)","Cabinets d'Avocats","Palais des Congrès","Sièges sociaux"],
    distanceParis: "Ouest",
    pricingZone: "standard",
    seo: { title: "Coursier Paris 17e — Tribunal de Paris, Batignolles | ONE CONNEXION", description: "Coursier express Paris 17e (75017). Expert des dépôts juridiques au Tribunal de Paris (Batignolles). Enlèvement immédiat, course dédiée spécialisée.", keywords: ["coursier Paris 17e","coursier Tribunal de Paris","coursier avocat Paris","livraison express 75017"] },
  },
  {
    slug: "paris-18e",
    dept: "75018",
    name: "Paris 18e",
    fullName: "Paris 18e arrondissement",
    category: "paris",
    landmarks: ["Montmartre","Sacré-Cœur","Hôpital Bichat","La Chapelle","Pigalle"],
    intro: "Mondialement célèbre pour Montmartre, le 18e est aussi un arrondissement populaire en pleine mutation. Il accueille des pôles de santé majeurs comme l'Hôpital Bichat, fleuron des maladies infectieuses, et un écosystème artistique foisonnant.",
    logisticsContext: "Grimper la butte Montmartre ou naviguer dans le trafic dense de la Porte de la Chapelle est le quotidien de nos pilotes. Nos motos se faufilent là où les camionnettes restent bloquées.",
    sectors: [
      { name: "Médical & Laboratoires", example: "Urgences vitales, biologie et infectiologie pour l'Hôpital Bichat-Claude-Bernard.", serviceHref: "/services/transport-medical", serviceLabel: "Transport médical" },
      { name: "Événementiel", example: "Livraison de décors et matériel technique pour les théâtres, cabarets et salles de Pigalle.", serviceHref: "/services/transport-evenementiel", serviceLabel: "Transport événementiel" },
      { name: "Corporate & Agences", example: "Transferts de dossiers pour les agences de production et studios d'enregistrement.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Course dédiée" },
      { name: "E-commerce & Luxe", example: "Logistique du dernier kilomètre pour les galeries d'art et artisans créateurs de la Butte.", serviceHref: "/services/livraison-e-commerce", serviceLabel: "Livraison express" },
      { name: "Juridique & Notarial", example: "Échanges d'actes pour les cabinets d'architectes et études du nord de Paris.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Plis confidentiels" },
      { name: "Grands comptes", example: "Navettes régulières pour les grandes institutions hospitalières.", serviceHref: "/services/compte-entreprise", serviceLabel: "Compte entreprise" },
    ],
    keyClients: ["Hôpital Bichat","Salles de spectacles (Pigalle)","Artisans (Montmartre)","Studios de production"],
    distanceParis: "Nord",
    pricingZone: "standard",
    seo: { title: "Coursier Paris 18e — Montmartre, Hôpital Bichat, Pigalle | ONE CONNEXION", description: "Coursier express Paris 18e (75018). Spécialiste logistique pour l'Hôpital Bichat, livraisons événementielles pour les salles de spectacles et théâtres.", keywords: ["coursier Paris 18e","coursier Montmartre","coursier Hôpital Bichat","livraison express 75018"] },
  },
  {
    slug: "paris-19e",
    dept: "75019",
    name: "Paris 19e",
    fullName: "Paris 19e arrondissement",
    category: "paris",
    landmarks: ["La Villette","Parc des Buttes-Chaumont","Hôpital Robert-Debré","Philharmonie de Paris","Cité des Sciences"],
    intro: "Le 19e arrondissement est le cœur vert et culturel du Nord-Est parisien. Le pôle de la Villette attire expositions et congrès géants, tandis que l'Hôpital Robert-Debré s'impose comme une référence en pédiatrie.",
    logisticsContext: "L'accès aux grands parcs et au périphérique (Porte de Pantin) offre d'excellents axes de dégagement. Nos véhicules utilitaires y opèrent fréquemment pour les livraisons volumineuses liées aux événements de La Villette.",
    sectors: [
      { name: "Médical & Laboratoires", example: "Transferts d'urgence, laits maternels et prélèvements pour l'Hôpital universitaire Robert-Debré.", serviceHref: "/services/transport-medical", serviceLabel: "Transport médical" },
      { name: "Événementiel", example: "Acheminement lourd d'instruments et de décors pour la Philharmonie et la Grande Halle de la Villette.", serviceHref: "/services/transport-evenementiel", serviceLabel: "Transport de matériel" },
      { name: "Corporate & Agences", example: "Liaisons régulières pour les administrations et sièges sociaux du canal de l'Ourcq.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Course dédiée" },
      { name: "Juridique & Notarial", example: "Transport d'actes officiels pour les institutions culturelles publiques.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Plis confidentiels" },
      { name: "E-commerce & Luxe", example: "Distribution pour les nouveaux quartiers résidentiels et éco-quartiers.", serviceHref: "/services/livraison-e-commerce", serviceLabel: "Livraison e-commerce" },
      { name: "Grands comptes", example: "Logistique d'expositions complètes pour la Cité des Sciences.", serviceHref: "/services/compte-entreprise", serviceLabel: "Compte institutionnel" },
    ],
    keyClients: ["Hôpital Robert-Debré","Philharmonie de Paris","La Villette (Expositions)","Institutions publiques"],
    distanceParis: "Nord",
    pricingZone: "standard",
    seo: { title: "Coursier Paris 19e — La Villette, Hôpital Robert-Debré | ONE CONNEXION", description: "Coursier express Paris 19e (75019). Transport médical pédiatrique (Robert-Debré), logistique événementielle lourde (La Villette).", keywords: ["coursier Paris 19e","coursier La Villette","coursier médical 75019","livraison express Paris 19"] },
  },
  {
    slug: "paris-20e",
    dept: "75020",
    name: "Paris 20e",
    fullName: "Paris 20e arrondissement",
    category: "paris",
    landmarks: ["Cimetière du Père-Lachaise","Belleville","Hôpital Tenon","Ménilmontant","Porte de Bagnolet"],
    intro: "Vivant, artistique et en perpétuelle ébullition, le 20e arrondissement est un laboratoire pour les start-ups et l'économie solidaire. L'Hôpital Tenon, spécialiste mondial des pathologies rénales, s'y dresse en pôle d'excellence.",
    logisticsContext: "La topographie vallonnée de Belleville et Ménilmontant nécessite une conduite experte. Notre flotte réactive assure des livraisons de bout en bout, connectant très rapidement l'Est au centre de Paris.",
    sectors: [
      { name: "Médical & Laboratoires", example: "Courses d'urgence, transport de greffons et de tissus pour l'Hôpital Tenon.", serviceHref: "/services/transport-medical", serviceLabel: "Transport médical" },
      { name: "Corporate & Agences", example: "Navettes B2B pour les pépinières d'entreprises et espaces créatifs de Belleville.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Course dédiée" },
      { name: "Événementiel", example: "Transport d'œuvres pour les ateliers d'artistes et galeries de l'Est parisien.", serviceHref: "/services/transport-evenementiel", serviceLabel: "Transport d'art" },
      { name: "Juridique & Notarial", example: "Acheminement de contrats et dossiers de subventions pour les associations.", serviceHref: "/services/plis-confidentiels", serviceLabel: "Plis confidentiels" },
      { name: "E-commerce & Luxe", example: "Livraisons express de paniers et produits sourcés par les commerces de proximité.", serviceHref: "/services/livraison-e-commerce", serviceLabel: "Livraison e-commerce" },
      { name: "Grands comptes", example: "Centralisation des flux pour les pôles hospitaliers de l'AP-HP.", serviceHref: "/services/compte-entreprise", serviceLabel: "Compte entreprise" },
    ],
    keyClients: ["Hôpital Tenon (AP-HP)","Start-ups et Pépinières","Ateliers d'artistes","Commerces de bouche"],
    distanceParis: "Est",
    pricingZone: "standard",
    seo: { title: "Coursier Paris 20e — Hôpital Tenon, Belleville, Père-Lachaise | ONE CONNEXION", description: "Coursier express Paris 20e (75020). Urgences médicales Hôpital Tenon, navettes pour start-ups et galeries de Belleville. Enlèvement < 45 min.", keywords: ["coursier Paris 20e","coursier Hôpital Tenon","coursier Belleville","livraison express 75020"] },
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// EXPORT CENTRAL
// ─────────────────────────────────────────────────────────────────────────────
export const ZONES: Zone[] = [
  ...ZONES_75,
  ...ZONES_92,
  ...ZONES_93,
  ...ZONES_94,
  ...ZONES_91,
  ...ZONES_95,
  ...ZONES_77,
  ...ZONES_78,
];

export const ZONE_SLUGS = ZONES.map((z) => z.slug);

export function getZone(slug: string): Zone | undefined {
  return ZONES.find((z) => z.slug === slug);
}

export function getZonesByCategory(category: Zone["category"]): Zone[] {
  return ZONES.filter((z) => z.category === category);
}
