import { makeZone } from "./factory";
import type { Zone } from "./types";

export const ZONES_91: Zone[] = [
  makeZone({
    slug: "evry-courcouronnes",
    dept: "91000",
    name: "Évry-Courcouronnes",
    fullName: "Évry-Courcouronnes — Essonne",
    category: "val-de-marne",
    landmarks: ["Préfecture de l'Essonne", "EVRY 2", "Université d'Évry", "A6", "RER D"],
    intro: "Évry-Courcouronnes est la préfecture de l'Essonne. Elle concentre administrations, le Tribunal judiciaire d'Évry, l'Université d'Évry et un tissu dense de PME et de services. C'est le principal centre d'affaires du sud de l'Île-de-France.",
    logisticsContext: "Évry est à 30 minutes de Paris 13e via l'A6. Nos coursiers desservent toute l'agglomération d'Évry et couvrent les principales zones d'activités.",
    sectorExamples: {
      juridique: "Dépôts au greffe du Tribunal judiciaire d'Évry, liaisons entre cabinets et Préfecture.",
      medical: "Transport de prélèvements et matériel médical depuis le Centre Hospitalier Sud Francilien (CHSF).",
      ecommerce: "Livraisons same-day pour les boutiques et e-commerçants d'Évry et de sa région.",
      corporate: "Navettes entre les sièges de PME d'Évry et leurs partenaires parisiens.",
      evenementiel: "Transport de matériel pour les événements corporates d'Évry.",
      grandsComptes: "Compte pour le CHSF, la Préfecture 91 et les grands groupes d'Évry.",
    },
    keyClients: ["Tribunal d'Évry", "Préfecture 91", "CHSF", "Université d'Évry", "PME"],
    distanceParis: "~30 min de Paris 13e",
    pricingZone: "devis",
    seoTitle: "Coursier Évry-Courcouronnes — Tribunal, Préfecture 91 | ONE CONNEXION",
    seoDesc: "Coursier express à Évry-Courcouronnes (91). Tribunal, Préfecture, CHSF. Sur devis pour l'Essonne.",
    seoKeywords: ["coursier Évry", "livraison express 91000", "coursier tribunal Évry", "coursier 91 Évry"],
  }),
  makeZone({
    slug: "massy",
    dept: "91300",
    name: "Massy",
    fullName: "Massy — Essonne",
    category: "val-de-marne",
    landmarks: ["Pôle scientifique de Saclay", "Gare TGV Massy-Palaiseau", "A10", "RER B"],
    intro: "Massy est un pôle économique et scientifique majeur, porte d'entrée du plateau de Saclay. La gare TGV de Massy et les sièges de grands groupes (Thales, CEA, Danone R&D) en font l'une des villes les plus stratégiques d'Île-de-France.",
    logisticsContext: "Massy est à 25 minutes de Paris 14e via l'A6. Sa gare TGV permet des connexions nationales rapides. Nos coursiers couvrent tout Massy et le plateau de Saclay.",
    sectorExamples: {
      juridique: "Transport de contrats entre les directions juridiques de Massy et leurs cabinets parisiens.",
      medical: "Transport de matériaux de recherche entre les laboratoires R&D et leurs partenaires.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants de Massy.",
      corporate: "Navettes entre Thales, le CEA, Danone R&D et leurs partenaires.",
      evenementiel: "Transport pour les événements scientifiques du plateau de Saclay.",
      grandsComptes: "Compte pour Thales, le CEA et les grands groupes du pôle Saclay.",
    },
    keyClients: ["Thales", "CEA Saclay", "Danone R&D", "Universités Paris-Saclay"],
    distanceParis: "~25 min de Paris 14e",
    pricingZone: "devis",
    seoTitle: "Coursier Massy — Thales, CEA Saclay, 91300 | ONE CONNEXION",
    seoDesc: "Coursier express à Massy (91). Thales, CEA Saclay, plateau scientifique. Sur devis Essonne.",
    seoKeywords: ["coursier Massy", "livraison express 91300", "coursier Thales Massy", "coursier CEA Saclay"],
  }),
  makeZone({
    slug: "palaiseau",
    dept: "91120",
    name: "Palaiseau",
    fullName: "Palaiseau — Essonne",
    category: "val-de-marne",
    landmarks: ["École Polytechnique", "Danone Research", "CEA Saclay", "A10", "RER B"],
    intro: "Palaiseau est au cœur du plateau de Saclay, l'un des dix meilleurs pôles de recherche mondiaux. L'École Polytechnique, Danone Research et le CEA y concentrent l'excellence scientifique française. Les besoins en transport de documents sensibles et de matériaux de recherche sont permanents.",
    logisticsContext: "Palaiseau est accessible depuis l'A10 et la D128. Nos coursiers desservent l'X, le CEA et les entreprises du plateau en moins de 35 minutes depuis Paris.",
    sectorExamples: {
      juridique: "Transport de contrats de recherche et documents officiels entre les institutions du plateau et Paris.",
      medical: "Transport de matériaux biologiques et de recherche entre Danone Research, le CEA et les laboratoires.",
      ecommerce: "Livraisons pour les boutiques et commerçants de Palaiseau.",
      corporate: "Navettes entre l'École Polytechnique, le CEA et leurs partenaires industriels.",
      evenementiel: "Transport de matériel pour les événements scientifiques et conférences de l'X.",
      grandsComptes: "Compte pour l'École Polytechnique, Danone Research et le CEA.",
    },
    keyClients: ["École Polytechnique", "CEA Saclay", "Danone Research", "Startup Saclay"],
    distanceParis: "~35 min de Paris 14e",
    pricingZone: "devis",
    seoTitle: "Coursier Palaiseau — École Polytechnique, CEA Saclay 91120 | ONE CONNEXION",
    seoDesc: "Coursier express à Palaiseau (91). École Polytechnique, CEA, Saclay. Sur devis Essonne.",
    seoKeywords: ["coursier Palaiseau", "livraison express 91120", "coursier Polytechnique Palaiseau", "coursier plateau Saclay"],
  }),
  makeZone({
    slug: "les-ulis",
    dept: "91940",
    name: "Les Ulis",
    fullName: "Les Ulis — Essonne",
    category: "val-de-marne",
    landmarks: ["Zone industrielle des Ulis", "A10", "Courtabœuf", "Villebon-sur-Yvette"],
    intro: "Les Ulis abrite l'une des plus importantes zones industrielles high-tech d'Île-de-France (Courtabœuf). Des centaines d'entreprises technologiques, biotech et de R&D y sont installées. Les flux logistiques B2B entre cette zone et Paris sont constants.",
    logisticsContext: "Les Ulis sont accessibles depuis l'A10. Nos coursiers desservent la zone Courtabœuf et relient Les Ulis à Paris en moins de 40 minutes.",
    sectorExamples: {
      juridique: "Transport de contrats entre les directions juridiques des groupes tech et leurs cabinets parisiens.",
      medical: "Transport de matériaux biotech entre les laboratoires des Ulis et leurs partenaires.",
      ecommerce: "Livraisons pour les boutiques et commerces des Ulis.",
      corporate: "Navettes entre les entreprises de Courtabœuf et leurs clients et partenaires parisiens.",
      evenementiel: "Transport de matériel pour les événements tech des Ulis.",
      grandsComptes: "Compte pour les groupes tech et biotech de la zone Courtabœuf.",
    },
    keyClients: ["Zone Courtabœuf", "Entreprises biotech", "Groupes high-tech", "R&D"],
    distanceParis: "~40 min de Paris 14e",
    pricingZone: "devis",
    seoTitle: "Coursier Les Ulis — Zone Courtabœuf, High-tech 91940 | ONE CONNEXION",
    seoDesc: "Coursier express aux Ulis (91). Zone Courtabœuf, biotech, high-tech. Sur devis Essonne.",
    seoKeywords: ["coursier Les Ulis", "livraison express 91940", "coursier Courtabœuf Les Ulis", "coursier 91 Ulis"],
  }),
  makeZone({
    slug: "longjumeau",
    dept: "91160",
    name: "Longjumeau",
    fullName: "Longjumeau — Essonne",
    category: "val-de-marne",
    landmarks: ["Zone Silic", "A10", "RER C", "Antony (proche)"],
    intro: "Longjumeau accueille la zone d'activités Silic, un pôle de services et de technologies. Sa position sur l'A10 et le RER C en fait un point de transit important du sud de l'Île-de-France.",
    logisticsContext: "Longjumeau est accessible depuis l'A10. Nos coursiers relient Longjumeau à Paris en moins de 35 minutes.",
    sectorExamples: {
      juridique: "Transport de documents entre les entreprises de Longjumeau et leurs conseils.",
      medical: "Transport inter-établissements de santé de Longjumeau.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants de Longjumeau.",
      corporate: "Navettes entre les PME de la zone Silic et leurs clients.",
      evenementiel: "Transport pour les événements des entreprises de Longjumeau.",
      grandsComptes: "Compte pour les groupes de la zone Silic.",
    },
    keyClients: ["Zone Silic", "PME tech", "Services B2B"],
    distanceParis: "~35 min de Paris 14e",
    pricingZone: "devis",
    seoTitle: "Coursier Longjumeau — Zone Silic, 91160 | ONE CONNEXION",
    seoDesc: "Coursier express à Longjumeau (91). Zone Silic, tech, PME. Sur devis Essonne.",
    seoKeywords: ["coursier Longjumeau", "livraison express 91160", "coursier 91 Longjumeau"],
  }),
  makeZone({
    slug: "corbeil-essonnes",
    dept: "91100",
    name: "Corbeil-Essonnes",
    fullName: "Corbeil-Essonnes — Essonne",
    category: "val-de-marne",
    landmarks: ["Centre Hospitalier Sud Francilien", "Sanofi", "Essonne", "A6", "RER D"],
    intro: "Corbeil-Essonnes abrite le Centre Hospitalier Sud Francilien, l'un des plus grands hôpitaux d'Île-de-France, et le site de production de Sanofi. Ce mélange de pharmacie et de santé crée des besoins logistiques très spécialisés.",
    logisticsContext: "Corbeil-Essonnes est accessible depuis l'A6. Nos coursiers desservent le CHSF et le site Sanofi avec les protocoles adaptés.",
    sectorExamples: {
      juridique: "Transport de contrats entre Sanofi et ses partenaires et conseils juridiques.",
      medical: "Transport de médicaments et matériaux de recherche entre Sanofi, le CHSF et les laboratoires.",
      ecommerce: "Livraisons pour les boutiques de Corbeil-Essonnes.",
      corporate: "Navettes entre les directions de Sanofi et leurs partenaires.",
      evenementiel: "Transport de matériel pour les congrès médicaux.",
      grandsComptes: "Compte pour Sanofi et le CHSF.",
    },
    keyClients: ["Sanofi", "Centre Hospitalier Sud Francilien", "PME"],
    distanceParis: "~40 min de Paris 13e",
    pricingZone: "devis",
    seoTitle: "Coursier Corbeil-Essonnes — Sanofi, CHSF 91100 | ONE CONNEXION",
    seoDesc: "Coursier express à Corbeil-Essonnes (91). Sanofi, CHSF, pharma. Sur devis Essonne.",
    seoKeywords: ["coursier Corbeil-Essonnes", "livraison express 91100", "coursier Sanofi Corbeil", "coursier 91 Corbeil"],
  }),
  makeZone({
    slug: "sainte-genevieve-des-bois",
    dept: "91700",
    name: "Sainte-Geneviève-des-Bois",
    fullName: "Sainte-Geneviève-des-Bois — Essonne",
    category: "val-de-marne",
    landmarks: ["Zone industrielle", "A6", "RER C", "Longjumeau (proche)"],
    intro: "Sainte-Geneviève-des-Bois est une ville résidentielle et industrielle du nord de l'Essonne. Ses zones d'activités regroupent des PME de services, d'industrie et de logistique bien positionnées sur les axes autoroutiers.",
    logisticsContext: "SGdB est accessible depuis l'A6. Nos coursiers relient la ville à Paris en moins de 40 minutes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets et les tribunaux.",
      medical: "Transport inter-établissements de santé.",
      ecommerce: "Livraisons pour les boutiques locales.",
      corporate: "Navettes entre les PME et leurs partenaires parisiens.",
      evenementiel: "Transport pour les événements locaux.",
      grandsComptes: "Compte pour les PME des zones d'activités.",
    },
    keyClients: ["PME industrielles", "Services B2B", "Logisticiens"],
    distanceParis: "~40 min de Paris 14e",
    pricingZone: "devis",
    seoTitle: "Coursier Sainte-Geneviève-des-Bois — 91700 | ONE CONNEXION",
    seoDesc: "Coursier express à Sainte-Geneviève-des-Bois (91). PME, zones d'activités. Sur devis Essonne.",
    seoKeywords: ["coursier Sainte-Geneviève-des-Bois", "livraison express 91700", "coursier 91 Ste-Geneviève"],
  }),
  makeZone({
    slug: "viry-chatillon",
    dept: "91170",
    name: "Viry-Châtillon",
    fullName: "Viry-Châtillon — Essonne",
    category: "val-de-marne",
    landmarks: ["Seine", "A86", "A6", "Juvisy (proche)"],
    intro: "Viry-Châtillon est une ville résidentielle et de services sur les bords de Seine, bien desservie par l'A86 et l'A6. Son tissu économique comprend des PME et des professions libérales qui ont des besoins de livraison express réguliers.",
    logisticsContext: "Viry-Châtillon est accessible depuis l'A86. Nos coursiers relient la ville à Paris en moins de 35 minutes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Viry et les tribunaux voisins.",
      medical: "Transport inter-établissements de santé de Viry-Châtillon.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants de Viry.",
      corporate: "Navettes entre les PME de Viry et leurs partenaires.",
      evenementiel: "Transport pour les événements locaux.",
      grandsComptes: "Compte pour les PME de Viry-Châtillon.",
    },
    keyClients: ["PME", "Professions libérales", "Commerces"],
    distanceParis: "~35 min de Paris 13e",
    pricingZone: "devis",
    seoTitle: "Coursier Viry-Châtillon — Livraison express 91170 | ONE CONNEXION",
    seoDesc: "Coursier express à Viry-Châtillon (91). PME, professions libérales. Sur devis Essonne.",
    seoKeywords: ["coursier Viry-Châtillon", "livraison express 91170", "coursier 91 Viry"],
  }),
  makeZone({
    slug: "juvisy-sur-orge",
    dept: "91260",
    name: "Juvisy-sur-Orge",
    fullName: "Juvisy-sur-Orge — Essonne",
    category: "val-de-marne",
    landmarks: ["Gare de Juvisy (nœud RER)", "Seine", "A6", "Orly (proche)"],
    intro: "Juvisy-sur-Orge est un nœud ferroviaire majeur : la gare de Juvisy est l'une des plus fréquentées d'Île-de-France (croisement RER C et D). Sa position entre Paris et Évry en fait un point logistique actif pour les entreprises du sud.",
    logisticsContext: "Juvisy est accessible depuis l'A6. Nos coursiers relient Juvisy à Paris en moins de 30 minutes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Juvisy et les juridictions.",
      medical: "Transport inter-établissements de santé de Juvisy.",
      ecommerce: "Livraisons pour les boutiques et commerces de Juvisy.",
      corporate: "Navettes entre les PME de Juvisy et leurs partenaires.",
      evenementiel: "Transport pour les événements locaux.",
      grandsComptes: "Compte pour les PME de Juvisy-sur-Orge.",
    },
    keyClients: ["PME", "Commerces", "Services"],
    distanceParis: "~30 min de Paris 13e",
    pricingZone: "devis",
    seoTitle: "Coursier Juvisy-sur-Orge — Nœud RER, 91260 | ONE CONNEXION",
    seoDesc: "Coursier express à Juvisy-sur-Orge (91). Gare RER, PME, services. Sur devis Essonne.",
    seoKeywords: ["coursier Juvisy-sur-Orge", "livraison express 91260", "coursier 91 Juvisy"],
  }),
  makeZone({
    slug: "athis-mons",
    dept: "91200",
    name: "Athis-Mons",
    fullName: "Athis-Mons — Essonne",
    category: "val-de-marne",
    landmarks: ["Aéroport d'Orly (limite)", "A86", "Seine", "Paray-Vieille-Poste"],
    intro: "Athis-Mons est limitrophe de l'aéroport d'Orly et accueille de nombreuses entreprises aéronautiques et de services aéroportuaires. La présence d'Orly à quelques centaines de mètres génère des besoins logistiques très spécifiques.",
    logisticsContext: "Athis-Mons est accessible depuis l'A86. Nos coursiers desservent les zones aéroportuaires d'Orly et d'Athis en moins de 25 minutes depuis Paris.",
    sectorExamples: {
      juridique: "Transport de contrats entre les opérateurs aéronautiques et leurs conseils.",
      medical: "Transport médical urgent depuis les zones aéroportuaires.",
      ecommerce: "Livraisons pour les boutiques d'Athis-Mons.",
      corporate: "Navettes entre les entreprises aéronautiques et leurs partenaires parisiens.",
      evenementiel: "Transport pour les événements des hôtels et structures aéroportuaires.",
      grandsComptes: "Compte pour les opérateurs aéronautiques d'Athis-Mons.",
    },
    keyClients: ["Entreprises aéronautiques", "Hôtels aéroport Orly", "PME"],
    distanceParis: "~25 min de Paris 13e",
    pricingZone: "devis",
    seoTitle: "Coursier Athis-Mons — Orly, Aéronautique 91200 | ONE CONNEXION",
    seoDesc: "Coursier express à Athis-Mons (91). Aéroport Orly, aéronautique. Sur devis Essonne.",
    seoKeywords: ["coursier Athis-Mons", "livraison express 91200", "coursier Orly Athis-Mons", "coursier 91 Athis"],
  }),
];
