import { makeZone } from "./factory";
import type { Zone } from "./types";

export const ZONES_78: Zone[] = [
  makeZone({
    slug: "versailles",
    dept: "78000",
    name: "Versailles",
    fullName: "Versailles — Yvelines",
    category: "hauts-de-seine",
    landmarks: ["Château de Versailles", "Tribunal judiciaire de Versailles", "A12", "RER C"],
    intro: "Versailles est la préfecture des Yvelines et accueille le Tribunal judiciaire et la Cour d'appel de Versailles, juridiction d'appel compétente pour toute l'Île-de-France hors Paris. C'est aussi une destination touristique et culturelle mondiale. One Connexion dessert quotidiennement les cabinets d'avocats et les institutions versaillaises.",
    logisticsContext: "Versailles est à 30 minutes de Paris 15e via l'A12. Nos coursiers connaissent les accès au Tribunal de Versailles et aux différentes juridictions.",
    sectorExamples: {
      juridique: "Liaisons entre les cabinets d'avocats de Versailles, la Cour d'appel et le Tribunal judiciaire.",
      medical: "Transport de prélèvements depuis l'Hôpital de Versailles vers les laboratoires.",
      ecommerce: "Livraisons pour les boutiques de prestige de Versailles.",
      corporate: "Navettes entre les sièges d'entreprises de Versailles et leurs partenaires parisiens.",
      evenementiel: "Transport de matériel pour les événements au château de Versailles.",
      grandsComptes: "Compte pour les cabinets de la Cour d'appel et les grandes institutions de Versailles.",
    },
    keyClients: ["Cour d'appel de Versailles", "Tribunal judiciaire", "Hôpital Versailles", "Cabinets d'avocats"],
    distanceParis: "~30 min de Paris 15e",
    pricingZone: "devis",
    seoTitle: "Coursier Versailles — Cour d'appel, Château, 78000 | ONE CONNEXION",
    seoDesc: "Coursier express à Versailles (78). Cour d'appel, Tribunal, château. Sur devis Yvelines.",
    seoKeywords: ["coursier Versailles", "livraison express 78000", "coursier Cour d'appel Versailles", "coursier 78 Versailles"],
  }),
  makeZone({
    slug: "saint-germain-en-laye",
    dept: "78100",
    name: "Saint-Germain-en-Laye",
    fullName: "Saint-Germain-en-Laye — Yvelines",
    category: "hauts-de-seine",
    landmarks: ["Château de Saint-Germain", "Forêt de Saint-Germain", "RER A", "A13"],
    intro: "Saint-Germain-en-Laye est une ville résidentielle de prestige en bord de Seine, desservie par le RER A. Son château, ses forêts et ses hôtels de luxe attirent une clientèle aisée. Les professions libérales et les directions d'entreprises y sont nombreuses.",
    logisticsContext: "Saint-Germain-en-Laye est à 35 minutes de La Défense via le RER A et l'A13. Nos coursiers effectuent des missions express entre Saint-Germain et Paris.",
    sectorExamples: {
      juridique: "Transport entre les études notariales de Saint-Germain et les juridictions.",
      medical: "Transport entre les cliniques privées de prestige et les laboratoires.",
      ecommerce: "Livraisons premium pour les boutiques et résidences de Saint-Germain.",
      corporate: "Navettes entre les directions d'entreprises de Saint-Germain et leurs partenaires.",
      evenementiel: "Transport pour les événements du château et les réceptions des hôtels.",
      grandsComptes: "Compte pour les professions libérales et entreprises de Saint-Germain.",
    },
    keyClients: ["Château de Saint-Germain", "Cliniques prestige", "Professions libérales", "Hôtels luxe"],
    distanceParis: "~35 min de La Défense",
    pricingZone: "devis",
    seoTitle: "Coursier Saint-Germain-en-Laye — Château, Prestige 78100 | ONE CONNEXION",
    seoDesc: "Coursier express à Saint-Germain-en-Laye (78). Château, cliniques prestige, professions libérales. Sur devis.",
    seoKeywords: ["coursier Saint-Germain-en-Laye", "livraison express 78100", "coursier 78 Saint-Germain"],
  }),
  makeZone({
    slug: "mantes-la-jolie",
    dept: "78200",
    name: "Mantes-la-Jolie",
    fullName: "Mantes-la-Jolie — Yvelines",
    category: "hauts-de-seine",
    landmarks: ["Seine", "A13", "Gare de Mantes", "Pôle économique"],
    intro: "Mantes-la-Jolie est la deuxième ville des Yvelines. Pôle industriel et de services sur la Seine, elle accueille des entreprises dans des secteurs variés et constitue un centre économique important du nord des Yvelines.",
    logisticsContext: "Mantes-la-Jolie est à 60 minutes de Paris via l'A13. Nos coursiers effectuent des missions express vers Mantes sur demande.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Mantes et les juridictions de Versailles.",
      medical: "Transport depuis le Centre Hospitalier de Mantes vers les laboratoires.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants de Mantes.",
      corporate: "Navettes entre les entreprises de Mantes et leurs partenaires parisiens.",
      evenementiel: "Transport pour les événements locaux.",
      grandsComptes: "Compte pour les grandes entreprises de Mantes.",
    },
    keyClients: ["CH Mantes", "Industriels", "PME", "Services"],
    distanceParis: "~60 min de Paris",
    pricingZone: "devis",
    seoTitle: "Coursier Mantes-la-Jolie — CH, Zone industrielle 78200 | ONE CONNEXION",
    seoDesc: "Coursier express à Mantes-la-Jolie (78). Hôpital, industriels, PME. Sur devis Yvelines.",
    seoKeywords: ["coursier Mantes-la-Jolie", "livraison express 78200", "coursier 78 Mantes"],
  }),
  makeZone({
    slug: "poissy",
    dept: "78300",
    name: "Poissy",
    fullName: "Poissy — Yvelines",
    category: "hauts-de-seine",
    landmarks: ["PSA / Stellantis", "Seine", "A13", "Villennes-sur-Seine (limite)"],
    intro: "Poissy est historiquement liée à l'industrie automobile. L'usine Stellantis (ex-PSA Peugeot-Citroën) y est implantée depuis des décennies. Ce tissu industriel génère des besoins logistiques B2B importants.",
    logisticsContext: "Poissy est à 35 minutes de Paris via l'A13. Nos coursiers relient Poissy à Paris et La Défense rapidement.",
    sectorExamples: {
      juridique: "Transport de contrats entre les directions juridiques de Stellantis et leurs cabinets.",
      medical: "Transport inter-établissements de santé de Poissy.",
      ecommerce: "Livraisons pour les boutiques de Poissy.",
      corporate: "Navettes entre Stellantis et ses partenaires et fournisseurs.",
      evenementiel: "Transport de matériel pour les événements corporate de Stellantis.",
      grandsComptes: "Compte pour Stellantis et les sous-traitants automobiles de Poissy.",
    },
    keyClients: ["Stellantis (PSA)", "Sous-traitants auto", "PME", "Services"],
    distanceParis: "~35 min de Paris 17e",
    pricingZone: "devis",
    seoTitle: "Coursier Poissy — Stellantis, Automobile 78300 | ONE CONNEXION",
    seoDesc: "Coursier express à Poissy (78). Stellantis, industrie automobile. Sur devis Yvelines.",
    seoKeywords: ["coursier Poissy", "livraison express 78300", "coursier Stellantis Poissy", "coursier 78 Poissy"],
  }),
  makeZone({
    slug: "sartrouville",
    dept: "78500",
    name: "Sartrouville",
    fullName: "Sartrouville — Yvelines",
    category: "hauts-de-seine",
    landmarks: ["Seine", "A86", "Argenteuil (limite)", "RER A"],
    intro: "Sartrouville est une ville industrielle et résidentielle en bord de Seine, limitrophe d'Argenteuil et accessible depuis l'A86. Son tissu économique mêle industries, PME et services.",
    logisticsContext: "Sartrouville est accessible depuis l'A86. Nos coursiers relient Sartrouville à Paris 17e en moins de 25 minutes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Sartrouville et les juridictions.",
      medical: "Transport inter-établissements de santé de Sartrouville.",
      ecommerce: "Livraisons pour les boutiques de Sartrouville.",
      corporate: "Navettes entre les entreprises de Sartrouville et leurs partenaires.",
      evenementiel: "Transport pour les événements locaux.",
      grandsComptes: "Compte pour les PME et industriels de Sartrouville.",
    },
    keyClients: ["Industriels", "PME", "Services"],
    distanceParis: "~25 min de Paris 17e",
    pricingZone: "devis",
    seoTitle: "Coursier Sartrouville — Livraison express 78500 | ONE CONNEXION",
    seoDesc: "Coursier express à Sartrouville (78). Industries, PME. Sur devis Yvelines.",
    seoKeywords: ["coursier Sartrouville", "livraison express 78500", "coursier 78 Sartrouville"],
  }),
  makeZone({
    slug: "guyancourt",
    dept: "78280",
    name: "Guyancourt",
    fullName: "Guyancourt — Yvelines",
    category: "hauts-de-seine",
    landmarks: ["Technocentre Renault", "Quartier de Montigny (SQY)", "A12", "Versailles (proche)"],
    intro: "Guyancourt abrite le Technocentre mondial de Renault, l'un des plus grands centres de R&D automobile du monde. Saint-Quentin-en-Yvelines est l'un des principaux pôles technologiques d'Île-de-France, avec des centaines d'entreprises.",
    logisticsContext: "Guyancourt est à 30 minutes de Paris via l'A12. Nos coursiers connaissent les accès au Technocentre Renault.",
    sectorExamples: {
      juridique: "Transport de contrats entre les directions juridiques de Renault et leurs cabinets conseil.",
      medical: "Transport de matériaux de R&D et médicaux entre Guyancourt et les laboratoires.",
      ecommerce: "Livraisons pour les boutiques de Saint-Quentin-en-Yvelines.",
      corporate: "Navettes entre le Technocentre Renault et ses partenaires et sous-traitants.",
      evenementiel: "Transport pour les événements corporate du Technocentre.",
      grandsComptes: "Compte pour Renault et les grandes entreprises de Saint-Quentin-en-Yvelines.",
    },
    keyClients: ["Technocentre Renault", "Sous-traitants auto", "Pôle SQY", "PME tech"],
    distanceParis: "~30 min de Paris 15e",
    pricingZone: "devis",
    seoTitle: "Coursier Guyancourt — Renault Technocentre, SQY 78280 | ONE CONNEXION",
    seoDesc: "Coursier express à Guyancourt (78). Renault Technocentre, Saint-Quentin-en-Yvelines. Sur devis.",
    seoKeywords: ["coursier Guyancourt", "livraison express 78280", "coursier Renault Technocentre Guyancourt", "coursier SQY"],
  }),
  makeZone({
    slug: "velizy-villacoublay",
    dept: "78140",
    name: "Vélizy-Villacoublay",
    fullName: "Vélizy-Villacoublay — Yvelines",
    category: "hauts-de-seine",
    landmarks: ["Dassault Aviation", "Thales", "Boeing", "N186", "A86"],
    intro: "Vélizy-Villacoublay est l'un des pôles aéronautiques et technologiques les plus denses d'Europe. Dassault Aviation, Thales, Boeing France et des centaines d'entreprises high-tech y ont leur siège. Les besoins en transport express B2B sont parmi les plus élevés d'Île-de-France.",
    logisticsContext: "Vélizy est accessible depuis l'A86. Nos coursiers relient Vélizy à Paris 15e en moins de 25 minutes.",
    sectorExamples: {
      juridique: "Transport de contrats entre les directions juridiques des groupes aéronautiques et leurs cabinets.",
      medical: "Transport de matériaux de recherche aéronautique et médicale.",
      ecommerce: "Livraisons pour les boutiques de Vélizy 2 et les e-commerçants.",
      corporate: "Navettes entre Dassault, Thales, Boeing et leurs partenaires parisiens.",
      evenementiel: "Transport de matériel pour les événements corporate des groupes aéronautiques.",
      grandsComptes: "Compte pour Dassault Aviation, Thales et Boeing France.",
    },
    keyClients: ["Dassault Aviation", "Thales", "Boeing France", "Groupes high-tech"],
    distanceParis: "~25 min de Paris 15e",
    pricingZone: "devis",
    seoTitle: "Coursier Vélizy-Villacoublay — Dassault, Thales, Boeing 78140 | ONE CONNEXION",
    seoDesc: "Coursier express à Vélizy-Villacoublay (78). Dassault, Thales, Boeing, aéronautique. Sur devis.",
    seoKeywords: ["coursier Vélizy-Villacoublay", "livraison express 78140", "coursier Dassault Vélizy", "coursier aéronautique Vélizy"],
  }),
  makeZone({
    slug: "chatou",
    dept: "78400",
    name: "Chatou",
    fullName: "Chatou — Yvelines",
    category: "hauts-de-seine",
    landmarks: ["Seine", "Île de Chatou", "RER A", "Rueil-Malmaison (limite)"],
    intro: "Chatou est une ville résidentielle et culturelle sur les bords de Seine, limitrophe de Rueil-Malmaison. Son île accueille des événements culturels importants. Son tissu de PME et de professions libérales génère des besoins logistiques réguliers.",
    logisticsContext: "Chatou est accessible depuis l'A13. Nos coursiers relient Chatou à La Défense en moins de 20 minutes.",
    sectorExamples: {
      juridique: "Transport entre les études de Chatou et les juridictions.",
      medical: "Transport inter-établissements de santé de Chatou.",
      ecommerce: "Livraisons pour les boutiques de Chatou.",
      corporate: "Navettes entre les PME de Chatou et leurs partenaires.",
      evenementiel: "Transport pour les événements culturels de l'Île de Chatou.",
      grandsComptes: "Compte pour les PME et professions libérales de Chatou.",
    },
    keyClients: ["PME", "Professions libérales", "Île de Chatou (événementiel)"],
    distanceParis: "~25 min de La Défense",
    pricingZone: "devis",
    seoTitle: "Coursier Chatou — Île de Chatou, 78400 | ONE CONNEXION",
    seoDesc: "Coursier express à Chatou (78). PME, professions libérales, événementiel. Sur devis.",
    seoKeywords: ["coursier Chatou", "livraison express 78400", "coursier 78 Chatou"],
  }),
  makeZone({
    slug: "houilles",
    dept: "78800",
    name: "Houilles",
    fullName: "Houilles — Yvelines",
    category: "hauts-de-seine",
    landmarks: ["A86", "Sartrouville (limite)", "Carrières-sur-Seine (limite)", "RER A"],
    intro: "Houilles est une commune résidentielle et économique du nord des Yvelines, bien desservie par l'A86. Son tissu de PME et de services génère des besoins de livraison express réguliers.",
    logisticsContext: "Houilles est accessible depuis l'A86. Nos coursiers relient Houilles à Paris 17e en moins de 20 minutes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Houilles et les juridictions.",
      medical: "Transport inter-établissements de santé de Houilles.",
      ecommerce: "Livraisons pour les boutiques de Houilles.",
      corporate: "Navettes entre les PME de Houilles et leurs partenaires.",
      evenementiel: "Transport pour les événements locaux.",
      grandsComptes: "Compte pour les PME multi-sites de Houilles.",
    },
    keyClients: ["PME", "Professions libérales", "Commerces"],
    distanceParis: "~20 min de Paris 17e",
    pricingZone: "devis",
    seoTitle: "Coursier Houilles — Livraison express 78800 | ONE CONNEXION",
    seoDesc: "Coursier express à Houilles (78). PME, professions libérales. Sur devis Yvelines.",
    seoKeywords: ["coursier Houilles", "livraison express 78800", "coursier 78 Houilles"],
  }),
];
