import { makeZone } from "./factory";
import type { Zone } from "./types";

export const ZONES_95: Zone[] = [
  makeZone({
    slug: "cergy",
    dept: "95000",
    name: "Cergy",
    fullName: "Cergy — Val-d'Oise",
    category: "hauts-de-seine",
    landmarks: ["Préfecture 95", "La Défense (30 min)", "CY Cergy Paris Université", "A15", "RER A"],
    intro: "Cergy est la préfecture du Val-d'Oise et le principal centre économique du 95. Cergy-Pontoise regroupe administrations, le Tribunal judiciaire, l'université et un tissu dense d'entreprises. Sa connexion à La Défense via le RER A en fait un pôle stratégique du nord de l'IDF.",
    logisticsContext: "Cergy est à 40 minutes de Paris via l'A15. Nos motos routières assurent des liaisons fiables entre Cergy et Paris ou La Défense.",
    sectorExamples: {
      juridique: "Liaisons entre le Tribunal judiciaire de Pontoise et les cabinets d'avocats de Cergy.",
      medical: "Transport de prélèvements et matériel médical depuis le Centre Hospitalier de Pontoise.",
      ecommerce: "Livraisons pour les boutiques des Trois-Fontaines et les e-commerçants de Cergy.",
      corporate: "Navettes entre les sièges d'entreprises de Cergy et leurs partenaires parisiens.",
      evenementiel: "Transport pour les événements de l'Axe Majeur et des espaces culturels de Cergy.",
      grandsComptes: "Compte pour la Préfecture 95, les grandes entreprises et le CH de Pontoise.",
    },
    keyClients: ["Préfecture 95", "Tribunal de Pontoise", "CH Pontoise", "Entreprises Cergy"],
    distanceParis: "~40 min de Paris",
    pricingZone: "devis",
    seoTitle: "Coursier Cergy — Préfecture 95, Tribunal Pontoise | ONE CONNEXION",
    seoDesc: "Coursier express à Cergy (95). Préfecture, tribunal, entreprises. Sur devis Val-d'Oise.",
    seoKeywords: ["coursier Cergy", "livraison express 95000", "coursier 95 Cergy", "coursier Val-d'Oise"],
  }),
  makeZone({
    slug: "argenteuil",
    dept: "95100",
    name: "Argenteuil",
    fullName: "Argenteuil — Val-d'Oise",
    category: "hauts-de-seine",
    landmarks: ["Seine", "Paris 17e (proche via pont)", "A15", "Zone industrielle"],
    intro: "Argenteuil est la plus grande ville du Val-d'Oise et borde la Seine face au 17e arrondissement. Son tissu industriel, ses PME et ses services génèrent des besoins logistiques intenses entre Argenteuil et Paris.",
    logisticsContext: "Argenteuil est à 20 minutes de Paris 17e via l'A15. Nos coursiers relient Argenteuil aux zones d'affaires parisiennes rapidement.",
    sectorExamples: {
      juridique: "Transport entre les cabinets d'Argenteuil et les juridictions de Paris et de Pontoise.",
      medical: "Transport inter-établissements de santé d'Argenteuil.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants d'Argenteuil.",
      corporate: "Navettes entre les PME et industries d'Argenteuil et leurs partenaires parisiens.",
      evenementiel: "Transport pour les événements et manifestations d'Argenteuil.",
      grandsComptes: "Compte pour les PME et industriels d'Argenteuil.",
    },
    keyClients: ["Industriels Seine", "PME", "Commerces", "Services"],
    distanceParis: "~20 min de Paris 17e",
    pricingZone: "devis",
    seoTitle: "Coursier Argenteuil — Livraison express 95100 | ONE CONNEXION",
    seoDesc: "Coursier express à Argenteuil (95). Industries, PME, Seine. Sur devis Val-d'Oise.",
    seoKeywords: ["coursier Argenteuil", "livraison express 95100", "coursier 95 Argenteuil"],
  }),
  makeZone({
    slug: "sarcelles",
    dept: "95200",
    name: "Sarcelles",
    fullName: "Sarcelles — Val-d'Oise",
    category: "hauts-de-seine",
    landmarks: ["A1", "A115", "Garges-lès-Gonesse (limite)", "Gare de Sarcelles"],
    intro: "Sarcelles est une ville dynamique du Val-d'Oise nord, avec un tissu commercial et de services actif. Sa position sur l'A1 en fait un point de transit entre Paris et Roissy CDG.",
    logisticsContext: "Sarcelles est accessible depuis l'A1. Nos coursiers relient Sarcelles à Paris 18e et à Roissy CDG en moins de 30 minutes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Sarcelles et les tribunaux de Pontoise et Bobigny.",
      medical: "Transport inter-établissements de santé de Sarcelles.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants de Sarcelles.",
      corporate: "Navettes entre les PME de Sarcelles et leurs partenaires.",
      evenementiel: "Transport pour les événements locaux.",
      grandsComptes: "Compte pour les PME de Sarcelles.",
    },
    keyClients: ["PME", "Commerces", "Services"],
    distanceParis: "~25 min de Paris 18e",
    pricingZone: "devis",
    seoTitle: "Coursier Sarcelles — Livraison express 95200 | ONE CONNEXION",
    seoDesc: "Coursier express à Sarcelles (95). PME, commerces. Sur devis Val-d'Oise.",
    seoKeywords: ["coursier Sarcelles", "livraison express 95200", "coursier 95 Sarcelles"],
  }),
  makeZone({
    slug: "gonesse",
    dept: "95500",
    name: "Gonesse",
    fullName: "Gonesse — Val-d'Oise",
    category: "hauts-de-seine",
    landmarks: ["Aéroport Roissy CDG (limite)", "A1", "Marché de Gonesse", "Triangle de Gonesse"],
    intro: "Gonesse est limitrophe de Roissy CDG et du Triangle de Gonesse, futur pôle économique majeur. Sa position entre l'A1 et l'aéroport en fait un hub logistique naturel pour les entreprises aéroportuaires.",
    logisticsContext: "Gonesse est à 5 minutes de Roissy CDG. Nos coursiers assurent des liaisons rapides entre l'aéroport et Paris ou toute la petite couronne.",
    sectorExamples: {
      juridique: "Transport de documents entre les opérateurs de Gonesse et leurs conseils.",
      medical: "Transport de médicaments depuis la zone aéroportuaire.",
      ecommerce: "Livraisons express pour les e-commerçants de Gonesse.",
      corporate: "Navettes entre les entreprises de Gonesse et leurs partenaires.",
      evenementiel: "Transport de matériel pour les événements des hôtels d'aéroport.",
      grandsComptes: "Compte pour les entreprises de la zone aéroportuaire de Gonesse.",
    },
    keyClients: ["Opérateurs Roissy CDG", "Entrepôts fret", "Hôtels aéroport"],
    distanceParis: "~30 min de Paris 18e",
    pricingZone: "devis",
    seoTitle: "Coursier Gonesse — Roissy CDG, Zone aéroportuaire 95500 | ONE CONNEXION",
    seoDesc: "Coursier express à Gonesse (95). Roissy CDG, zone aéroportuaire. Sur devis Val-d'Oise.",
    seoKeywords: ["coursier Gonesse", "livraison express 95500", "coursier Roissy Gonesse", "coursier 95 Gonesse"],
  }),
  makeZone({
    slug: "enghien-les-bains",
    dept: "95880",
    name: "Enghien-les-Bains",
    fullName: "Enghien-les-Bains — Val-d'Oise",
    category: "hauts-de-seine",
    landmarks: ["Lac d'Enghien", "Casino d'Enghien", "Maison du Lac", "A115", "Paris 18e (20 min)"],
    intro: "Enghien-les-Bains est la seule ville thermale d'Île-de-France. Son lac, son casino et ses hôtels de luxe attirent une clientèle aisée et des événements premium. Les professions libérales, cliniques privées et hôtels y ont des besoins logistiques réguliers.",
    logisticsContext: "Enghien est à 20 minutes de Paris 18e. Nos coursiers desservent le casino, les hôtels et les cliniques privées avec la discrétion requise.",
    sectorExamples: {
      juridique: "Transport discret de documents entre les études et cabinets d'Enghien et Paris.",
      medical: "Transport entre les cliniques thermales et spécialisées d'Enghien et les laboratoires.",
      ecommerce: "Livraisons premium pour les boutiques et résidences de prestige d'Enghien.",
      corporate: "Navettes entre les sièges d'entreprises et les hôtels d'Enghien.",
      evenementiel: "Transport de matériel pour les événements au Casino et à la Maison du Lac.",
      grandsComptes: "Compte pour le Casino d'Enghien et les hôtels premium.",
    },
    keyClients: ["Casino d'Enghien", "Hôtels luxe lac", "Cliniques thermales", "Professions libérales"],
    distanceParis: "~20 min de Paris 18e",
    pricingZone: "devis",
    seoTitle: "Coursier Enghien-les-Bains — Casino, Lac, Luxe 95880 | ONE CONNEXION",
    seoDesc: "Coursier express à Enghien-les-Bains (95). Casino, hôtels luxe, cliniques thermales. Sur devis.",
    seoKeywords: ["coursier Enghien-les-Bains", "livraison express 95880", "coursier casino Enghien", "coursier 95 Enghien"],
  }),
  makeZone({
    slug: "franconville",
    dept: "95130",
    name: "Franconville",
    fullName: "Franconville — Val-d'Oise",
    category: "hauts-de-seine",
    landmarks: ["Éragny (limite)", "A115", "Saint-Gratien (limite)"],
    intro: "Franconville est une ville résidentielle et économique du Val-d'Oise, bien positionnée sur l'A115. Son tissu de PME et de services génère des besoins logistiques réguliers entre le 95 et Paris.",
    logisticsContext: "Franconville est accessible depuis l'A115. Nos coursiers relient Franconville à Paris 17e en moins de 25 minutes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Franconville et les tribunaux.",
      medical: "Transport inter-établissements de santé de Franconville.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants de Franconville.",
      corporate: "Navettes entre les PME de Franconville et leurs partenaires parisiens.",
      evenementiel: "Transport pour les événements locaux.",
      grandsComptes: "Compte pour les PME de Franconville.",
    },
    keyClients: ["PME", "Professions libérales", "Commerces"],
    distanceParis: "~25 min de Paris 17e",
    pricingZone: "devis",
    seoTitle: "Coursier Franconville — Livraison express 95130 | ONE CONNEXION",
    seoDesc: "Coursier express à Franconville (95). PME, professions libérales. Sur devis Val-d'Oise.",
    seoKeywords: ["coursier Franconville", "livraison express 95130", "coursier 95 Franconville"],
  }),
  makeZone({
    slug: "ermont",
    dept: "95120",
    name: "Ermont",
    fullName: "Ermont — Val-d'Oise",
    category: "hauts-de-seine",
    landmarks: ["Gare d'Ermont-Eaubonne", "A115", "Enghien (limite)"],
    intro: "Ermont est une ville résidentielle desservie par le Transilien, proche d'Enghien-les-Bains. Son tissu économique de PME et de professions libérales est actif.",
    logisticsContext: "Ermont est accessible depuis l'A115. Nos coursiers relient Ermont à Paris en moins de 30 minutes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets d'Ermont et les juridictions.",
      medical: "Transport inter-établissements de santé d'Ermont.",
      ecommerce: "Livraisons pour les boutiques d'Ermont.",
      corporate: "Navettes entre les PME d'Ermont et leurs partenaires.",
      evenementiel: "Transport pour les événements locaux.",
      grandsComptes: "Compte pour les PME d'Ermont.",
    },
    keyClients: ["PME", "Professions libérales", "Commerces"],
    distanceParis: "~30 min de Paris 18e",
    pricingZone: "devis",
    seoTitle: "Coursier Ermont — Livraison express 95120 | ONE CONNEXION",
    seoDesc: "Coursier express à Ermont (95). PME, professions libérales. Sur devis Val-d'Oise.",
    seoKeywords: ["coursier Ermont", "livraison express 95120", "coursier 95 Ermont"],
  }),
  makeZone({
    slug: "herblay-sur-seine",
    dept: "95220",
    name: "Herblay-sur-Seine",
    fullName: "Herblay-sur-Seine — Val-d'Oise",
    category: "hauts-de-seine",
    landmarks: ["Seine", "A15", "Conflans (proche)", "Cormeilles (proche)"],
    intro: "Herblay-sur-Seine est une ville résidentielle en bord de Seine, bien desservie par l'A15. Son tissu économique comprend des PME et des professions libérales qui utilisent régulièrement des services de livraison express.",
    logisticsContext: "Herblay est accessible depuis l'A15. Nos coursiers relient Herblay à Paris 17e en moins de 30 minutes.",
    sectorExamples: {
      juridique: "Transport entre les études d'Herblay et les juridictions.",
      medical: "Transport inter-établissements de santé d'Herblay.",
      ecommerce: "Livraisons pour les boutiques d'Herblay.",
      corporate: "Navettes entre les PME d'Herblay et leurs partenaires.",
      evenementiel: "Transport pour les événements locaux.",
      grandsComptes: "Compte pour les PME d'Herblay.",
    },
    keyClients: ["PME", "Professions libérales", "Commerces"],
    distanceParis: "~30 min de Paris 17e",
    pricingZone: "devis",
    seoTitle: "Coursier Herblay-sur-Seine — Livraison express 95220 | ONE CONNEXION",
    seoDesc: "Coursier express à Herblay-sur-Seine (95). PME, bords de Seine. Sur devis Val-d'Oise.",
    seoKeywords: ["coursier Herblay-sur-Seine", "livraison express 95220", "coursier 95 Herblay"],
  }),
  makeZone({
    slug: "maisons-laffitte",
    dept: "78600",
    name: "Maisons-Laffitte",
    fullName: "Maisons-Laffitte — Yvelines",
    category: "hauts-de-seine",
    landmarks: ["Hippodrome de Maisons-Laffitte", "Château de Maisons", "Seine", "RER A"],
    intro: "Maisons-Laffitte est une ville résidentielle de prestige, connue pour son hippodrome et son château classé. Elle attire des professions libérales et des dirigeants d'entreprises qui ont des besoins logistiques B2B réguliers.",
    logisticsContext: "Maisons-Laffitte est accessible depuis l'A14. Nos coursiers relient Maisons-Laffitte à La Défense en moins de 25 minutes.",
    sectorExamples: {
      juridique: "Transport entre les études de Maisons-Laffitte et les juridictions.",
      medical: "Transport inter-établissements de santé de Maisons-Laffitte.",
      ecommerce: "Livraisons premium pour les boutiques et résidences de Maisons-Laffitte.",
      corporate: "Navettes entre les entreprises de Maisons-Laffitte et leurs partenaires.",
      evenementiel: "Transport pour les événements à l'hippodrome de Maisons-Laffitte.",
      grandsComptes: "Compte pour les entreprises et institutions de Maisons-Laffitte.",
    },
    keyClients: ["Hippodrome", "Professions libérales", "Résidences prestige", "Château de Maisons"],
    distanceParis: "~30 min de La Défense",
    pricingZone: "devis",
    seoTitle: "Coursier Maisons-Laffitte — Hippodrome, Château 78600 | ONE CONNEXION",
    seoDesc: "Coursier express à Maisons-Laffitte (78). Hippodrome, prestige, professions libérales. Sur devis.",
    seoKeywords: ["coursier Maisons-Laffitte", "livraison express 78600", "coursier hippodrome Maisons-Laffitte"],
  }),
  makeZone({
    slug: "conflans-sainte-honorine",
    dept: "78700",
    name: "Conflans-Sainte-Honorine",
    fullName: "Conflans-Sainte-Honorine — Yvelines",
    category: "hauts-de-seine",
    landmarks: ["Confluence Oise-Seine", "Port fluvial", "A15", "RER A"],
    intro: "Conflans-Sainte-Honorine est la capitale de la batellerie française, à la confluence de l'Oise et de la Seine. Son port fluvial, ses entreprises de transport et sa zone commerciale génèrent des besoins logistiques spécifiques.",
    logisticsContext: "Conflans est accessible depuis l'A15. Nos coursiers relient Conflans à Paris 17e en moins de 35 minutes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Conflans et les juridictions.",
      medical: "Transport inter-établissements de santé de Conflans.",
      ecommerce: "Livraisons pour les boutiques de Conflans.",
      corporate: "Navettes entre les entreprises de Conflans et leurs partenaires.",
      evenementiel: "Transport pour les événements de la batellerie.",
      grandsComptes: "Compte pour les opérateurs fluviaux et entreprises de Conflans.",
    },
    keyClients: ["Opérateurs fluviaux", "Port de Conflans", "PME", "Commerces"],
    distanceParis: "~35 min de Paris 17e",
    pricingZone: "devis",
    seoTitle: "Coursier Conflans-Sainte-Honorine — Port fluvial 78700 | ONE CONNEXION",
    seoDesc: "Coursier express à Conflans-Sainte-Honorine (78). Port fluvial, PME. Sur devis.",
    seoKeywords: ["coursier Conflans-Sainte-Honorine", "livraison express 78700", "coursier 78 Conflans"],
  }),
];
