import { makeZone } from "./factory";
import type { Zone } from "./types";

export const ZONES_77: Zone[] = [
  makeZone({
    slug: "melun",
    dept: "77000",
    name: "Melun",
    fullName: "Melun — Seine-et-Marne",
    category: "val-de-marne",
    landmarks: ["Préfecture 77", "Tribunal judiciaire de Melun", "Seine", "A5", "RER D"],
    intro: "Melun est la préfecture de la Seine-et-Marne. Elle concentre la Préfecture du 77, le Tribunal judiciaire, l'Hôpital de Melun et un tissu d'entreprises actif. C'est le principal centre administratif et judiciaire du sud de l'Île-de-France.",
    logisticsContext: "Melun est à 45 minutes de Paris 12e via l'A5. Nos coursiers desservent Melun pour les missions urgentes à destination ou en provenance de la Seine-et-Marne.",
    sectorExamples: {
      juridique: "Liaisons entre le Tribunal judiciaire de Melun et les cabinets d'avocats, dépôts de conclusions.",
      medical: "Transport de prélèvements depuis l'Hôpital de Melun vers les laboratoires de référence.",
      ecommerce: "Livraisons same-day pour les boutiques de Melun vers la région.",
      corporate: "Navettes entre les sièges d'entreprises de Melun et leurs partenaires parisiens.",
      evenementiel: "Transport pour les événements culturels et professionnels de Melun.",
      grandsComptes: "Compte pour la Préfecture 77 et les institutions judiciaires de Melun.",
    },
    keyClients: ["Tribunal de Melun", "Préfecture 77", "Hôpital de Melun", "PME 77"],
    distanceParis: "~45 min de Paris",
    pricingZone: "devis",
    seoTitle: "Coursier Melun — Tribunal, Préfecture 77 | ONE CONNEXION",
    seoDesc: "Coursier express à Melun (77). Tribunal, Préfecture, médical. Sur devis Seine-et-Marne.",
    seoKeywords: ["coursier Melun", "livraison express 77000", "coursier tribunal Melun", "coursier 77 Melun"],
  }),
  makeZone({
    slug: "meaux",
    dept: "77100",
    name: "Meaux",
    fullName: "Meaux — Seine-et-Marne",
    category: "val-de-marne",
    landmarks: ["Cathédrale de Meaux", "A140", "Marne", "Centre hospitalier de Meaux"],
    intro: "Meaux est une ville historique et économique du nord de la Seine-et-Marne. Centre régional de services, elle concentre un Hôpital, des entreprises agroalimentaires (moutarde de Meaux) et des services aux entreprises.",
    logisticsContext: "Meaux est à 45 minutes de Paris 20e. Nos coursiers desservent Meaux pour les missions B2B urgentes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Meaux et le Tribunal.",
      medical: "Transport depuis le Centre Hospitalier de Meaux vers les laboratoires.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants de Meaux.",
      corporate: "Navettes entre les entreprises de Meaux et leurs partenaires parisiens.",
      evenementiel: "Transport pour les événements de la cathédrale et les manifestations locales.",
      grandsComptes: "Compte pour le CH de Meaux et les grandes entreprises.",
    },
    keyClients: ["Centre Hospitalier de Meaux", "PME agroalimentaire", "Services"],
    distanceParis: "~45 min de Paris 20e",
    pricingZone: "devis",
    seoTitle: "Coursier Meaux — Centre hospitalier, 77100 | ONE CONNEXION",
    seoDesc: "Coursier express à Meaux (77). CH, PME, agroalimentaire. Sur devis Seine-et-Marne.",
    seoKeywords: ["coursier Meaux", "livraison express 77100", "coursier 77 Meaux"],
  }),
  makeZone({
    slug: "chelles",
    dept: "77500",
    name: "Chelles",
    fullName: "Chelles — Seine-et-Marne",
    category: "val-de-marne",
    landmarks: ["Marne", "A4", "RER E", "Vaires-sur-Marne"],
    intro: "Chelles est l'une des plus grandes villes de Seine-et-Marne, limitrophe du 93. Elle accueille un tissu dense de PME, de commerces et de professions libérales bien desservis par le RER E et l'A4.",
    logisticsContext: "Chelles est accessible depuis l'A4. Nos coursiers relient Chelles à Paris 20e en moins de 30 minutes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Chelles et les tribunaux de Bobigny et Meaux.",
      medical: "Transport inter-établissements de santé de Chelles.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants de Chelles.",
      corporate: "Navettes entre les PME de Chelles et leurs partenaires.",
      evenementiel: "Transport pour les événements locaux de Chelles.",
      grandsComptes: "Compte pour les PME et structures multi-sites de Chelles.",
    },
    keyClients: ["PME", "Professions libérales", "Commerces"],
    distanceParis: "~30 min de Paris 20e",
    pricingZone: "devis",
    seoTitle: "Coursier Chelles — Livraison express 77500 | ONE CONNEXION",
    seoDesc: "Coursier express à Chelles (77). PME, commerces, professions libérales. Sur devis 77.",
    seoKeywords: ["coursier Chelles", "livraison express 77500", "coursier 77 Chelles"],
  }),
  makeZone({
    slug: "torcy",
    dept: "77200",
    name: "Torcy",
    fullName: "Torcy — Seine-et-Marne",
    category: "val-de-marne",
    landmarks: ["Val d'Europe (proche)", "A4", "RER A", "Marne-la-Vallée"],
    intro: "Torcy est au cœur de Marne-la-Vallée et est desservie par le RER A. C'est un pôle économique important du 77 avec des zones d'activités, des bureaux et des centres commerciaux.",
    logisticsContext: "Torcy est accessible depuis l'A4. Nos coursiers relient Torcy à Paris 12e en moins de 35 minutes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Torcy et les juridictions.",
      medical: "Transport inter-établissements de santé de Torcy.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants de Torcy.",
      corporate: "Navettes entre les entreprises de Torcy et leurs partenaires.",
      evenementiel: "Transport pour les événements de Marne-la-Vallée.",
      grandsComptes: "Compte pour les entreprises de la zone Marne-la-Vallée.",
    },
    keyClients: ["Entreprises Marne-la-Vallée", "PME", "Commerces"],
    distanceParis: "~35 min de Paris 12e",
    pricingZone: "devis",
    seoTitle: "Coursier Torcy — Marne-la-Vallée, 77200 | ONE CONNEXION",
    seoDesc: "Coursier express à Torcy (77). Marne-la-Vallée, PME, zones d'activités. Sur devis 77.",
    seoKeywords: ["coursier Torcy", "livraison express 77200", "coursier Marne-la-Vallée Torcy", "coursier 77 Torcy"],
  }),
  makeZone({
    slug: "lagny-sur-marne",
    dept: "77400",
    name: "Lagny-sur-Marne",
    fullName: "Lagny-sur-Marne — Seine-et-Marne",
    category: "val-de-marne",
    landmarks: ["Marne", "A4", "RER E", "Chelles (limite)"],
    intro: "Lagny-sur-Marne est une ville historique de Seine-et-Marne sur les bords de Marne. Son tissu économique comprend des PME, des artisans et des commerces qui ont des besoins de livraison express réguliers.",
    logisticsContext: "Lagny est accessible depuis l'A4 et le RER E. Nos coursiers relient Lagny à Paris en moins de 35 minutes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Lagny et les tribunaux.",
      medical: "Transport inter-établissements de santé de Lagny.",
      ecommerce: "Livraisons pour les boutiques de Lagny.",
      corporate: "Navettes entre les PME de Lagny et leurs partenaires.",
      evenementiel: "Transport pour les événements locaux.",
      grandsComptes: "Compte pour les PME de Lagny-sur-Marne.",
    },
    keyClients: ["PME", "Artisans", "Commerces"],
    distanceParis: "~35 min de Paris 20e",
    pricingZone: "devis",
    seoTitle: "Coursier Lagny-sur-Marne — Livraison express 77400 | ONE CONNEXION",
    seoDesc: "Coursier express à Lagny-sur-Marne (77). PME, artisans. Sur devis 77.",
    seoKeywords: ["coursier Lagny-sur-Marne", "livraison express 77400", "coursier 77 Lagny"],
  }),
  makeZone({
    slug: "pontault-combault",
    dept: "77340",
    name: "Pontault-Combault",
    fullName: "Pontault-Combault — Seine-et-Marne",
    category: "val-de-marne",
    landmarks: ["Zone industrielle", "A4", "RER E", "Roissy-en-Brie (limite)"],
    intro: "Pontault-Combault est une ville de taille importante avec des zones industrielles et commerciales actives. Sa position sur l'A4 et le RER E en fait un pôle économique du 77 ouest.",
    logisticsContext: "Pontault-Combault est accessible depuis l'A4. Nos coursiers relient la ville à Paris 12e en moins de 35 minutes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Pontault et les juridictions.",
      medical: "Transport inter-établissements de santé de Pontault.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants de Pontault.",
      corporate: "Navettes entre les PME industrielles de Pontault et leurs partenaires.",
      evenementiel: "Transport pour les événements locaux.",
      grandsComptes: "Compte pour les PME des zones industrielles de Pontault.",
    },
    keyClients: ["Industriels", "PME", "Commerces"],
    distanceParis: "~35 min de Paris 12e",
    pricingZone: "devis",
    seoTitle: "Coursier Pontault-Combault — Zone industrielle 77340 | ONE CONNEXION",
    seoDesc: "Coursier express à Pontault-Combault (77). Industries, PME. Sur devis 77.",
    seoKeywords: ["coursier Pontault-Combault", "livraison express 77340", "coursier 77 Pontault"],
  }),
  makeZone({
    slug: "fontainebleau",
    dept: "77300",
    name: "Fontainebleau",
    fullName: "Fontainebleau — Seine-et-Marne",
    category: "val-de-marne",
    landmarks: ["Château de Fontainebleau", "Forêt de Fontainebleau", "INSEAD", "A6"],
    intro: "Fontainebleau est une ville de prestige, connue pour son château royal, sa forêt et l'INSEAD, l'une des meilleures business schools mondiales. Ce profil unique génère des besoins logistiques premium pour les institutions, les hôtels de luxe et les dirigeants.",
    logisticsContext: "Fontainebleau est à 60 minutes de Paris via l'A6. Nos coursiers effectuent des missions express Fontainebleau-Paris sur demande.",
    sectorExamples: {
      juridique: "Transport de documents entre les études de Fontainebleau et leurs partenaires parisiens.",
      medical: "Transport médical depuis le Centre Hospitalier de Fontainebleau.",
      ecommerce: "Livraisons premium pour les hôtels et boutiques de Fontainebleau.",
      corporate: "Navettes entre l'INSEAD et ses partenaires d'affaires.",
      evenementiel: "Transport de matériel pour les événements au château et à l'INSEAD.",
      grandsComptes: "Compte pour l'INSEAD et les hôtels de luxe de Fontainebleau.",
    },
    keyClients: ["INSEAD", "Château de Fontainebleau", "Hôtels luxe", "CH Fontainebleau"],
    distanceParis: "~60 min de Paris",
    pricingZone: "devis",
    seoTitle: "Coursier Fontainebleau — INSEAD, Château, 77300 | ONE CONNEXION",
    seoDesc: "Coursier express à Fontainebleau (77). INSEAD, Château, hôtels luxe. Sur devis Seine-et-Marne.",
    seoKeywords: ["coursier Fontainebleau", "livraison express 77300", "coursier INSEAD Fontainebleau", "coursier 77 Fontainebleau"],
  }),
];
