import { makeZone } from "./factory";
import type { Zone } from "./types";

export const ZONES_94: Zone[] = [
  makeZone({
    slug: "vitry-sur-seine",
    dept: "94400",
    name: "Vitry-sur-Seine",
    category: "val-de-marne",
    landmarks: ["MAC VAL", "Zone industrielle", "Seine", "A86", "Paris 13e (limite)"],
    intro: "Vitry-sur-Seine est la plus grande ville du Val-de-Marne. Elle accueille le MAC VAL, musée d'art contemporain, et une importante zone industrielle en bord de Seine. Sa proximité avec le 13e arrondissement et l'axe A86 en font une ville logistiquement stratégique.",
    logisticsContext: "Vitry est à 10 minutes de Paris 13e. L'A86 et la N305 permettent des liaisons rapides avec toute la petite couronne.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Vitry et les juridictions parisiennes.",
      medical: "Transport inter-établissements pour les structures de santé de Vitry.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants de Vitry.",
      corporate: "Navettes entre les entreprises industrielles de Vitry et leurs partenaires.",
      evenementiel: "Transport d'œuvres et de matériel pour le MAC VAL et les événements culturels.",
      grandsComptes: "Compte pour les grands industriels et le MAC VAL.",
    },
    keyClients: ["MAC VAL", "Zone industrielle Seine", "PME", "Industries chimiques"],
    distanceParis: "~10 min de Paris 13e",
    pricingZone: "standard",
    seoTitle: "Coursier Vitry-sur-Seine — MAC VAL, Zone industrielle 94400 | ONE CONNEXION",
    seoDesc: "Coursier express à Vitry-sur-Seine (94). Zone industrielle, MAC VAL, PME. Enlèvement < 45 min.",
    seoKeywords: ["coursier Vitry-sur-Seine", "livraison express 94400", "coursier 94 Vitry"],
  }),
  makeZone({
    slug: "alfortville",
    dept: "94140",
    name: "Alfortville",
    category: "val-de-marne",
    landmarks: ["Confluence Marne-Seine", "Maisons-Alfort (limite)", "A86", "Paris 12e (proche)"],
    intro: "Alfortville est une commune dynamique à la confluence de la Marne et de la Seine. Sa position géographique unique, entre Paris 12e et Maisons-Alfort, en fait un point de desserte logistique naturel pour le Val-de-Marne nord.",
    logisticsContext: "Alfortville est à 15 minutes de Paris 12e. Nos scooters desservent toute la ville rapidement depuis nos relais du 94.",
    sectorExamples: {
      juridique: "Transport entre les cabinets d'Alfortville et les juridictions de Créteil.",
      medical: "Transport inter-établissements de santé d'Alfortville.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants d'Alfortville.",
      corporate: "Navettes entre les PME d'Alfortville et leurs partenaires.",
      evenementiel: "Transport pour les événements locaux.",
      grandsComptes: "Compte pour les PME multi-sites d'Alfortville.",
    },
    keyClients: ["PME", "Commerces", "Professions libérales"],
    distanceParis: "~15 min de Paris 12e",
    pricingZone: "standard",
    seoTitle: "Coursier Alfortville — Livraison express 94140 | ONE CONNEXION",
    seoDesc: "Coursier express à Alfortville (94). PME, commerces, professions libérales. Enlèvement < 45 min.",
    seoKeywords: ["coursier Alfortville", "livraison express 94140", "coursier 94 Alfortville"],
  }),
  makeZone({
    slug: "maisons-alfort",
    dept: "94700",
    name: "Maisons-Alfort",
    category: "val-de-marne",
    landmarks: ["École Nationale Vétérinaire (ENVA)", "Hôpital Henri-Mondor (proche)", "Marne", "A86"],
    intro: "Maisons-Alfort abrite l'École Nationale Vétérinaire de Paris (ENVA), l'une des plus grandes d'Europe, ainsi qu'un tissu résidentiel et économique actif. Sa proximité avec Créteil et l'Hôpital Henri-Mondor en fait une zone médicale et scientifique importante.",
    logisticsContext: "Maisons-Alfort est accessible depuis l'A86. Nos coursiers relient la ville à Créteil et Paris 12e en moins de 20 minutes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Maisons-Alfort et le Tribunal de Créteil.",
      medical: "Transport de prélèvements vétérinaires et médicaux depuis l'ENVA et les cliniques.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants de Maisons-Alfort.",
      corporate: "Navettes entre les PME de Maisons-Alfort et leurs partenaires.",
      evenementiel: "Transport de matériel pour les événements académiques de l'ENVA.",
      grandsComptes: "Compte pour l'ENVA et les institutions de Maisons-Alfort.",
    },
    keyClients: ["ENVA", "Hôpital Henri-Mondor (proche)", "PME", "Cliniques vétérinaires"],
    distanceParis: "~20 min de Paris 12e",
    pricingZone: "standard",
    seoTitle: "Coursier Maisons-Alfort — ENVA, 94700 | ONE CONNEXION",
    seoDesc: "Coursier express à Maisons-Alfort (94). ENVA, médical, PME. Enlèvement < 45 min.",
    seoKeywords: ["coursier Maisons-Alfort", "livraison express 94700", "coursier ENVA Maisons-Alfort"],
  }),
  makeZone({
    slug: "charenton-le-pont",
    dept: "94220",
    name: "Charenton-le-Pont",
    category: "val-de-marne",
    landmarks: ["Paris 12e (limite)", "Bercy (limite)", "Marne", "A4", "Centre commercial"],
    intro: "Charenton-le-Pont est limitrophe du 12e arrondissement et de Bercy. Cette position exceptionnelle en fait l'une des villes du 94 les plus proches de Paris intramuros. Son tissu économique dense, avec des bureaux, des commerces et des entreprises de services, génère des besoins logistiques quotidiens.",
    logisticsContext: "Charenton est à 5 minutes de Paris 12e via le pont de Charenton. Nos scooters relient Charenton à Bercy et Bastille en moins de 15 minutes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Charenton et les tribunaux parisiens, limitrophie optimale.",
      medical: "Transport inter-établissements de santé de Charenton.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants de Charenton.",
      corporate: "Navettes entre les entreprises de Charenton et leurs partenaires parisiens.",
      evenementiel: "Transport pour les événements corporate de Charenton.",
      grandsComptes: "Compte pour les entreprises de services de Charenton.",
    },
    keyClients: ["Entreprises services", "Commerces", "PME", "Professions libérales"],
    distanceParis: "~5 min de Paris 12e",
    pricingZone: "standard",
    seoTitle: "Coursier Charenton-le-Pont — Livraison express 94220 | ONE CONNEXION",
    seoDesc: "Coursier express à Charenton-le-Pont (94). Limitrophe Paris 12e, PME, services. Enlèvement < 45 min.",
    seoKeywords: ["coursier Charenton-le-Pont", "livraison express 94220", "coursier 94 Charenton"],
  }),
  makeZone({
    slug: "saint-maurice",
    dept: "94410",
    name: "Saint-Maurice",
    category: "val-de-marne",
    landmarks: ["Hôpital National de Saint-Maurice", "Marne", "Saint-Mandé (limite)", "Charenton (limite)"],
    intro: "Saint-Maurice abrite l'Hôpital National de Saint-Maurice, établissement spécialisé en soins de suite et rééducation. Sa proximité avec notre siège de Saint-Mandé nous permet d'y intervenir en moins de 10 minutes.",
    logisticsContext: "Saint-Maurice est à 5 minutes de notre siège de Saint-Mandé. C'est l'une des zones où nos délais d'intervention sont les plus courts.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Saint-Maurice et les juridictions.",
      medical: "Transport urgent depuis l'Hôpital National de Saint-Maurice vers les laboratoires partenaires.",
      ecommerce: "Livraisons pour les boutiques et résidences de Saint-Maurice.",
      corporate: "Navettes entre les entreprises de Saint-Maurice et leurs partenaires.",
      evenementiel: "Transport pour les événements locaux.",
      grandsComptes: "Compte pour l'Hôpital National et les structures de Saint-Maurice.",
    },
    keyClients: ["Hôpital National de Saint-Maurice", "PME", "Résidences"],
    distanceParis: "~10 min de Paris 12e",
    pricingZone: "standard",
    seoTitle: "Coursier Saint-Maurice — Hôpital National, 94410 | ONE CONNEXION",
    seoDesc: "Coursier express à Saint-Maurice (94). Hôpital National, transport médical urgent. Enlèvement < 15 min (siège One Connexion).",
    seoKeywords: ["coursier Saint-Maurice 94", "livraison express 94410", "coursier hôpital Saint-Maurice"],
  }),
  makeZone({
    slug: "joinville-le-pont",
    dept: "94340",
    name: "Joinville-le-Pont",
    category: "val-de-marne",
    landmarks: ["Marne", "Base nautique", "A4", "Nogent-sur-Marne (limite)"],
    intro: "Joinville-le-Pont est une ville résidentielle de prestige sur les bords de Marne, entre Paris et Nogent. Son tissu économique mêle professions libérales, agences et PME de services dans un cadre de qualité.",
    logisticsContext: "Joinville est accessible depuis l'A4. Nos coursiers relient Joinville à Paris 12e en moins de 20 minutes.",
    sectorExamples: {
      juridique: "Transport entre les études notariales de Joinville et les juridictions.",
      medical: "Transport inter-établissements de santé de Joinville.",
      ecommerce: "Livraisons premium pour les boutiques et résidences de Joinville.",
      corporate: "Navettes entre les PME et agences de Joinville et leurs clients.",
      evenementiel: "Transport pour les événements sportifs et culturels des bords de Marne.",
      grandsComptes: "Compte pour les PME et professions libérales de Joinville.",
    },
    keyClients: ["Professions libérales", "Études notariales", "Agences", "Résidences prestige"],
    distanceParis: "~20 min de Paris 12e",
    pricingZone: "standard",
    seoTitle: "Coursier Joinville-le-Pont — Marne, 94340 | ONE CONNEXION",
    seoDesc: "Coursier express à Joinville-le-Pont (94). Bords de Marne, professions libérales. Enlèvement < 45 min.",
    seoKeywords: ["coursier Joinville-le-Pont", "livraison express 94340", "coursier 94 Joinville"],
  }),
  makeZone({
    slug: "nogent-sur-marne",
    dept: "94130",
    name: "Nogent-sur-Marne",
    category: "val-de-marne",
    landmarks: ["Marne", "Bois de Vincennes (limite)", "A4", "Joinville (limite)"],
    intro: "Nogent-sur-Marne est une ville résidentielle et économique active sur les bords de Marne, aux portes du bois de Vincennes. Cabinets médicaux, études notariales et PME de services y concentrent une activité B2B régulière.",
    logisticsContext: "Nogent est accessible depuis l'A4. Nos coursiers relient Nogent à Paris 12e en moins de 20 minutes.",
    sectorExamples: {
      juridique: "Transport entre les études de Nogent et les juridictions parisiennes.",
      medical: "Transport inter-établissements de santé de Nogent.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants de Nogent.",
      corporate: "Navettes entre les PME de Nogent et leurs clients.",
      evenementiel: "Transport pour les événements des bords de Marne.",
      grandsComptes: "Compte pour les PME et professions libérales de Nogent.",
    },
    keyClients: ["Professions libérales", "Études notariales", "Cliniques", "PME"],
    distanceParis: "~20 min de Paris 12e",
    pricingZone: "standard",
    seoTitle: "Coursier Nogent-sur-Marne — Livraison express 94130 | ONE CONNEXION",
    seoDesc: "Coursier express à Nogent-sur-Marne (94). Professions libérales, médical. Enlèvement < 45 min.",
    seoKeywords: ["coursier Nogent-sur-Marne", "livraison express 94130", "coursier 94 Nogent"],
  }),
  makeZone({
    slug: "le-perreux-sur-marne",
    dept: "94170",
    name: "Le Perreux-sur-Marne",
    category: "val-de-marne",
    landmarks: ["Marne", "Nogent (limite)", "Bry (limite)", "A4"],
    intro: "Le Perreux-sur-Marne est une ville résidentielle de qualité sur les bords de Marne. Professions libérales et PME de services constituent l'essentiel de son tissu économique.",
    logisticsContext: "Le Perreux est accessible depuis l'A4. Nos coursiers relient Le Perreux à Paris 12e en moins de 25 minutes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets du Perreux et les juridictions.",
      medical: "Transport inter-établissements de santé du Perreux.",
      ecommerce: "Livraisons pour les boutiques du Perreux.",
      corporate: "Navettes entre les PME du Perreux et leurs partenaires.",
      evenementiel: "Transport pour les événements locaux.",
      grandsComptes: "Compte pour les professions libérales et PME du Perreux.",
    },
    keyClients: ["Professions libérales", "PME services", "Cliniques"],
    distanceParis: "~25 min de Paris 12e",
    pricingZone: "standard",
    seoTitle: "Coursier Le Perreux-sur-Marne — 94170 | ONE CONNEXION",
    seoDesc: "Coursier express au Perreux-sur-Marne (94). PME, professions libérales. Enlèvement < 45 min.",
    seoKeywords: ["coursier Le Perreux-sur-Marne", "livraison express 94170", "coursier 94 Perreux"],
  }),
  makeZone({
    slug: "fontenay-sous-bois",
    dept: "94120",
    name: "Fontenay-sous-Bois",
    category: "val-de-marne",
    landmarks: ["Bois de Vincennes (limite)", "RER A", "A86", "Vincennes (limite)"],
    intro: "Fontenay-sous-Bois est une ville résidentielle active aux portes du bois de Vincennes. Son tissu économique comprend des PME, des cabinets médicaux et des agences, bien desservis par le RER A.",
    logisticsContext: "Fontenay est accessible depuis l'A86 et la Porte de Vincennes. Nos coursiers relient Fontenay à Paris 12e en moins de 20 minutes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Fontenay et les juridictions parisiennes.",
      medical: "Transport inter-établissements de santé de Fontenay.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants de Fontenay.",
      corporate: "Navettes entre les PME de Fontenay et leurs partenaires.",
      evenementiel: "Transport pour les événements locaux.",
      grandsComptes: "Compte pour les PME multi-sites de Fontenay.",
    },
    keyClients: ["PME", "Cabinets médicaux", "Agences", "Commerces"],
    distanceParis: "~15 min de Paris 12e",
    pricingZone: "standard",
    seoTitle: "Coursier Fontenay-sous-Bois — Livraison express 94120 | ONE CONNEXION",
    seoDesc: "Coursier express à Fontenay-sous-Bois (94). PME, médical, agences. Enlèvement < 45 min.",
    seoKeywords: ["coursier Fontenay-sous-Bois", "livraison express 94120", "coursier 94 Fontenay"],
  }),
  makeZone({
    slug: "saint-maur-des-fosses",
    dept: "94100",
    name: "Saint-Maur-des-Fossés",
    category: "val-de-marne",
    landmarks: ["Marne (méandre)", "A4", "La Varenne", "Chennevières (limite)"],
    intro: "Saint-Maur-des-Fossés est l'une des villes les plus peuplées du Val-de-Marne. Son méandre de Marne crée une topographie unique. Professions libérales, cabinets médicaux et PME y sont nombreux, dans un cadre résidentiel de qualité.",
    logisticsContext: "Saint-Maur est accessible depuis l'A4. Nos coursiers couvrent tous les quartiers (La Varenne, Le Parc, Saint-Maur centre) en moins de 30 minutes.",
    sectorExamples: {
      juridique: "Transport entre les études notariales de Saint-Maur et les juridictions.",
      medical: "Transport entre les nombreux cabinets médicaux et cliniques de Saint-Maur.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants de Saint-Maur.",
      corporate: "Navettes entre les PME de Saint-Maur et leurs partenaires parisiens.",
      evenementiel: "Transport pour les événements sportifs et culturels de Saint-Maur.",
      grandsComptes: "Compte pour les PME et professions libérales de Saint-Maur.",
    },
    keyClients: ["Professions libérales", "Études notariales", "Cliniques privées", "PME"],
    distanceParis: "~25 min de Paris 12e",
    pricingZone: "standard",
    seoTitle: "Coursier Saint-Maur-des-Fossés — Marne, 94100 | ONE CONNEXION",
    seoDesc: "Coursier express à Saint-Maur-des-Fossés (94). Professions libérales, médical, PME. Enlèvement < 45 min.",
    seoKeywords: ["coursier Saint-Maur-des-Fossés", "livraison express 94100", "coursier 94 Saint-Maur"],
  }),
  makeZone({
    slug: "champigny-sur-marne",
    dept: "94500",
    name: "Champigny-sur-Marne",
    category: "val-de-marne",
    landmarks: ["Marne", "A4", "Zone industrielle", "Chennevières (limite)"],
    intro: "Champigny-sur-Marne est une grande ville du 94, mêlant zones industrielles en bord de Marne et tissu résidentiel dense. Son dynamisme économique et sa position sur l'A4 en font un point logistique important pour l'est du Val-de-Marne.",
    logisticsContext: "Champigny est accessible depuis l'A4. Nos coursiers relient Champigny à Paris 12e en moins de 25 minutes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Champigny et les tribunaux de Créteil.",
      medical: "Transport inter-établissements de santé de Champigny.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants de Champigny.",
      corporate: "Navettes entre les entreprises industrielles de Champigny et leurs partenaires.",
      evenementiel: "Transport pour les événements locaux.",
      grandsComptes: "Compte pour les industriels et PME de Champigny.",
    },
    keyClients: ["Industriels Marne", "PME", "Commerces", "Services"],
    distanceParis: "~25 min de Paris 12e",
    pricingZone: "standard",
    seoTitle: "Coursier Champigny-sur-Marne — Livraison express 94500 | ONE CONNEXION",
    seoDesc: "Coursier express à Champigny-sur-Marne (94). Industries, PME, commerces. Enlèvement < 45 min.",
    seoKeywords: ["coursier Champigny-sur-Marne", "livraison express 94500", "coursier 94 Champigny"],
  }),
  makeZone({
    slug: "villejuif",
    dept: "94800",
    name: "Villejuif",
    category: "val-de-marne",
    landmarks: ["Institut Gustave-Roussy", "Hôpital Paul-Brousse", "A6", "Paris 13e (limite)"],
    intro: "Villejuif est la capitale mondiale de l'oncologie. L'Institut Gustave-Roussy, premier centre anti-cancer d'Europe, et l'Hôpital Paul-Brousse en font l'un des pôles médicaux les plus importants d'Île-de-France. One Connexion y assure des liaisons médicales critiques quotidiennes.",
    logisticsContext: "Villejuif est à 10 minutes de Paris 13e via l'A6. Nos coursiers connaissent les accès à l'IGR et à Paul-Brousse, garantissant des livraisons médicales sans délai.",
    sectorExamples: {
      juridique: "Transport de documents entre les institutions médicales de Villejuif et leurs conseils juridiques.",
      medical: "Transport de prélèvements oncologiques entre l'Institut Gustave-Roussy et les laboratoires partenaires, ou de médicaments urgents entre établissements.",
      ecommerce: "Livraisons pour les boutiques et commerces de Villejuif.",
      corporate: "Navettes entre les directions administratives des hôpitaux et leurs partenaires.",
      evenementiel: "Transport de matériel pour les congrès médicaux à l'IGR.",
      grandsComptes: "Compte pour l'Institut Gustave-Roussy et l'Hôpital Paul-Brousse.",
    },
    keyClients: ["Institut Gustave-Roussy", "Hôpital Paul-Brousse", "Laboratoires oncologie", "Cliniques Villejuif"],
    distanceParis: "~10 min de Paris 13e",
    pricingZone: "standard",
    seoTitle: "Coursier Villejuif — Institut Gustave-Roussy, Paul-Brousse 94800 | ONE CONNEXION",
    seoDesc: "Coursier express à Villejuif (94). Institut Gustave-Roussy, Paul-Brousse, transport médical oncologie. Enlèvement < 45 min.",
    seoKeywords: ["coursier Villejuif", "livraison express 94800", "coursier Gustave-Roussy Villejuif", "coursier médical oncologie 94"],
  }),
  makeZone({
    slug: "gentilly",
    dept: "94250",
    name: "Gentilly",
    category: "val-de-marne",
    landmarks: ["Paris 13e (limite)", "Périphérique", "A6", "Kremlin-Bicêtre (limite)"],
    intro: "Gentilly est limitrophe du 13e arrondissement, directement accessible depuis le périphérique. Sa position de porte d'entrée du Val-de-Marne en fait une ville de transit et de services B2B active.",
    logisticsContext: "Gentilly est à 5 minutes de Paris 13e. C'est l'une des villes du 94 les plus proches de Paris intramuros.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Gentilly et les juridictions parisiennes.",
      medical: "Transport inter-établissements de santé de Gentilly.",
      ecommerce: "Livraisons pour les boutiques de Gentilly.",
      corporate: "Navettes entre les entreprises de Gentilly et leurs partenaires parisiens.",
      evenementiel: "Transport pour les événements locaux.",
      grandsComptes: "Compte pour les PME et structures de Gentilly.",
    },
    keyClients: ["PME", "Commerces", "Professions libérales"],
    distanceParis: "~5 min de Paris 13e",
    pricingZone: "standard",
    seoTitle: "Coursier Gentilly — Livraison express 94250 | ONE CONNEXION",
    seoDesc: "Coursier express à Gentilly (94). Limitrophe Paris 13e, PME. Enlèvement < 45 min.",
    seoKeywords: ["coursier Gentilly", "livraison express 94250", "coursier 94 Gentilly"],
  }),
  makeZone({
    slug: "arcueil",
    dept: "94110",
    name: "Arcueil",
    category: "val-de-marne",
    landmarks: ["Paris 14e (limite)", "INRIA (proche)", "A6", "Cachan (limite)"],
    intro: "Arcueil est limitrophe du 14e arrondissement et accueille des entreprises technologiques et de R&D. Sa proximité avec l'INRIA de Saclay et les campus universitaires en fait une ville à fort contenu scientifique.",
    logisticsContext: "Arcueil est à 5 minutes de Paris 14e. Nos scooters relient Arcueil à Montparnasse en moins de 15 minutes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets d'Arcueil et les juridictions parisiennes.",
      medical: "Transport inter-établissements de santé d'Arcueil.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants d'Arcueil.",
      corporate: "Navettes entre les entreprises tech d'Arcueil et leurs partenaires.",
      evenementiel: "Transport pour les événements scientifiques locaux.",
      grandsComptes: "Compte pour les entreprises tech et R&D d'Arcueil.",
    },
    keyClients: ["Entreprises tech & R&D", "PME", "Professions libérales"],
    distanceParis: "~5 min de Paris 14e",
    pricingZone: "standard",
    seoTitle: "Coursier Arcueil — Tech & R&D, 94110 | ONE CONNEXION",
    seoDesc: "Coursier express à Arcueil (94). Tech, R&D, PME. Limitrophe Paris 14e. Enlèvement < 45 min.",
    seoKeywords: ["coursier Arcueil", "livraison express 94110", "coursier 94 Arcueil"],
  }),
  makeZone({
    slug: "cachan",
    dept: "94230",
    name: "Cachan",
    category: "val-de-marne",
    landmarks: ["ENS Paris-Saclay (ex-Cachan)", "Arcueil (limite)", "A6", "Bagneux (92, limite)"],
    intro: "Cachan a longtemps abrité l'ENS Cachan (aujourd'hui ENS Paris-Saclay). Ce passé académique a laissé un tissu d'entreprises technologiques et de formation. Sa position sur l'A6 en fait un nœud logistique du sud de la petite couronne.",
    logisticsContext: "Cachan est accessible depuis l'A6. Nos coursiers relient Cachan à Paris 14e en moins de 20 minutes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Cachan et les juridictions.",
      medical: "Transport inter-établissements de santé de Cachan.",
      ecommerce: "Livraisons pour les boutiques de Cachan.",
      corporate: "Navettes entre les PME tech de Cachan et leurs partenaires.",
      evenementiel: "Transport pour les événements académiques locaux.",
      grandsComptes: "Compte pour les PME et institutions de Cachan.",
    },
    keyClients: ["Entreprises tech", "PME", "Centres de formation"],
    distanceParis: "~15 min de Paris 14e",
    pricingZone: "standard",
    seoTitle: "Coursier Cachan — Livraison express 94230 | ONE CONNEXION",
    seoDesc: "Coursier express à Cachan (94). Tech, PME, formation. Enlèvement < 45 min.",
    seoKeywords: ["coursier Cachan", "livraison express 94230", "coursier 94 Cachan"],
  }),
  makeZone({
    slug: "rungis",
    dept: "94150",
    name: "Rungis",
    category: "val-de-marne",
    landmarks: ["Marché International de Rungis (MIN)", "A86", "A6", "Orly (proche)"],
    intro: "Rungis abrite le Marché International de Rungis, le plus grand marché de produits frais au monde. Ce géant logistique génère des besoins de transport B2B ultra-urgents dès l'aube, et One Connexion y intervient régulièrement pour des missions express entre le MIN et ses clients professionnels.",
    logisticsContext: "Rungis est à 20 minutes de Paris 13e via l'A6. Nos coursiers interviennent sur le MIN avec des départs dès 5h du matin sur demande.",
    sectorExamples: {
      juridique: "Transport de contrats et documents entre les grossistes du MIN et leurs conseils.",
      medical: "Transport de produits alimentaires diététiques et médicaux depuis le MIN.",
      ecommerce: "Livraisons urgentes de produits depuis le MIN vers les restaurants et traiteurs parisiens.",
      corporate: "Navettes entre les directions du MIN et leurs partenaires logistiques.",
      evenementiel: "Transport de denrées et matériel pour les événements traiteurs premium.",
      grandsComptes: "Compte pour les grossistes et importateurs du MIN de Rungis.",
    },
    keyClients: ["MIN de Rungis", "Grossistes alimentaires", "Importateurs", "Traiteurs premium"],
    distanceParis: "~20 min de Paris 13e",
    pricingZone: "standard",
    seoTitle: "Coursier Rungis — MIN, Marché International 94150 | ONE CONNEXION",
    seoDesc: "Coursier express à Rungis (94). MIN, marché international, grossistes. Enlèvement < 45 min.",
    seoKeywords: ["coursier Rungis", "livraison express 94150", "coursier MIN Rungis", "coursier marché Rungis"],
  }),
  makeZone({
    slug: "orly",
    dept: "94310",
    name: "Orly",
    category: "val-de-marne",
    landmarks: ["Aéroport de Paris-Orly", "A86", "A106", "Rungis (limite)"],
    intro: "Orly est dominée par son aéroport international, deuxième plateforme aérienne de France. Les zones d'activités aéroportuaires, les entrepôts fret et les entreprises de services générés autour d'Orly créent des besoins logistiques express permanents.",
    logisticsContext: "Orly est accessible depuis l'A86 et l'A106. Nos motos routières relient Orly à Paris 13e en moins de 25 minutes.",
    sectorExamples: {
      juridique: "Transport de contrats entre les opérateurs aéroportuaires et leurs conseils juridiques.",
      medical: "Transport de médicaments et matériel médical urgent depuis et vers Orly.",
      ecommerce: "Livraisons express depuis Orly pour les e-commerçants à flux tendu.",
      corporate: "Navettes entre les directions générales des compagnies et des prestataires aéroportuaires.",
      evenementiel: "Transport de matériel pour les événements des hôtels d'aéroport.",
      grandsComptes: "Compte pour les opérateurs aéroportuaires et les grands groupes de la zone.",
    },
    keyClients: ["Aéroport Paris-Orly", "Compagnies aériennes", "Entrepôts fret", "Hôtels aéroport"],
    distanceParis: "~25 min de Paris 13e",
    pricingZone: "standard",
    seoTitle: "Coursier Orly — Aéroport Paris-Orly, 94310 | ONE CONNEXION",
    seoDesc: "Coursier express à Orly (94). Aéroport Paris-Orly, fret, zone aéroportuaire. Enlèvement < 45 min.",
    seoKeywords: ["coursier Orly", "livraison express 94310", "coursier aéroport Orly", "coursier 94 Orly"],
  }),
  makeZone({
    slug: "chevilly-larue",
    dept: "94550",
    name: "Chevilly-Larue",
    category: "val-de-marne",
    landmarks: ["MIN de Rungis (limite)", "A86", "A6", "Thiais (limite)"],
    intro: "Chevilly-Larue jouxte le MIN de Rungis et accueille des entrepôts logistiques et des entreprises de la filière alimentaire. Sa position sur l'A86 et l'A6 en fait un nœud de distribution important.",
    logisticsContext: "Chevilly-Larue est accessible depuis l'A86. Nos coursiers relient la ville à Paris et au MIN en moins de 20 minutes.",
    sectorExamples: {
      juridique: "Transport entre les entreprises de Chevilly et leurs conseils juridiques.",
      medical: "Transport de produits médicaux et diététiques depuis les entrepôts.",
      ecommerce: "Livraisons pour les e-commerçants de la zone logistique.",
      corporate: "Navettes entre les entrepôts de Chevilly et leurs clients distributeurs.",
      evenementiel: "Transport de denrées et matériel pour les événements traiteurs.",
      grandsComptes: "Compte pour les logisticiens et distributeurs de Chevilly-Larue.",
    },
    keyClients: ["Entrepôts logistiques", "Distributeurs alimentaires", "PME"],
    distanceParis: "~20 min de Paris 13e",
    pricingZone: "standard",
    seoTitle: "Coursier Chevilly-Larue — Zone logistique Rungis 94550 | ONE CONNEXION",
    seoDesc: "Coursier express à Chevilly-Larue (94). Zone Rungis, logistique, distribution. Enlèvement < 45 min.",
    seoKeywords: ["coursier Chevilly-Larue", "livraison express 94550", "coursier 94 Chevilly"],
  }),
  makeZone({
    slug: "lhay-les-roses",
    dept: "94240",
    name: "L'Haÿ-les-Roses",
    category: "val-de-marne",
    landmarks: ["Roseraie de L'Haÿ-les-Roses", "A6", "Fresnes (limite)", "Villejuif (limite)"],
    intro: "L'Haÿ-les-Roses est une commune résidentielle et économique du sud du Val-de-Marne, connue pour sa célèbre roseraie. Son tissu d'entreprises et de professions libérales génère des besoins logistiques B2B réguliers.",
    logisticsContext: "L'Haÿ-les-Roses est accessible depuis l'A6. Nos coursiers relient la ville à Paris 13e en moins de 20 minutes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de L'Haÿ et les tribunaux.",
      medical: "Transport inter-établissements de santé de L'Haÿ-les-Roses.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants locaux.",
      corporate: "Navettes entre les PME de L'Haÿ et leurs partenaires.",
      evenementiel: "Transport pour les événements de la roseraie et les manifestations locales.",
      grandsComptes: "Compte pour les PME multi-sites de L'Haÿ-les-Roses.",
    },
    keyClients: ["PME", "Professions libérales", "Cliniques"],
    distanceParis: "~20 min de Paris 13e",
    pricingZone: "standard",
    seoTitle: "Coursier L'Haÿ-les-Roses — Livraison express 94240 | ONE CONNEXION",
    seoDesc: "Coursier express à L'Haÿ-les-Roses (94). PME, professions libérales. Enlèvement < 45 min.",
    seoKeywords: ["coursier L'Haÿ-les-Roses", "livraison express 94240", "coursier 94 Haÿ-les-Roses"],
  }),
  makeZone({
    slug: "fresnes",
    dept: "94260",
    name: "Fresnes",
    category: "val-de-marne",
    landmarks: ["Centre Hospitalier de Fresnes", "Prison de Fresnes", "A86", "L'Haÿ (limite)"],
    intro: "Fresnes abrite le Centre Hospitalier de Fresnes (CHSF), établissement spécialisé en médecine pénitentiaire, et un tissu économique composé de PME et de professions libérales. Sa position sur l'A86 facilite les liaisons avec toute la petite couronne sud.",
    logisticsContext: "Fresnes est accessible depuis l'A86. Nos coursiers relient Fresnes à Paris 14e en moins de 25 minutes.",
    sectorExamples: {
      juridique: "Transport de documents entre le CHSF et les juridictions.",
      medical: "Transport médical depuis le CHSF et les établissements de santé de Fresnes.",
      ecommerce: "Livraisons pour les boutiques de Fresnes.",
      corporate: "Navettes entre les PME de Fresnes et leurs partenaires.",
      evenementiel: "Transport pour les événements locaux.",
      grandsComptes: "Compte pour le CHSF et les institutions de Fresnes.",
    },
    keyClients: ["CHSF", "PME", "Professions libérales"],
    distanceParis: "~25 min de Paris 14e",
    pricingZone: "standard",
    seoTitle: "Coursier Fresnes — CHSF, 94260 | ONE CONNEXION",
    seoDesc: "Coursier express à Fresnes (94). CHSF, médical, PME. Enlèvement < 45 min.",
    seoKeywords: ["coursier Fresnes", "livraison express 94260", "coursier 94 Fresnes"],
  }),
  makeZone({
    slug: "thiais",
    dept: "94320",
    name: "Thiais",
    category: "val-de-marne",
    landmarks: ["Belle Épine (centre commercial)", "Marché de Rungis (proche)", "A86", "Orly (proche)"],
    intro: "Thiais accueille le centre commercial Belle Épine et jouxte le MIN de Rungis. Cette double vocation commerciale et logistique en fait une ville très active pour les livraisons B2B et last-mile.",
    logisticsContext: "Thiais est accessible depuis l'A86. Nos coursiers desservent Belle Épine et les zones logistiques en moins de 25 minutes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Thiais et les juridictions.",
      medical: "Transport inter-établissements de santé de Thiais.",
      ecommerce: "Livraisons pour Belle Épine et les e-commerçants de Thiais.",
      corporate: "Navettes entre les entreprises de Thiais et leurs partenaires.",
      evenementiel: "Transport de matériel pour les événements de Belle Épine.",
      grandsComptes: "Compte pour les enseignes de Belle Épine et les logisticiens de Thiais.",
    },
    keyClients: ["Belle Épine", "Enseignes retail", "Logisticiens Rungis", "PME"],
    distanceParis: "~25 min de Paris 13e",
    pricingZone: "standard",
    seoTitle: "Coursier Thiais — Belle Épine, Rungis 94320 | ONE CONNEXION",
    seoDesc: "Coursier express à Thiais (94). Belle Épine, Rungis, retail, logistique. Enlèvement < 45 min.",
    seoKeywords: ["coursier Thiais", "livraison express 94320", "coursier Belle Épine Thiais"],
  }),
];
