import { makeZone } from "./factory";
import type { Zone } from "./types";

export const ZONES_92: Zone[] = [
  makeZone({
    slug: "nanterre",
    dept: "92000",
    name: "Nanterre",
    category: "hauts-de-seine",
    landmarks: ["La Défense", "Tribunal judiciaire de Nanterre", "Université Paris-Nanterre", "A86", "RER A"],
    intro: "Nanterre est la ville-préfecture des Hauts-de-Seine et accueille le Tribunal judiciaire de Nanterre, l'une des juridictions les plus importantes d'Île-de-France. La Défense, son quartier d'affaires international, concentre les directions générales des plus grands groupes mondiaux.",
    logisticsContext: "Nanterre est à 15 minutes de Paris 17e via l'A14. La Défense génère un trafic dense aux heures de bureau. Nos scooters empruntent les voies réservées et les accès underground pour livrer dans les tours sans délai.",
    sectorExamples: {
      juridique: "Liaisons entre le Tribunal judiciaire de Nanterre et les cabinets d'avocats des tours de La Défense et de Paris.",
      medical: "Transport de prélèvements entre les établissements de santé de Nanterre et les laboratoires de référence.",
      ecommerce: "Livraisons same-day pour les boutiques et e-commerçants du centre-ville de Nanterre.",
      corporate: "Navettes urgentes entre les directions générales des tours de La Défense (Total, KPMG, Société Générale) et leurs partenaires.",
      evenementiel: "Transport de matériel pour les congrès et événements au CNIT de La Défense.",
      grandsComptes: "Compte entreprise pour les grands groupes du CAC 40 installés à La Défense avec imputation par direction.",
    },
    keyClients: ["Tribunal de Nanterre", "Grands groupes La Défense", "CNIT", "Université Paris-Nanterre"],
    distanceParis: "~15 min de Paris 17e",
    pricingZone: "standard",
    seoTitle: "Coursier Nanterre — La Défense, Tribunal judiciaire 92 | ONE CONNEXION",
    seoDesc: "Coursier express à Nanterre (92). Tribunal de Nanterre, La Défense, grands groupes. Plis confidentiels, course dédiée. Enlèvement < 45 min.",
    seoKeywords: ["coursier Nanterre", "livraison express 92000", "coursier La Défense", "coursier tribunal Nanterre"],
  }),
  makeZone({
    slug: "courbevoie",
    dept: "92400",
    name: "Courbevoie",
    category: "hauts-de-seine",
    landmarks: ["La Défense", "Charras", "Faubourg de l'Arche", "A86", "Seine"],
    intro: "Courbevoie est au cœur du quartier d'affaires de La Défense. EDF, Schneider Electric, Bouygues et de nombreux sièges de multinationales y sont installés. Les besoins en transport urgent B2B sont parmi les plus élevés d'Île-de-France.",
    logisticsContext: "Courbevoie borde La Défense et son réseau de tours. Nos coursiers connaissent les accès piétonniers aux socles des tours et les parkings sous-terrain des grandes entreprises.",
    sectorExamples: {
      juridique: "Transport de contrats entre les directions juridiques des multinationales de Courbevoie et leurs cabinets conseil parisiens.",
      medical: "Transport entre la clinique de Courbevoie et les laboratoires partenaires.",
      ecommerce: "Livraisons pour les commerces et boutiques du Faubourg de l'Arche.",
      corporate: "Navettes entre EDF, Schneider Electric, Bouygues et leurs sous-traitants et partenaires.",
      evenementiel: "Livraisons de matériel pour les événements corporate des grands groupes de Courbevoie.",
      grandsComptes: "Comptes mensuels pour les multinationales de Courbevoie avec imputation par business unit.",
    },
    keyClients: ["EDF", "Schneider Electric", "Bouygues", "Sièges multinationales La Défense"],
    distanceParis: "~15 min de Paris 17e",
    pricingZone: "standard",
    seoTitle: "Coursier Courbevoie — EDF, Schneider Electric, La Défense 92 | ONE CONNEXION",
    seoDesc: "Coursier express à Courbevoie (92). EDF, Schneider Electric, sièges La Défense. Course dédiée, enlèvement < 45 min.",
    seoKeywords: ["coursier Courbevoie", "livraison express 92400", "coursier La Défense Courbevoie"],
  }),
  makeZone({
    slug: "puteaux",
    dept: "92800",
    name: "Puteaux",
    category: "hauts-de-seine",
    landmarks: ["La Défense", "CNIT", "Grande Arche", "Île de la Jatte", "A14"],
    intro: "Puteaux est la troisième ville de La Défense et accueille la Grande Arche ainsi que le CNIT, salle d'exposition et de congrès. Des dizaines de sièges sociaux y sont regroupés, générant des flux logistiques constants entre les tours et le reste de l'Île-de-France.",
    logisticsContext: "Puteaux est accessible depuis la A14 et le boulevard circulaire de La Défense. Nos motos accèdent aux socles des tours et aux quais de livraison professionnels sans délai.",
    sectorExamples: {
      juridique: "Liaisons entre les directions juridiques installées sous la Grande Arche et les juridictions parisiennes.",
      medical: "Transport médical urgent entre les établissements de santé de Puteaux et leurs partenaires.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants de Puteaux.",
      corporate: "Navettes entre les sièges de Puteaux (Saint-Gobain, Dassault Systèmes) et leurs partenaires.",
      evenementiel: "Transport de matériel pour les salons et congrès au CNIT.",
      grandsComptes: "Compte pour Saint-Gobain, Dassault Systèmes et les grands groupes de Puteaux.",
    },
    keyClients: ["Grande Arche", "CNIT", "Saint-Gobain", "Dassault Systèmes"],
    distanceParis: "~15 min de Paris 16e",
    pricingZone: "standard",
    seoTitle: "Coursier Puteaux — Grande Arche, CNIT, La Défense 92 | ONE CONNEXION",
    seoDesc: "Coursier express à Puteaux (92). Grande Arche, CNIT, sièges sociaux. Enlèvement < 45 min.",
    seoKeywords: ["coursier Puteaux", "livraison express 92800", "coursier CNIT Puteaux"],
  }),
  makeZone({
    slug: "suresnes",
    dept: "92150",
    name: "Suresnes",
    category: "hauts-de-seine",
    landmarks: ["Mont Valérien", "Hippodrome de Saint-Cloud", "Seine", "Hôpital Foch", "A13"],
    intro: "Suresnes est une ville résidentielle et hospitalière. L'Hôpital Foch est un établissement de référence nationale en transplantation. De nombreuses PME et sièges régionaux y sont établis, entre mont Valérien et les bords de Seine.",
    logisticsContext: "Suresnes est accessible depuis la A13 et la D907. Nos scooters relient Suresnes à Paris 16e en moins de 20 minutes.",
    sectorExamples: {
      juridique: "Transport de documents entre les études notariales de Suresnes et les tribunaux de Nanterre.",
      medical: "Transport urgent de prélèvements et matériel médical depuis l'Hôpital Foch vers les laboratoires spécialisés.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants de Suresnes.",
      corporate: "Navettes entre les PME et sièges régionaux de Suresnes et leurs clients parisiens.",
      evenementiel: "Transport de matériel pour les événements de l'hippodrome de Saint-Cloud.",
      grandsComptes: "Compte entreprise pour l'Hôpital Foch et les grandes entreprises de Suresnes.",
    },
    keyClients: ["Hôpital Foch", "PME Suresnes", "Hippodrome Saint-Cloud"],
    distanceParis: "~20 min de Paris 16e",
    pricingZone: "standard",
    seoTitle: "Coursier Suresnes — Hôpital Foch, 92150 | ONE CONNEXION",
    seoDesc: "Coursier express à Suresnes (92). Hôpital Foch, PME, transport médical. Enlèvement < 45 min.",
    seoKeywords: ["coursier Suresnes", "livraison express 92150", "coursier Hôpital Foch Suresnes"],
  }),
  makeZone({
    slug: "rueil-malmaison",
    dept: "92500",
    name: "Rueil-Malmaison",
    category: "hauts-de-seine",
    landmarks: ["Château de Malmaison", "L'Oréal", "A13", "Aéroport Paris-Le Bourget (proche)", "Seine"],
    intro: "Rueil-Malmaison accueille le siège mondial de L'Oréal et de nombreux grands groupes (Schneider Electric R&D, Suez, Pfizer). C'est l'une des villes les plus riches en emplois cadres d'Île-de-France, avec des besoins logistiques B2B très élevés.",
    logisticsContext: "Rueil est accessible depuis la A13. L'Oréal et les autres sièges disposent de quais de réception dédiés. Nos coursiers connaissent les accès sécurisés de ces campus.",
    sectorExamples: {
      juridique: "Transport de contrats et documents légaux entre les directions juridiques de Rueil et leurs cabinets parisiens.",
      medical: "Transport de médicaments et matériel de recherche entre les sites Pfizer et Sanofi de Rueil.",
      ecommerce: "Livraisons pour les boutiques et commerces de Rueil-Malmaison.",
      corporate: "Navettes entre L'Oréal, Suez, Schneider R&D et leurs fournisseurs et partenaires.",
      evenementiel: "Transport de matériel pour les événements et présentations au château de Malmaison.",
      grandsComptes: "Compte entreprise pour L'Oréal, Pfizer et les grands groupes de Rueil.",
    },
    keyClients: ["L'Oréal (siège mondial)", "Pfizer", "Suez", "Schneider Electric R&D"],
    distanceParis: "~20 min de Paris 16e",
    pricingZone: "standard",
    seoTitle: "Coursier Rueil-Malmaison — L'Oréal, Pfizer, 92500 | ONE CONNEXION",
    seoDesc: "Coursier express à Rueil-Malmaison (92). L'Oréal, Pfizer, Suez, grands groupes. Enlèvement < 45 min.",
    seoKeywords: ["coursier Rueil-Malmaison", "livraison express 92500", "coursier L'Oréal Rueil"],
  }),
  makeZone({
    slug: "asnieres-sur-seine",
    dept: "92600",
    name: "Asnières-sur-Seine",
    category: "hauts-de-seine",
    landmarks: ["Seine", "Pôle économique Nord 92", "A86", "Paris 17e (limite)"],
    intro: "Asnières-sur-Seine est l'une des villes les plus peuplées des Hauts-de-Seine. Elle accueille un tissu dense de PME, d'agences et de professions libérales, aux portes du 17e arrondissement de Paris.",
    logisticsContext: "Asnières est à 10 minutes de Paris 17e via la Porte de Clichy. Nos scooters relient Asnières aux zones d'affaires parisiennes rapidement.",
    sectorExamples: {
      juridique: "Liaisons entre les cabinets d'Asnières et les tribunaux de Paris et de Nanterre.",
      medical: "Transport entre les cliniques et laboratoires d'Asnières et les hôpitaux voisins.",
      ecommerce: "Livraisons same-day pour les e-commerçants d'Asnières vers toute la petite couronne.",
      corporate: "Navettes entre les PME et agences d'Asnières et leurs clients parisiens.",
      evenementiel: "Transport pour les événements et manifestations d'Asnières.",
      grandsComptes: "Compte mensuel pour les PME et structures multi-sites d'Asnières.",
    },
    keyClients: ["PME Asnières", "Cabinets libéraux", "Agences communication", "Cliniques privées"],
    distanceParis: "~10 min de Paris 17e",
    pricingZone: "standard",
    seoTitle: "Coursier Asnières-sur-Seine — Livraison express 92600 | ONE CONNEXION",
    seoDesc: "Coursier express à Asnières-sur-Seine (92). PME, cabinets, médical. Enlèvement < 45 min.",
    seoKeywords: ["coursier Asnières-sur-Seine", "livraison express 92600", "coursier 92 Asnières"],
  }),
  makeZone({
    slug: "clichy-92",
    dept: "92110",
    name: "Clichy",
    fullName: "Clichy — Hauts-de-Seine",
    category: "hauts-de-seine",
    landmarks: ["L'Oréal usine historique", "Paris 17e (limite)", "Seine", "Carrefour de la Défense"],
    intro: "Clichy abrite l'usine historique de L'Oréal et un tissu industriel et tertiaire dense aux portes de Paris. Sa proximité immédiate avec le 17e en fait une destination très active pour les coursiers express.",
    logisticsContext: "Clichy est à 5 minutes de la Porte de Clichy. Nos scooters relient Clichy à La Défense et au 17e en moins de 15 minutes.",
    sectorExamples: {
      juridique: "Transport de contrats entre les entreprises de Clichy et les cabinets juridiques parisiens.",
      medical: "Transport entre les établissements de santé de Clichy et les hôpitaux voisins (Beaujon).",
      ecommerce: "Livraisons pour les e-commerçants et boutiques de Clichy.",
      corporate: "Navettes entre les industries et agences de Clichy et leurs partenaires parisiens.",
      evenementiel: "Transport de matériel pour les événements d'entreprise à Clichy.",
      grandsComptes: "Compte mensuel pour les industriels et grands groupes de Clichy.",
    },
    keyClients: ["L'Oréal Clichy", "Industries Seine", "PME tertiaires", "Agences"],
    distanceParis: "~5 min de Paris 17e",
    pricingZone: "standard",
    seoTitle: "Coursier Clichy 92 — Livraison express 92110 | ONE CONNEXION",
    seoDesc: "Coursier express à Clichy (92110). Industries, PME, L'Oréal. Enlèvement < 45 min. Limitrophe Paris 17e.",
    seoKeywords: ["coursier Clichy 92", "livraison express 92110", "coursier 92 Clichy"],
  }),
  makeZone({
    slug: "colombes",
    dept: "92700",
    name: "Colombes",
    category: "hauts-de-seine",
    landmarks: ["Stade Yves-du-Manoir", "A86", "Seine", "Gennevilliers (limite)"],
    intro: "Colombes est une ville industrielle et résidentielle avec un tissu économique actif. Sa position entre la Seine et l'A86 en fait un point logistique naturel pour la desserte du Nord des Hauts-de-Seine.",
    logisticsContext: "Colombes est accessible rapidement depuis l'A86 et le boulevard de Valmy. Nos coursiers couvrent toute la ville en moins de 30 minutes.",
    sectorExamples: {
      juridique: "Transport entre les études de Colombes et le Tribunal de Nanterre.",
      medical: "Transport inter-établissements de santé pour les structures de Colombes.",
      ecommerce: "Livraisons pour les commerçants et e-boutiques de Colombes.",
      corporate: "Navettes entre les entreprises de Colombes et leurs partenaires d'Île-de-France.",
      evenementiel: "Transport de matériel pour les événements sportifs et culturels de Colombes.",
      grandsComptes: "Compte entreprise pour les PME et ETI de Colombes.",
    },
    keyClients: ["Entreprises zone industrielle", "Stade Yves-du-Manoir", "PME Colombes"],
    distanceParis: "~20 min de Paris 17e",
    pricingZone: "standard",
    seoTitle: "Coursier Colombes — Livraison express 92700 | ONE CONNEXION",
    seoDesc: "Coursier express à Colombes (92). Entreprises, PME, médical. Enlèvement < 45 min.",
    seoKeywords: ["coursier Colombes", "livraison express 92700", "coursier 92 Colombes"],
  }),
  makeZone({
    slug: "gennevilliers",
    dept: "92230",
    name: "Gennevilliers",
    category: "hauts-de-seine",
    landmarks: ["Port de Gennevilliers", "Zone industrielle", "Seine", "A86"],
    intro: "Gennevilliers abrite le plus grand port fluvial d'Île-de-France et une zone industrielle massive. Chimie, logistique, agroalimentaire et services aux industries génèrent d'importants besoins de transport B2B express.",
    logisticsContext: "Gennevilliers est accessible depuis l'A86 et la D9. Le port et les zones industrielles disposent de quais et d'accès professionnels que nos coursiers maîtrisent.",
    sectorExamples: {
      juridique: "Transport de documents entre les entreprises industrielles et leurs conseils juridiques.",
      medical: "Transport de produits chimiques et matériaux de laboratoire entre les industries et les labos d'analyses.",
      ecommerce: "Livraisons pour les e-commerçants et boutiques de Gennevilliers.",
      corporate: "Navettes urgentes entre les directions générales des groupes industriels et leurs partenaires.",
      evenementiel: "Transport de matériel pour les événements professionnels des zones industrielles.",
      grandsComptes: "Compte pour les groupes industriels et logistiques du port de Gennevilliers.",
    },
    keyClients: ["Port de Gennevilliers", "Industries chimiques", "Plateformes logistiques", "Agroalimentaire"],
    distanceParis: "~20 min de Paris 18e",
    pricingZone: "standard",
    seoTitle: "Coursier Gennevilliers — Port, Zone industrielle 92230 | ONE CONNEXION",
    seoDesc: "Coursier express à Gennevilliers (92). Port fluvial, industries, zones logistiques. Enlèvement < 45 min.",
    seoKeywords: ["coursier Gennevilliers", "livraison express 92230", "coursier port Gennevilliers"],
  }),
  makeZone({
    slug: "montrouge",
    dept: "92120",
    name: "Montrouge",
    category: "hauts-de-seine",
    landmarks: ["Paris 14e (limite)", "Périphérique Sud", "Orange France", "Pôle Santé"],
    intro: "Montrouge est limitrophe du 14e arrondissement et abrite le siège d'Orange France et plusieurs sièges de groupes de services. Sa densité économique en fait une ville très active pour les coursiers express.",
    logisticsContext: "Montrouge est à 5 minutes de Paris 14e via la Porte de Montrouge. Nos scooters servent tous les quartiers de Montrouge en moins de 20 minutes.",
    sectorExamples: {
      juridique: "Liaisons entre les cabinets de Montrouge et les tribunaux parisiens.",
      medical: "Transport entre les établissements de santé de Montrouge et les hôpitaux proches.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants de Montrouge.",
      corporate: "Navettes entre Orange France et ses partenaires, ou entre les sièges de services et leurs clients.",
      evenementiel: "Transport pour les événements corporate des grands groupes de Montrouge.",
      grandsComptes: "Compte pour Orange France et les grands sièges de services de Montrouge.",
    },
    keyClients: ["Orange France", "Sièges services B2B", "Cabinets médicaux", "PME tertiaires"],
    distanceParis: "~5 min de Paris 14e",
    pricingZone: "standard",
    seoTitle: "Coursier Montrouge — Orange France, 92120 | ONE CONNEXION",
    seoDesc: "Coursier express à Montrouge (92). Orange France, sièges sociaux, PME. Enlèvement < 45 min.",
    seoKeywords: ["coursier Montrouge", "livraison express 92120", "coursier 92 Montrouge"],
  }),
  makeZone({
    slug: "malakoff",
    dept: "92240",
    name: "Malakoff",
    category: "hauts-de-seine",
    landmarks: ["Paris 14e (limite)", "Périphérique", "Pôle économique", "Châtillon (limite)"],
    intro: "Malakoff est une commune résidentielle et tertiaire aux portes du 14e. Elle accueille des agences, des PME et des professions libérales dans un tissu urbain dense et bien desservi.",
    logisticsContext: "Malakoff est à 5 minutes du périphérique Paris Sud. Nos coursiers la relient à Montparnasse et Châtillon en moins de 20 minutes.",
    sectorExamples: {
      juridique: "Transport entre les études et cabinets de Malakoff et les juridictions de Paris.",
      medical: "Transport inter-établissements de santé de Malakoff.",
      ecommerce: "Livraisons same-day pour les boutiques et e-commerçants de Malakoff.",
      corporate: "Navettes entre les agences et PME de Malakoff et leurs clients parisiens.",
      evenementiel: "Transport de matériel pour les événements locaux.",
      grandsComptes: "Compte pour les PME multi-sites de Malakoff.",
    },
    keyClients: ["PME tertiaires", "Agences", "Cabinets libéraux", "Cliniques"],
    distanceParis: "~5 min de Paris 14e",
    pricingZone: "standard",
    seoTitle: "Coursier Malakoff — Livraison express 92240 | ONE CONNEXION",
    seoDesc: "Coursier express à Malakoff (92). PME, agences, professions libérales. Enlèvement < 45 min.",
    seoKeywords: ["coursier Malakoff", "livraison express 92240", "coursier 92 Malakoff"],
  }),
  makeZone({
    slug: "vanves",
    dept: "92170",
    name: "Vanves",
    category: "hauts-de-seine",
    landmarks: ["Paris 15e (limite)", "Palais des Sports de Vanves", "ESCP Europe", "Périphérique"],
    intro: "Vanves est une ville compacte et dynamique, limitrophe du 15e arrondissement. Elle accueille l'ESCP Europe et des PME de services. Sa position entre Paris et les villes du 92 Sud en fait un point de desserte stratégique.",
    logisticsContext: "Vanves est à 5 minutes du 15e arrondissement. Nos scooters assurent des liaisons rapides entre Vanves et Montparnasse.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Vanves et les juridictions parisiennes.",
      medical: "Transport inter-établissements pour les structures de santé de Vanves.",
      ecommerce: "Livraisons pour les boutiques de Vanves.",
      corporate: "Navettes entre l'ESCP et les entreprises de Vanves et leurs partenaires.",
      evenementiel: "Transport pour les événements au Palais des Sports de Vanves.",
      grandsComptes: "Compte pour les entreprises de services de Vanves.",
    },
    keyClients: ["ESCP Europe", "PME services", "Palais des Sports"],
    distanceParis: "~5 min de Paris 15e",
    pricingZone: "standard",
    seoTitle: "Coursier Vanves — ESCP, Livraison express 92170 | ONE CONNEXION",
    seoDesc: "Coursier express à Vanves (92). ESCP Europe, PME, services. Enlèvement < 45 min.",
    seoKeywords: ["coursier Vanves", "livraison express 92170", "coursier 92 Vanves"],
  }),
  makeZone({
    slug: "clamart",
    dept: "92140",
    name: "Clamart",
    category: "hauts-de-seine",
    landmarks: ["Hôpital Percy (armée)", "Forêt de Clamart", "CEA (limite)", "A86"],
    intro: "Clamart accueille l'Hôpital d'instruction des armées Percy, établissement médical militaire de référence, et des laboratoires du CEA à sa frontière. Ce profil médico-scientifique génère des besoins spécifiques en transport sécurisé.",
    logisticsContext: "Clamart est accessible depuis l'A86 et la N306. Nos coursiers connaissent les procédures d'accès aux établissements militaires et scientifiques.",
    sectorExamples: {
      juridique: "Transport de documents administratifs entre Clamart et les juridictions.",
      medical: "Transport de prélèvements et matériel médical depuis l'Hôpital Percy et les laboratoires CEA de Fontenay.",
      ecommerce: "Livraisons pour les boutiques de Clamart.",
      corporate: "Navettes entre les entreprises de Clamart et leurs partenaires d'IDF.",
      evenementiel: "Transport pour les événements institutionnels à Clamart.",
      grandsComptes: "Compte pour les établissements publics et militaires de Clamart.",
    },
    keyClients: ["Hôpital Percy", "CEA Saclay (proche)", "PME Clamart"],
    distanceParis: "~20 min de Paris 15e",
    pricingZone: "standard",
    seoTitle: "Coursier Clamart — Hôpital Percy, CEA 92140 | ONE CONNEXION",
    seoDesc: "Coursier express à Clamart (92). Hôpital Percy, CEA, transport médical. Enlèvement < 45 min.",
    seoKeywords: ["coursier Clamart", "livraison express 92140", "coursier hôpital Percy Clamart"],
  }),
  makeZone({
    slug: "chatillon",
    dept: "92320",
    name: "Châtillon",
    category: "hauts-de-seine",
    landmarks: ["Axa France", "Périphérique Sud", "Malakoff (limite)", "Montrouge (limite)"],
    intro: "Châtillon accueille le siège d'Axa France et de nombreuses entreprises de services financiers et technologiques. Sa position sur la rocade périphérique en fait une plaque tournante logistique du sud des Hauts-de-Seine.",
    logisticsContext: "Châtillon est accessible depuis le périphérique Sud. Nos coursiers relient Châtillon à Paris 14e en moins de 15 minutes.",
    sectorExamples: {
      juridique: "Transport de contrats entre les directions juridiques d'Axa et leurs cabinets conseil.",
      medical: "Transport inter-établissements pour les structures de santé de Châtillon.",
      ecommerce: "Livraisons pour les boutiques de Châtillon.",
      corporate: "Navettes entre Axa France et ses partenaires et sous-traitants.",
      evenementiel: "Transport de matériel pour les événements corporate d'Axa et des groupes de Châtillon.",
      grandsComptes: "Compte entreprise pour Axa France avec imputation par direction.",
    },
    keyClients: ["Axa France", "Sièges services financiers", "PME tech"],
    distanceParis: "~10 min de Paris 14e",
    pricingZone: "standard",
    seoTitle: "Coursier Châtillon — Axa France, 92320 | ONE CONNEXION",
    seoDesc: "Coursier express à Châtillon (92). Axa France, sièges financiers, PME. Enlèvement < 45 min.",
    seoKeywords: ["coursier Châtillon 92", "livraison express 92320", "coursier Axa France Châtillon"],
  }),
  makeZone({
    slug: "bagneux",
    dept: "92220",
    name: "Bagneux",
    category: "hauts-de-seine",
    landmarks: ["ZAC des Blagis", "Périphérique", "Montrouge (limite)", "A86"],
    intro: "Bagneux est une commune en plein développement économique avec plusieurs zones d'activités actives. Sa position au Sud de la petite couronne en fait une ville incontournable pour les liaisons entre Paris et le 92 Sud.",
    logisticsContext: "Bagneux est accessible depuis l'A86 et le périphérique. Nos coursiers desservent toute la ville rapidement.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Bagneux et les tribunaux de Paris et Nanterre.",
      medical: "Transport inter-établissements de santé de Bagneux.",
      ecommerce: "Livraisons pour les e-commerçants et boutiques de Bagneux.",
      corporate: "Navettes entre les PME et agences de Bagneux et leurs clients.",
      evenementiel: "Transport de matériel pour les événements locaux de Bagneux.",
      grandsComptes: "Compte pour les entreprises des zones d'activité de Bagneux.",
    },
    keyClients: ["Zones d'activités Bagneux", "PME", "Commerces"],
    distanceParis: "~15 min de Paris 14e",
    pricingZone: "standard",
    seoTitle: "Coursier Bagneux — Livraison express 92220 | ONE CONNEXION",
    seoDesc: "Coursier express à Bagneux (92). PME, zones d'activités. Enlèvement < 45 min.",
    seoKeywords: ["coursier Bagneux", "livraison express 92220", "coursier 92 Bagneux"],
  }),
  makeZone({
    slug: "antony",
    dept: "92160",
    name: "Antony",
    category: "hauts-de-seine",
    landmarks: ["Hôpital Antoine-Béclère", "Pôle scientifique de Saclay (proche)", "A86", "SAFRAN"],
    intro: "Antony est une ville scientifique et industrielle du sud des Hauts-de-Seine. L'Hôpital Antoine-Béclère est une maternité de référence nationale. Des groupes comme SAFRAN et des entreprises de technologies y ont leur siège.",
    logisticsContext: "Antony est bien desservie par l'A86 et le RER B. Nos motos routières relient Antony à Paris en moins de 25 minutes.",
    sectorExamples: {
      juridique: "Transport de documents entre les entreprises d'Antony et leurs conseils juridiques.",
      medical: "Transport de prélèvements et matériel médical depuis l'Hôpital Antoine-Béclère.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants d'Antony.",
      corporate: "Navettes entre SAFRAN et les autres sièges d'Antony et leurs partenaires.",
      evenementiel: "Transport pour les événements corporate des grands groupes d'Antony.",
      grandsComptes: "Compte pour SAFRAN et les grands groupes industriels d'Antony.",
    },
    keyClients: ["Hôpital Antoine-Béclère", "SAFRAN", "Groupes industriels", "Pôle Saclay (proche)"],
    distanceParis: "~25 min de Paris 14e",
    pricingZone: "standard",
    seoTitle: "Coursier Antony — SAFRAN, Hôpital Béclère 92160 | ONE CONNEXION",
    seoDesc: "Coursier express à Antony (92). SAFRAN, Antoine-Béclère, groupes industriels. Enlèvement < 45 min.",
    seoKeywords: ["coursier Antony", "livraison express 92160", "coursier 92 Antony"],
  }),
  makeZone({
    slug: "meudon",
    dept: "92190",
    name: "Meudon",
    category: "hauts-de-seine",
    landmarks: ["ONERA", "Observatoire de Meudon", "Forêt de Meudon", "A13", "Vélizy (limite)"],
    intro: "Meudon abrite l'ONERA, centre national de recherche aérospatiale, et l'Observatoire de Paris-Meudon. Ce profil scientifique et résidentiel de prestige génère des besoins logistiques spécifiques pour les transports de matériel de recherche et de documents sensibles.",
    logisticsContext: "Meudon est accessible depuis l'A13. Nos coursiers connaissent les accès aux sites de recherche et aux zones résidentielles de prestige de la ville.",
    sectorExamples: {
      juridique: "Transport de documents entre les instituts de recherche de Meudon et leurs conseils.",
      medical: "Transport de matériaux de recherche et d'analyses entre Meudon et les laboratoires partenaires.",
      ecommerce: "Livraisons premium pour les résidences de prestige et boutiques de Meudon.",
      corporate: "Navettes entre l'ONERA et ses partenaires industriels et académiques.",
      evenementiel: "Transport de matériel pour les colloques scientifiques à l'ONERA et l'Observatoire.",
      grandsComptes: "Compte pour l'ONERA et les instituts de recherche de Meudon.",
    },
    keyClients: ["ONERA", "Observatoire Paris-Meudon", "Résidences prestige", "Instituts de recherche"],
    distanceParis: "~20 min de Paris 16e",
    pricingZone: "standard",
    seoTitle: "Coursier Meudon — ONERA, Observatoire 92190 | ONE CONNEXION",
    seoDesc: "Coursier express à Meudon (92). ONERA, recherche aérospatiale, résidentiel prestige. Enlèvement < 45 min.",
    seoKeywords: ["coursier Meudon", "livraison express 92190", "coursier ONERA Meudon"],
  }),
  makeZone({
    slug: "sevres",
    dept: "92310",
    name: "Sèvres",
    category: "hauts-de-seine",
    landmarks: ["Manufacture nationale de Sèvres", "INRIA", "Seine", "Pont de Sèvres", "A13"],
    intro: "Sèvres est une ville patrimoniale et scientifique. La Manufacture nationale de porcelaine est mondialement connue. L'INRIA y a une antenne. Ces institutions génèrent des besoins logistiques spécifiques : transport d'œuvres, de matériel de recherche et de documents officiels.",
    logisticsContext: "Sèvres est à 20 minutes de Paris via l'A13. Le pont de Sèvres est un point de passage stratégique entre la rive gauche et la rive droite.",
    sectorExamples: {
      juridique: "Transport de documents et contrats entre les institutions de Sèvres et leurs conseils.",
      medical: "Transport inter-établissements pour les structures de santé de Sèvres.",
      ecommerce: "Livraisons premium pour les boutiques et résidences de Sèvres.",
      corporate: "Navettes entre les entreprises et instituts de Sèvres et leurs partenaires.",
      evenementiel: "Transport d'œuvres et de pièces pour les expositions de la Manufacture de Sèvres.",
      grandsComptes: "Compte pour la Manufacture nationale et les institutions de Sèvres.",
    },
    keyClients: ["Manufacture de Sèvres", "INRIA", "Résidences prestige"],
    distanceParis: "~20 min de Paris 16e",
    pricingZone: "standard",
    seoTitle: "Coursier Sèvres — Manufacture nationale, INRIA 92310 | ONE CONNEXION",
    seoDesc: "Coursier express à Sèvres (92). Manufacture nationale, INRIA, résidentiel prestige. Enlèvement < 45 min.",
    seoKeywords: ["coursier Sèvres", "livraison express 92310", "coursier 92 Sèvres"],
  }),
  makeZone({
    slug: "saint-cloud",
    dept: "92210",
    name: "Saint-Cloud",
    category: "hauts-de-seine",
    landmarks: ["Parc de Saint-Cloud", "Hippodrome de Saint-Cloud", "ECP", "A13", "Seine"],
    intro: "Saint-Cloud est une ville résidentielle de prestige aux portes de Paris. L'École Centrale Paris (ECP) y est installée, de même que des sièges de grandes entreprises. L'hippodrome de Saint-Cloud génère des événements premium réguliers.",
    logisticsContext: "Saint-Cloud est accessible depuis l'A13. Nos coursiers servent les résidences de prestige, l'ECP et les sièges d'entreprises avec la discrétion requise.",
    sectorExamples: {
      juridique: "Transport de documents patrimoniaux et juridiques pour les études de Saint-Cloud.",
      medical: "Transport entre les cliniques privées de prestige et les laboratoires.",
      ecommerce: "Livraisons premium pour les résidences et boutiques de Saint-Cloud.",
      corporate: "Navettes entre les sièges de Saint-Cloud et leurs partenaires parisiens.",
      evenementiel: "Transport de matériel pour les événements à l'hippodrome de Saint-Cloud.",
      grandsComptes: "Compte pour les grands groupes et institutions de Saint-Cloud.",
    },
    keyClients: ["ECP", "Hippodrome Saint-Cloud", "Cliniques privées prestige", "Sièges sociaux"],
    distanceParis: "~20 min de Paris 16e",
    pricingZone: "standard",
    seoTitle: "Coursier Saint-Cloud — ECP, Hippodrome 92210 | ONE CONNEXION",
    seoDesc: "Coursier express à Saint-Cloud (92). ECP, hippodrome, résidentiel prestige. Enlèvement < 45 min.",
    seoKeywords: ["coursier Saint-Cloud", "livraison express 92210", "coursier 92 Saint-Cloud"],
  }),
  makeZone({
    slug: "chatenay-malabry",
    dept: "92290",
    name: "Châtenay-Malabry",
    category: "hauts-de-seine",
    landmarks: ["École Centrale Paris", "Parc de Sceaux", "A86", "Robinson"],
    intro: "Châtenay-Malabry accueille l'École Centrale Paris (avant son déménagement à Saclay) et jouxte le magnifique parc de Sceaux. Son tissu économique mêle entreprises high-tech, professions libérales et grandes écoles.",
    logisticsContext: "Châtenay-Malabry est accessible depuis l'A86. Nos scooters relient la ville à Paris et Antony en moins de 25 minutes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Châtenay et les juridictions.",
      medical: "Transport inter-établissements pour les structures de santé locales.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants de Châtenay.",
      corporate: "Navettes entre les entreprises high-tech et leurs partenaires.",
      evenementiel: "Transport pour les événements académiques de l'ECP.",
      grandsComptes: "Compte pour les entreprises multi-sites de Châtenay.",
    },
    keyClients: ["École Centrale Paris", "Entreprises high-tech", "Parc de Sceaux"],
    distanceParis: "~25 min de Paris 14e",
    pricingZone: "standard",
    seoTitle: "Coursier Châtenay-Malabry — ECP, Sceaux 92290 | ONE CONNEXION",
    seoDesc: "Coursier express à Châtenay-Malabry (92). ECP, high-tech, parc de Sceaux. Enlèvement < 45 min.",
    seoKeywords: ["coursier Châtenay-Malabry", "livraison express 92290", "coursier 92 Châtenay"],
  }),
  makeZone({
    slug: "sceaux",
    dept: "92330",
    name: "Sceaux",
    category: "hauts-de-seine",
    landmarks: ["Parc de Sceaux", "Université Paris-Saclay (proche)", "RER B", "Châtenay (limite)"],
    intro: "Sceaux est une ville résidentielle aisée et universitaire, dominée par son magnifique parc classé. Elle accueille des professions libérales et des cadres supérieurs dont les besoins logistiques sont récurrents.",
    logisticsContext: "Sceaux est accessible en RER B depuis Paris en 20 minutes. Nos scooters desservent toute la ville depuis nos relais du 92.",
    sectorExamples: {
      juridique: "Transport entre les études notariales de Sceaux et les juridictions voisines.",
      medical: "Transport entre les cabinets médicaux et cliniques de Sceaux.",
      ecommerce: "Livraisons pour les boutiques de prestige de Sceaux.",
      corporate: "Navettes entre les professions libérales et leurs clients et partenaires.",
      evenementiel: "Transport pour les événements au château de Sceaux.",
      grandsComptes: "Compte pour les professions libérales et structures multi-sites.",
    },
    keyClients: ["Professions libérales", "Études notariales", "Cliniques privées"],
    distanceParis: "~25 min de Paris 14e",
    pricingZone: "standard",
    seoTitle: "Coursier Sceaux — Parc de Sceaux, 92330 | ONE CONNEXION",
    seoDesc: "Coursier express à Sceaux (92). Professions libérales, études, cliniques. Enlèvement < 45 min.",
    seoKeywords: ["coursier Sceaux", "livraison express 92330", "coursier 92 Sceaux"],
  }),
  makeZone({
    slug: "bourg-la-reine",
    dept: "92340",
    name: "Bourg-la-Reine",
    category: "hauts-de-seine",
    landmarks: ["RER B", "Sceaux (limite)", "Antony (limite)", "A86"],
    intro: "Bourg-la-Reine est un nœud de transport et une ville résidentielle active sur le RER B. Sa position entre Sceaux et Antony en fait un point de passage incontournable pour la desserte du sud des Hauts-de-Seine.",
    logisticsContext: "Bourg-la-Reine est bien desservie depuis l'A86. Nos coursiers relient la ville à Paris et Antony en moins de 20 minutes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Bourg-la-Reine et les juridictions.",
      medical: "Transport inter-établissements pour les structures de santé locales.",
      ecommerce: "Livraisons pour les boutiques et commerces de Bourg-la-Reine.",
      corporate: "Navettes entre les PME de Bourg-la-Reine et leurs partenaires.",
      evenementiel: "Transport pour les événements locaux.",
      grandsComptes: "Compte pour les PME multi-sites de Bourg-la-Reine.",
    },
    keyClients: ["PME", "Professions libérales", "Commerces"],
    distanceParis: "~20 min de Paris 14e",
    pricingZone: "standard",
    seoTitle: "Coursier Bourg-la-Reine — Livraison express 92340 | ONE CONNEXION",
    seoDesc: "Coursier express à Bourg-la-Reine (92). PME, professions libérales. Enlèvement < 45 min.",
    seoKeywords: ["coursier Bourg-la-Reine", "livraison express 92340", "coursier 92 Bourg-la-Reine"],
  }),
  makeZone({
    slug: "fontenay-aux-roses",
    dept: "92260",
    name: "Fontenay-aux-Roses",
    category: "hauts-de-seine",
    landmarks: ["CEA Fontenay", "Bagneux (limite)", "Châtenay (limite)", "A86"],
    intro: "Fontenay-aux-Roses abrite un site du CEA (Commissariat à l'énergie atomique), l'un des plus importants centres de recherche en sécurité nucléaire d'Europe. Ce profil scientifique et résidentiel génère des besoins logistiques très spécifiques.",
    logisticsContext: "Fontenay-aux-Roses est accessible depuis l'A86. Nos coursiers connaissent les protocoles d'accès aux sites du CEA.",
    sectorExamples: {
      juridique: "Transport de documents officiels entre le CEA et les administrations.",
      medical: "Transport de matériaux de recherche et d'échantillons entre le CEA et les laboratoires partenaires.",
      ecommerce: "Livraisons pour les boutiques et commerçants de Fontenay.",
      corporate: "Navettes entre le CEA et ses partenaires industriels et académiques.",
      evenementiel: "Transport de matériel pour les conférences scientifiques du CEA.",
      grandsComptes: "Compte pour le CEA et ses partenaires industriels.",
    },
    keyClients: ["CEA Fontenay-aux-Roses", "Instituts de recherche", "PME"],
    distanceParis: "~20 min de Paris 14e",
    pricingZone: "standard",
    seoTitle: "Coursier Fontenay-aux-Roses — CEA, 92260 | ONE CONNEXION",
    seoDesc: "Coursier express à Fontenay-aux-Roses (92). CEA, recherche nucléaire, PME. Enlèvement < 45 min.",
    seoKeywords: ["coursier Fontenay-aux-Roses", "livraison express 92260", "coursier CEA Fontenay"],
  }),
  makeZone({
    slug: "le-plessis-robinson",
    dept: "92350",
    name: "Le Plessis-Robinson",
    category: "hauts-de-seine",
    landmarks: ["Pôle des métiers", "Clamart (limite)", "A86", "Châtenay (limite)"],
    intro: "Le Plessis-Robinson est une ville en pleine transformation urbanistique avec un nouveau centre-ville et un tissu d'entreprises actif. Sa position entre Clamart et Châtenay en fait un point stratégique du sud-ouest de la petite couronne.",
    logisticsContext: "Le Plessis-Robinson est accessible depuis l'A86. Nos coursiers desservent toute la ville en moins de 30 minutes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets du Plessis et les juridictions.",
      medical: "Transport inter-établissements pour les structures de santé locales.",
      ecommerce: "Livraisons pour les boutiques et commerces du Plessis-Robinson.",
      corporate: "Navettes entre les PME du Plessis et leurs partenaires.",
      evenementiel: "Transport pour les événements locaux.",
      grandsComptes: "Compte pour les entreprises du Plessis-Robinson.",
    },
    keyClients: ["Entreprises pôle économique", "PME", "Commerces"],
    distanceParis: "~20 min de Paris 14e",
    pricingZone: "standard",
    seoTitle: "Coursier Le Plessis-Robinson — Livraison express 92350 | ONE CONNEXION",
    seoDesc: "Coursier express au Plessis-Robinson (92). PME, professions libérales. Enlèvement < 45 min.",
    seoKeywords: ["coursier Le Plessis-Robinson", "livraison express 92350", "coursier 92 Plessis-Robinson"],
  }),
  makeZone({
    slug: "la-garenne-colombes",
    dept: "92250",
    name: "La Garenne-Colombes",
    category: "hauts-de-seine",
    landmarks: ["Colombes (limite)", "A86", "Paris 17e (proche)", "Seine"],
    intro: "La Garenne-Colombes est une commune résidentielle et active du nord des Hauts-de-Seine. Bien desservie par l'A86, elle accueille des entreprises et des professions libérales bénéficiant de sa proximité avec Paris.",
    logisticsContext: "La Garenne est à 15 minutes de Paris via la Porte de Champerret. Nos scooters relient facilement la ville aux zones d'affaires parisiennes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de La Garenne et les juridictions de Paris et Nanterre.",
      medical: "Transport inter-établissements de santé de La Garenne.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants de La Garenne.",
      corporate: "Navettes entre les entreprises de La Garenne et leurs clients.",
      evenementiel: "Transport pour les événements locaux et corporates.",
      grandsComptes: "Compte pour les PME et structures multi-sites de La Garenne.",
    },
    keyClients: ["PME", "Professions libérales", "Commerces"],
    distanceParis: "~15 min de Paris 17e",
    pricingZone: "standard",
    seoTitle: "Coursier La Garenne-Colombes — Livraison express 92250 | ONE CONNEXION",
    seoDesc: "Coursier express à La Garenne-Colombes (92). PME, professions libérales. Enlèvement < 45 min.",
    seoKeywords: ["coursier La Garenne-Colombes", "livraison express 92250", "coursier 92 La Garenne"],
  }),
];
