import { makeZone } from "./factory";
import type { Zone } from "./types";

export const ZONES_93: Zone[] = [
  makeZone({
    slug: "aubervilliers",
    dept: "93300",
    name: "Aubervilliers",
    category: "seine-saint-denis",
    landmarks: ["Plaine Saint-Denis (limite)", "Fort d'Aubervilliers", "Canal Saint-Denis", "A1", "Paris 19e (limite)"],
    intro: "Aubervilliers est limitrophe du 19e arrondissement et en pleine transformation. Le projet du Grand Paris Express y crée une nouvelle centralité. Son tissu d'entreprises, d'ateliers et de commerces de gros est l'un des plus denses de la petite couronne nord.",
    logisticsContext: "Aubervilliers est à 10 minutes de Paris 19e via la Porte d'Aubervilliers. L'A1 permet des liaisons rapides vers Roissy et le nord de l'IDF.",
    sectorExamples: {
      juridique: "Transport entre les cabinets d'Aubervilliers et les juridictions de Paris et Bobigny.",
      medical: "Transport inter-établissements de santé pour les structures d'Aubervilliers.",
      ecommerce: "Livraisons pour les grossistes et e-commerçants d'Aubervilliers.",
      corporate: "Navettes entre les entreprises d'Aubervilliers et leurs partenaires parisiens.",
      evenementiel: "Transport de matériel pour les événements au Fort d'Aubervilliers.",
      grandsComptes: "Compte pour les grossistes et industriels d'Aubervilliers.",
    },
    keyClients: ["Grossistes", "Ateliers", "Commerces de gros", "PME canal Saint-Denis"],
    distanceParis: "~10 min de Paris 19e",
    pricingZone: "standard",
    seoTitle: "Coursier Aubervilliers — Livraison express 93300 | ONE CONNEXION",
    seoDesc: "Coursier express à Aubervilliers (93). Grossistes, PME, commerce de gros. Enlèvement < 45 min.",
    seoKeywords: ["coursier Aubervilliers", "livraison express 93300", "coursier 93 Aubervilliers"],
  }),
  makeZone({
    slug: "pantin",
    dept: "93500",
    name: "Pantin",
    category: "seine-saint-denis",
    landmarks: ["Canal de l'Ourcq", "IRCAM / Magasin Général", "Paris 19e (limite)", "A3"],
    intro: "Pantin est devenu le nouveau quartier créatif et artistique de la petite couronne. Chanel y a installé son centre logistique, LVMH ses ateliers. Mode, luxe et création y ont élu domicile aux bords du canal de l'Ourcq.",
    logisticsContext: "Pantin est à 10 minutes de Paris 19e. Le canal de l'Ourcq est un axe logistique naturel. Nos scooters desservent les ateliers et showrooms des grandes maisons.",
    sectorExamples: {
      juridique: "Liaisons entre les directions juridiques des grandes maisons de Pantin et leurs cabinets conseil.",
      medical: "Transport inter-établissements de santé de Pantin.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants de Pantin.",
      corporate: "Navettes entre les ateliers Chanel, LVMH et leurs partenaires et fournisseurs.",
      evenementiel: "Transport de matériel pour les défilés et événements des maisons de luxe de Pantin.",
      grandsComptes: "Compte entreprise pour Chanel, LVMH et les grands groupes de luxe de Pantin.",
    },
    keyClients: ["Chanel", "LVMH", "Studios créatifs", "Mode & luxe canal Ourcq"],
    distanceParis: "~10 min de Paris 19e",
    pricingZone: "standard",
    seoTitle: "Coursier Pantin — Chanel, LVMH, Canal Ourcq 93500 | ONE CONNEXION",
    seoDesc: "Coursier express à Pantin (93). Chanel, LVMH, mode et luxe. Enlèvement < 45 min.",
    seoKeywords: ["coursier Pantin", "livraison express 93500", "coursier Chanel Pantin", "coursier luxe Pantin"],
  }),
  makeZone({
    slug: "saint-ouen",
    dept: "93400",
    name: "Saint-Ouen",
    category: "seine-saint-denis",
    landmarks: ["Marché aux Puces de Saint-Ouen", "Paris 18e (limite)", "Canal Saint-Denis", "Pôle universitaire"],
    intro: "Saint-Ouen est célèbre pour son marché aux Puces, le plus grand marché d'antiquités du monde, mais c'est aussi une ville en pleine transformation avec l'arrivée du Grand Paris Express. Des milliers de transactions commerciales y nécessitent des livraisons express quotidiennes.",
    logisticsContext: "Saint-Ouen est à 5 minutes de Paris 18e via la Porte de Clignancourt. Nos scooters servent aussi bien les antiquaires que les nouvelles entreprises du quartier.",
    sectorExamples: {
      juridique: "Transport de contrats entre les marchands des Puces, les études et les juridictions.",
      medical: "Transport inter-établissements de santé de Saint-Ouen.",
      ecommerce: "Livraisons pour les marchands des Puces et les e-commerçants de Saint-Ouen.",
      corporate: "Navettes entre les entreprises de Saint-Ouen et leurs partenaires parisiens.",
      evenementiel: "Transport d'antiquités et d'objets d'art pour les expositions.",
      grandsComptes: "Compte pour les grands marchands des Puces et les groupes de Saint-Ouen.",
    },
    keyClients: ["Marché aux Puces", "Antiquaires", "PME Grand Paris Express", "Commerces"],
    distanceParis: "~5 min de Paris 18e",
    pricingZone: "standard",
    seoTitle: "Coursier Saint-Ouen — Puces, 93400 | ONE CONNEXION",
    seoDesc: "Coursier express à Saint-Ouen (93). Marché aux Puces, antiquaires, PME. Enlèvement < 45 min.",
    seoKeywords: ["coursier Saint-Ouen", "livraison express 93400", "coursier Puces Saint-Ouen"],
  }),
  makeZone({
    slug: "bobigny",
    dept: "93000",
    name: "Bobigny",
    category: "seine-saint-denis",
    landmarks: ["Préfecture 93", "Tribunal de Bobigny", "Hôpital Avicenne", "A3", "A86"],
    intro: "Bobigny est la préfecture de la Seine-Saint-Denis. Elle concentre le Tribunal de grande instance, la Préfecture et l'Hôpital Avicenne, CHU de référence. Ces institutions génèrent quotidiennement des besoins en transport de documents urgents et en liaisons médicales.",
    logisticsContext: "Bobigny est accessible depuis l'A3 et l'A86. Nos coursiers connaissent les accès aux greffes du tribunal et aux différents services hospitaliers d'Avicenne.",
    sectorExamples: {
      juridique: "Dépôts au greffe du Tribunal de Bobigny, liaisons entre cabinets d'avocats et la Préfecture 93.",
      medical: "Transport de prélèvements et documents médicaux depuis l'Hôpital Avicenne vers les laboratoires partenaires.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants de Bobigny.",
      corporate: "Navettes entre les entreprises de Bobigny et leurs partenaires.",
      evenementiel: "Transport pour les événements institutionnels de la Préfecture.",
      grandsComptes: "Compte pour l'Hôpital Avicenne et les institutions de Bobigny.",
    },
    keyClients: ["Tribunal de Bobigny", "Préfecture 93", "Hôpital Avicenne", "Administrations publiques"],
    distanceParis: "~20 min de Paris 19e",
    pricingZone: "standard",
    seoTitle: "Coursier Bobigny — Tribunal, Préfecture 93, Avicenne | ONE CONNEXION",
    seoDesc: "Coursier express à Bobigny (93). Tribunal, Préfecture, Hôpital Avicenne. Enlèvement < 45 min.",
    seoKeywords: ["coursier Bobigny", "livraison express 93000", "coursier tribunal Bobigny", "coursier 93 Bobigny"],
  }),
  makeZone({
    slug: "drancy",
    dept: "93700",
    name: "Drancy",
    category: "seine-saint-denis",
    landmarks: ["Aéroport du Bourget (proche)", "A1", "Zone industrielle", "Le Bourget (limite)"],
    intro: "Drancy est une ville industrielle et de services proche du Bourget. Sa position sur l'A1 en fait un point de transit logistique important pour les entreprises qui relient Paris au nord de l'IDF et à l'aéroport du Bourget.",
    logisticsContext: "Drancy est accessible depuis l'A1 et l'A86. Nos coursiers relient Drancy à Paris 18e et à l'aéroport du Bourget en moins de 20 minutes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Drancy et les juridictions de Bobigny.",
      medical: "Transport inter-établissements de santé de Drancy.",
      ecommerce: "Livraisons pour les commerces et e-commerçants de Drancy.",
      corporate: "Navettes entre les entreprises industrielles de Drancy et leurs partenaires.",
      evenementiel: "Transport de matériel pour les salons au Bourget (Paris Air Show).",
      grandsComptes: "Compte pour les industriels et logisticiens de Drancy.",
    },
    keyClients: ["Industriels", "PME logistiques", "Zone d'activité Bourget"],
    distanceParis: "~20 min de Paris 18e",
    pricingZone: "standard",
    seoTitle: "Coursier Drancy — Le Bourget, Zone industrielle 93700 | ONE CONNEXION",
    seoDesc: "Coursier express à Drancy (93). Zone industrielle, Bourget, logistique. Enlèvement < 45 min.",
    seoKeywords: ["coursier Drancy", "livraison express 93700", "coursier 93 Drancy"],
  }),
  makeZone({
    slug: "aulnay-sous-bois",
    dept: "93600",
    name: "Aulnay-sous-Bois",
    category: "seine-saint-denis",
    landmarks: ["Zone industrielle Nord", "A1", "A3", "Aéroport Roissy (proche)", "Hôpital Robert-Ballanger"],
    intro: "Aulnay-sous-Bois est une ville industrielle importante, limitrophe de Roissy. L'Hôpital Robert-Ballanger est un établissement de référence du nord du 93. Les zones industrielles et la proximité de l'aéroport génèrent des besoins logistiques spécifiques.",
    logisticsContext: "Aulnay est accessible depuis l'A1 et l'A3. Sa proximité avec Roissy CDG (15 min) permet des liaisons rapides avec l'aéroport.",
    sectorExamples: {
      juridique: "Transport entre les cabinets d'Aulnay et les juridictions de Bobigny.",
      medical: "Transport de prélèvements et matériel médical depuis l'Hôpital Robert-Ballanger.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants d'Aulnay.",
      corporate: "Navettes entre les entreprises industrielles d'Aulnay et leurs partenaires.",
      evenementiel: "Transport pour les salons professionnels de la zone.",
      grandsComptes: "Compte pour les industriels et grands groupes d'Aulnay.",
    },
    keyClients: ["Hôpital Robert-Ballanger", "Industriels zone nord", "Logisticiens Roissy"],
    distanceParis: "~25 min de Paris 18e",
    pricingZone: "standard",
    seoTitle: "Coursier Aulnay-sous-Bois — Robert-Ballanger, 93600 | ONE CONNEXION",
    seoDesc: "Coursier express à Aulnay-sous-Bois (93). Hôpital Robert-Ballanger, zones industrielles. Enlèvement < 45 min.",
    seoKeywords: ["coursier Aulnay-sous-Bois", "livraison express 93600", "coursier 93 Aulnay"],
  }),
  makeZone({
    slug: "bondy",
    dept: "93140",
    name: "Bondy",
    category: "seine-saint-denis",
    landmarks: ["Canal de l'Ourcq", "A3", "Noisy-le-Sec (limite)", "Gare RER E"],
    intro: "Bondy est une ville de la moyenne couronne du 93, bien desservie par l'A3 et le RER E. Son tissu économique mêle PME, artisans et services. Le canal de l'Ourcq offre un axe logistique naturel.",
    logisticsContext: "Bondy est accessible depuis l'A3. Nos coursiers relient Bondy à Paris 20e en moins de 25 minutes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Bondy et les tribunaux de Bobigny.",
      medical: "Transport inter-établissements de santé de Bondy.",
      ecommerce: "Livraisons pour les commerçants et e-boutiques de Bondy.",
      corporate: "Navettes entre les PME de Bondy et leurs partenaires parisiens.",
      evenementiel: "Transport de matériel pour les événements locaux.",
      grandsComptes: "Compte pour les PME et artisans de Bondy.",
    },
    keyClients: ["PME", "Artisans", "Commerces", "Services"],
    distanceParis: "~25 min de Paris 20e",
    pricingZone: "standard",
    seoTitle: "Coursier Bondy — Livraison express 93140 | ONE CONNEXION",
    seoDesc: "Coursier express à Bondy (93). PME, artisans, commerces. Enlèvement < 45 min.",
    seoKeywords: ["coursier Bondy", "livraison express 93140", "coursier 93 Bondy"],
  }),
  makeZone({
    slug: "rosny-sous-bois",
    dept: "93110",
    name: "Rosny-sous-Bois",
    category: "seine-saint-denis",
    landmarks: ["Centre commercial Rosny 2", "A86", "RER E", "Noisy-le-Sec (limite)"],
    intro: "Rosny-sous-Bois accueille l'un des plus grands centres commerciaux d'Île-de-France, Rosny 2. C'est aussi une ville d'entreprises et de services bien desservie par l'A86 et le RER E, idéale pour la distribution last-mile.",
    logisticsContext: "Rosny est accessible depuis l'A86. Nos scooters desservent Rosny 2 et toutes les zones d'entreprises de la ville en moins de 30 minutes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Rosny et les tribunaux voisins.",
      medical: "Transport inter-établissements de santé de Rosny.",
      ecommerce: "Livraisons pour les boutiques de Rosny 2 et les e-commerçants locaux.",
      corporate: "Navettes entre les entreprises de Rosny et leurs partenaires.",
      evenementiel: "Transport pour les événements et promotions de Rosny 2.",
      grandsComptes: "Compte pour les grandes enseignes de Rosny 2.",
    },
    keyClients: ["Rosny 2", "Enseignes retail", "PME", "Services"],
    distanceParis: "~20 min de Paris 20e",
    pricingZone: "standard",
    seoTitle: "Coursier Rosny-sous-Bois — Rosny 2, 93110 | ONE CONNEXION",
    seoDesc: "Coursier express à Rosny-sous-Bois (93). Rosny 2, retail, PME. Enlèvement < 45 min.",
    seoKeywords: ["coursier Rosny-sous-Bois", "livraison express 93110", "coursier Rosny 2"],
  }),
  makeZone({
    slug: "epinay-sur-seine",
    dept: "93800",
    name: "Épinay-sur-Seine",
    category: "seine-saint-denis",
    landmarks: ["Studios d'Épinay", "Seine", "A86", "Saint-Denis (limite)"],
    intro: "Épinay-sur-Seine abrite les célèbres Studios d'Épinay, l'un des plus anciens et plus importants complexes de production cinématographique de France. Ce secteur audiovisuel génère des besoins logistiques très spécifiques : transport de rushes, de costumes, de matériel technique.",
    logisticsContext: "Épinay est accessible depuis l'A86. Nos coursiers connaissent les accès aux studios et les procédures de livraison sur plateau.",
    sectorExamples: {
      juridique: "Transport de contrats de production entre les studios et les maisons de production parisiennes.",
      medical: "Transport inter-établissements de santé d'Épinay.",
      ecommerce: "Livraisons pour les commerces d'Épinay.",
      corporate: "Navettes entre les Studios d'Épinay et les maisons de production parisiennes.",
      evenementiel: "Transport de matériel technique, costumes et accessoires pour les tournages.",
      grandsComptes: "Compte pour les grandes productions et studios d'Épinay.",
    },
    keyClients: ["Studios d'Épinay", "Maisons de production", "Équipes tournage", "PME"],
    distanceParis: "~20 min de Paris 18e",
    pricingZone: "standard",
    seoTitle: "Coursier Épinay-sur-Seine — Studios, 93800 | ONE CONNEXION",
    seoDesc: "Coursier express à Épinay-sur-Seine (93). Studios de cinéma, productions, PME. Enlèvement < 45 min.",
    seoKeywords: ["coursier Épinay-sur-Seine", "livraison express 93800", "coursier studios Épinay"],
  }),
  makeZone({
    slug: "noisy-le-sec",
    dept: "93130",
    name: "Noisy-le-Sec",
    category: "seine-saint-denis",
    landmarks: ["Gare de triage", "A3", "RER E", "Bondy (limite)", "Bobigny (limite)"],
    intro: "Noisy-le-Sec est un nœud ferroviaire et routier important du 93. Sa gare de triage fret et sa position sur l'A3 en font un point de transit pour de nombreuses entreprises de la petite couronne nord-est.",
    logisticsContext: "Noisy-le-Sec est accessible depuis l'A3. Nos coursiers relient Noisy à Paris 20e et Bobigny en moins de 25 minutes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Noisy et les tribunaux de Bobigny.",
      medical: "Transport inter-établissements de santé de Noisy-le-Sec.",
      ecommerce: "Livraisons pour les boutiques et commerçants de Noisy.",
      corporate: "Navettes entre les entreprises de Noisy et leurs partenaires.",
      evenementiel: "Transport de matériel pour les événements locaux.",
      grandsComptes: "Compte pour les PME et industries de Noisy-le-Sec.",
    },
    keyClients: ["Entreprises fret", "PME", "Services"],
    distanceParis: "~20 min de Paris 20e",
    pricingZone: "standard",
    seoTitle: "Coursier Noisy-le-Sec — Livraison express 93130 | ONE CONNEXION",
    seoDesc: "Coursier express à Noisy-le-Sec (93). PME, industries, fret. Enlèvement < 45 min.",
    seoKeywords: ["coursier Noisy-le-Sec", "livraison express 93130", "coursier 93 Noisy-le-Sec"],
  }),
  makeZone({
    slug: "villepinte",
    dept: "93420",
    name: "Villepinte",
    category: "seine-saint-denis",
    landmarks: ["Paris Nord Villepinte (salons)", "Aéroport Roissy CDG (15 min)", "A1", "A104"],
    intro: "Villepinte accueille le Parc des Expositions Paris Nord Villepinte, l'un des plus grands complexes d'exposition au monde (SIAL, Foire de Paris, Equiphotel…). Chaque salon génère des besoins logistiques intenses : matériel, échantillons, documents, badges.",
    logisticsContext: "Villepinte est à 15 minutes de Roissy CDG et à 25 minutes de Paris 18e. Nos coursiers renforcent leur présence lors des grands salons pour assurer une réactivité maximale.",
    sectorExamples: {
      juridique: "Transport de contrats et documents lors des salons professionnels de Villepinte.",
      medical: "Transport de matériel médical lors des salons de santé (Medica, Hospitalia).",
      ecommerce: "Livraisons urgentes de matériel et d'échantillons pendant les salons retail.",
      corporate: "Navettes entre les stands d'exposition et les hôtels ou partenaires proches.",
      evenementiel: "Transport de matériel, supports de communication et prototypes pendant les salons.",
      grandsComptes: "Compte pour les exposants récurrents des salons de Villepinte.",
    },
    keyClients: ["Parc des Expositions Villepinte", "Exposants SIAL, Foire de Paris", "Organisateurs de salons"],
    distanceParis: "~25 min de Paris 18e",
    pricingZone: "standard",
    seoTitle: "Coursier Villepinte — Paris Nord Villepinte, Salons 93420 | ONE CONNEXION",
    seoDesc: "Coursier express à Villepinte (93). Paris Nord Villepinte, salons professionnels. Enlèvement < 45 min.",
    seoKeywords: ["coursier Villepinte", "livraison express 93420", "coursier salons Villepinte", "coursier Paris Nord Villepinte"],
  }),
  makeZone({
    slug: "tremblay-en-france",
    dept: "93290",
    name: "Tremblay-en-France",
    category: "seine-saint-denis",
    landmarks: ["Aéroport Roissy CDG (5 min)", "Zone aéroportuaire", "A1", "A104"],
    intro: "Tremblay-en-France est la porte d'entrée logistique de Roissy CDG. Les zones d'activités aéroportuaires, les entrepôts fret et les hôtels d'aéroport créent un besoin permanent en transport express B2B.",
    logisticsContext: "Tremblay est à 5 minutes de Roissy CDG. Nos coursiers assurent des liaisons rapides entre l'aéroport et Paris ou toute la petite couronne.",
    sectorExamples: {
      juridique: "Transport de contrats et documents entre les entreprises aéroportuaires et leurs conseils.",
      medical: "Transport de médicaments et matériel médical urgent depuis l'aéroport.",
      ecommerce: "Livraisons express depuis et vers Roissy pour les e-commerçants internationaux.",
      corporate: "Navettes entre les entreprises de la zone aéroportuaire et Paris.",
      evenementiel: "Transport de matériel pour les événements des hôtels d'aéroport.",
      grandsComptes: "Compte pour les opérateurs aéroportuaires et les groupes de la zone de Roissy.",
    },
    keyClients: ["Opérateurs aéroportuaires Roissy", "Entrepôts fret", "Hôtels d'aéroport", "Transitaires"],
    distanceParis: "~30 min de Paris 18e",
    pricingZone: "standard",
    seoTitle: "Coursier Tremblay-en-France — Roissy CDG, Zone aéroportuaire 93 | ONE CONNEXION",
    seoDesc: "Coursier express à Tremblay-en-France (93). Roissy CDG, zone fret, aéroportuaire. Enlèvement < 45 min.",
    seoKeywords: ["coursier Tremblay-en-France", "livraison express 93290", "coursier Roissy CDG Tremblay"],
  }),
  makeZone({
    slug: "le-blanc-mesnil",
    dept: "93150",
    name: "Le Blanc-Mesnil",
    category: "seine-saint-denis",
    landmarks: ["Zone industrielle", "A1", "Le Bourget (limite)", "Drancy (limite)"],
    intro: "Le Blanc-Mesnil est une ville industrielle et de services du nord du 93, proche du Bourget. Son tissu économique dense et sa position sur l'A1 en font une ville active pour les flux logistiques B2B.",
    logisticsContext: "Le Blanc-Mesnil est accessible depuis l'A1. Nos coursiers desservent la ville et ses zones industrielles en moins de 30 minutes depuis Paris.",
    sectorExamples: {
      juridique: "Transport entre les cabinets du Blanc-Mesnil et les tribunaux de Bobigny.",
      medical: "Transport inter-établissements de santé du Blanc-Mesnil.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants locaux.",
      corporate: "Navettes entre les PME industrielles et leurs partenaires.",
      evenementiel: "Transport pour les événements professionnels de la zone.",
      grandsComptes: "Compte pour les industriels et logisticiens du Blanc-Mesnil.",
    },
    keyClients: ["Industriels", "PME logistiques", "Services B2B"],
    distanceParis: "~25 min de Paris 18e",
    pricingZone: "standard",
    seoTitle: "Coursier Le Blanc-Mesnil — Zone industrielle 93150 | ONE CONNEXION",
    seoDesc: "Coursier express au Blanc-Mesnil (93). Industries, PME, logistique. Enlèvement < 45 min.",
    seoKeywords: ["coursier Le Blanc-Mesnil", "livraison express 93150", "coursier 93 Blanc-Mesnil"],
  }),
  makeZone({
    slug: "gagny",
    dept: "93220",
    name: "Gagny",
    category: "seine-saint-denis",
    landmarks: ["Forêt de Bondy", "RER E", "A3", "Neuilly-sur-Marne (limite)"],
    intro: "Gagny est une ville résidentielle de l'est du 93, aux portes de la forêt de Bondy. Son tissu économique, principalement composé de PME, de commerces et de professions libérales, génère des besoins logistiques réguliers.",
    logisticsContext: "Gagny est accessible depuis l'A3. Nos coursiers relient Gagny à Paris 20e en moins de 30 minutes.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Gagny et les tribunaux de Bobigny.",
      medical: "Transport inter-établissements de santé de Gagny.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants de Gagny.",
      corporate: "Navettes entre les PME de Gagny et leurs partenaires.",
      evenementiel: "Transport pour les événements locaux.",
      grandsComptes: "Compte pour les PME multi-sites de Gagny.",
    },
    keyClients: ["PME", "Professions libérales", "Commerces", "Services"],
    distanceParis: "~30 min de Paris 20e",
    pricingZone: "standard",
    seoTitle: "Coursier Gagny — Livraison express 93220 | ONE CONNEXION",
    seoDesc: "Coursier express à Gagny (93). PME, professions libérales, commerces. Enlèvement < 45 min.",
    seoKeywords: ["coursier Gagny", "livraison express 93220", "coursier 93 Gagny"],
  }),
  makeZone({
    slug: "neuilly-sur-marne",
    dept: "93330",
    name: "Neuilly-sur-Marne",
    category: "seine-saint-denis",
    landmarks: ["Hôpital Maison-Blanche", "Marne", "A4", "Neuilly-Plaisance (limite)"],
    intro: "Neuilly-sur-Marne abrite l'Hôpital Maison-Blanche, établissement psychiatrique de référence. Les bords de Marne attirent également des entreprises de services. La ville est bien desservie par l'A4.",
    logisticsContext: "Neuilly-sur-Marne est accessible depuis l'A4. Nos coursiers relient la ville à Paris 12e et Vincennes en moins de 25 minutes.",
    sectorExamples: {
      juridique: "Transport de documents entre les établissements de Neuilly-sur-Marne et les juridictions.",
      medical: "Transport de documents et matériel médical depuis l'Hôpital Maison-Blanche.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants de Neuilly-sur-Marne.",
      corporate: "Navettes entre les PME de Neuilly-sur-Marne et leurs partenaires.",
      evenementiel: "Transport pour les événements locaux.",
      grandsComptes: "Compte pour l'Hôpital Maison-Blanche et les structures locales.",
    },
    keyClients: ["Hôpital Maison-Blanche", "PME bords de Marne", "Services"],
    distanceParis: "~25 min de Paris 12e",
    pricingZone: "standard",
    seoTitle: "Coursier Neuilly-sur-Marne — Hôpital Maison-Blanche 93330 | ONE CONNEXION",
    seoDesc: "Coursier express à Neuilly-sur-Marne (93). Hôpital Maison-Blanche, PME. Enlèvement < 45 min.",
    seoKeywords: ["coursier Neuilly-sur-Marne", "livraison express 93330", "coursier 93 Neuilly-sur-Marne"],
  }),
  makeZone({
    slug: "livry-gargan",
    dept: "93190",
    name: "Livry-Gargan",
    category: "seine-saint-denis",
    landmarks: ["Hôpital Intercommunal de Montfermeil", "Forêt de Bondy", "A3", "A86"],
    intro: "Livry-Gargan est une ville résidentielle du nord-est du 93, proche de la forêt de Bondy et de l'Hôpital Intercommunal de Montfermeil. Son tissu économique actif comprend des PME, des artisans et des professions libérales.",
    logisticsContext: "Livry-Gargan est accessible depuis l'A3 et l'A86. Nos coursiers desservent la ville rapidement.",
    sectorExamples: {
      juridique: "Transport entre les cabinets de Livry-Gargan et les juridictions de Bobigny.",
      medical: "Transport vers l'Hôpital Intercommunal de Montfermeil et les laboratoires partenaires.",
      ecommerce: "Livraisons pour les boutiques et e-commerçants de Livry-Gargan.",
      corporate: "Navettes entre les PME de Livry-Gargan et leurs partenaires.",
      evenementiel: "Transport pour les événements locaux.",
      grandsComptes: "Compte pour les PME multi-sites de Livry-Gargan.",
    },
    keyClients: ["Hôpital Intercommunal Montfermeil", "PME", "Artisans"],
    distanceParis: "~30 min de Paris 20e",
    pricingZone: "standard",
    seoTitle: "Coursier Livry-Gargan — 93190 | ONE CONNEXION",
    seoDesc: "Coursier express à Livry-Gargan (93). PME, médical, artisans. Enlèvement < 45 min.",
    seoKeywords: ["coursier Livry-Gargan", "livraison express 93190", "coursier 93 Livry-Gargan"],
  }),
];
